### ISSUE TITLE
how to use this in a windows machine, using boot2docker

### ISSUE THREAD

**Issue by joeyhipolito** [jwilder/nginx-proxy#100]
I've tried

    docker run --name=nginx-proxy -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy

    docker run --name site -d -p 81:80 -e "VIRTUAL_HOST=virtualhost.dev" --volumes-from data-desktop dockerfile/nginx:latest

result

    443/tcp, 0.0.0.0:81->80/tcp > site
    443/tcp, 0.0.0.0:80->80/tcp > nginx-proxy

This does not work, and I thought it's because windows doesn't have `0.0.0.0`, so i've tried using

     docker run --name=nginx-proxy -d -p 127.0.0.1:80:80 -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy

    docker run --name site -d -p 127.0.0.1:81:80 -e "VIRTUAL_HOST=virtualhost.dev" --volumes-from data-desktop dockerfile/nginx:latest

result

    443/tcp, 127.0.0.1:81->80/tcp > site
    443/tcp, 127.0.0.1:80->80/tcp > nginx-proxy

This still does not work, gives me `This webpage is not available`, same as the previous

What could be the solution to this:

**Comment by jwilder** [comment]
I have not tried nginx-proxy on windows or w/ boot2docker but my guess is that you need to use the IP returned from `boot2docker ip` and add a hosts file entry for your virtual hosts pointing to that IP.  

See https://docs.docker.com/installation/windows/#container-port-redirection

**Comment by thaJeztah** [comment]
Also worth noting that the site-container only has to *expose* a port (e.g. by adding `EXPOSE 80` in the Dockerfile). You don't need to *publish* that port. All trafic to the site will go through the nginx-proxy. So, this should be sufficient;

    docker run --name site -d -e "VIRTUAL_HOST=virtualhost.dev" --volumes-from data-desktop dockerfile/nginx:latest

However, as Jason mentioned you need to use the right IP-address to access the site and will need a DNS or entries in your host-file pointing to that address.

Out of curiosity, were you able to access the site via `http://<boot2docker-ip>:81` in your original example (thus, *with* the `-p 81:80`)?

**Comment by thaJeztah** [comment]
One more thing l noted; ` dockerfile/nginx` is *not* the official nginx image. I know some people think it is, however, the official nginx image is simply `nginx`. It can be found here on Docker Hub;

https://registry.hub.docker.com/_/nginx/

**Comment by joeyhipolito** [comment]
@jwilder  and @thaJeztah my bad, it turns out that I've missed the point of using boot2docker ip instead, which is the correct way.

> but my guess is that you need to use the IP returned from boot2docker ip and add a hosts file entry for your virtual hosts pointing to that IP.

**Comment by thaJeztah** [comment]
Good to hear this worked for you!

Could you close this issue, to mark it "resolved"? Thanks!
