### ISSUE TITLE
How to use ssl_client_certificate method

### ISSUE THREAD

**Issue by HollyGhos** [jwilder/nginx-proxy#1027]
Hi,
I’m just starting using your cool project and I’d like to protect some of my servers using ssl_client_certificate method. Is there an environment setting for using client certificates and crl-files or will I end up in generating an individual vhost file for each of the servers I’d like to protect?
Looking forward seeing an answer or at least a hint
Holger

**Comment by HollyGhos** [comment]
Greatest tool ever ;o)
I just have to set up /etc/nginx/vhost.d/{VIRTUAL_HOST} for my instance and add 
ssl_client_certificate with the path to my root ca and set ssl_verify_client to 'on'
nginx-proxy is adding the let's encrypt location to this vhost file and include the vhost for this server.
Magic - thanks jwilder for this great image.
Holger

**Comment by enric1994** [comment]
Hi @HollyGhos ,
How did you modify the .conf file?
I tried to mount the file using the docker-compose but with no results.

Thanks!

**Comment by HollyGhos** [comment]
Hi enric - 
First of all I did not modify any *.conf file
What did you try to mount?
My volumes area in the compose file looks like:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginxproxy_certs:/etc/nginx/certs:ro
      - ./nginxproxy_vhosts:/etc/nginx/vhost.d
      - ./nginxproxy_html:/usr/share/nginx/html

In the ./nginxproxy_vhosts directory I put a file with the name www.example.com (must be the same name as your virtual host is called).
The file has just two lines:

ssl_client_certificate    /etc/nginx/certs/ca.cert.pem;  #Path to Root Cert for client certification
ssl_verify_client on;

If you use LetsEncrypt comp - the tool will add additional lines at the beginning during the initial run.
Hope this could help you for the moment.
If not just ask further questions

**Comment by enric1994** [comment]
Thanks Hoger!
Yesterday I enabled the mutual connection using the "$docker exec" command to modify the container while running, thenI run $service nginx reload. It works but it's so tricky.

The method you propose is much better! Thanks a lot.

Enric
