### ISSUE TITLE
Multiple Hosts, not proxying through correctly

### ISSUE THREAD

**Issue by johnjelinek** [jwilder/nginx-proxy#103]
```
$ docker run -d -p 80:80 -p 443:443 --name nginx -v /home/user/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy

$ docker run -d --name johnjelinek.com -e VIRTUAL_HOST=www.johnjelinek.com -e VIRTUAL_PORT=2368 -v /home/user/johnjelinek.com:/ghost-override dockerfile/ghost

$ docker run -d --name beaneighbor.org -e VIRTUAL_HOST=www.beaneighbor.org -e VIRTUAL_PORT=2368 -v /home/user/beaneighbor.org:/ghost-override dockerfile/ghost

$ tree certs/
certs/
├── www.beaneighbor.org.crt
├── www.beaneighbor.org.key
├── www.johnjelinek.com.crt
└── www.johnjelinek.com.key

$ curl https://johnjelinek.com
curl: (51) SSL: no alternative certificate subject name matches target host name 'johnjelinek.com'
```

The beaneighbor `VIRTUAL_HOST` isn't working, and `johnjelinek` routes to the `beaneighbor` site, and `www.johnjelinek.com` routes correctly. What am I missing?

**Comment by johnjelinek** [comment]
Changing `VIRTUAL_HOST=www.beaneighbor.org` to include non-www subdomain seems to help `VIRTUAL_HOST=beaneighbor.org,www.beaneighbor.org`.

**Comment by jwilder** [comment]
I think you need to start your containers w/ both `www.` and the root domain.  It looks like you have started the containers w/ `www` but are curling the root domain which won't automatically redirect to the root domain.  nginx-proxy will just see the root domain and it'll get handled by the default server currently.

**Comment by johnjelinek** [comment]
Would it be better if I set `VIRTUAL_HOST=*.johnjelinek.com`?



—

**Comment by jwilder** [comment]
Yeah that should work.

**Comment by johnjelinek** [comment]
When I have `VIRTUAL_HOST=*.johnjelinek.com` and if I browse to https://johnjelinek.com, the browser redirects to https://%2A.johnjelinek.com

**Comment by jwilder** [comment]
Hmm.  Ok.  Probably need to specify each one separately then.  I thought `*.johnjelinek.com` would work but maybe it won't.

**Comment by md5** [comment]
You may want to try: `VIRTUAL_HOST=johnjelinek.com,*.johnjelinek.com`

**Comment by md5** [comment]
[Actually...](http://nginx.org/en/docs/http/server_names.html#wildcard_names)

> A special wildcard name in the form “.example.org” can be used to match both the exact name “example.org” and the wildcard name “*.example.org”.

Try: `VIRTUAL_HOST=.johnjelinek.com`

**Comment by johnjelinek** [comment]
`VIRTUAL_HOST=.johnjelinek.com` did not work either, it redirects to `https://.johnjelinek.com`. I guess I'll just stick with `johnjelinek.com,www.johnjelinek.com`

**Comment by md5** [comment]
That looks like a bug in [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L91)

It should not be using `{{ $host }}`, but should instead rely on nginx to get the appropriate hostname to redirect to.

**Comment by md5** [comment]
I think something like this could work instead of the current `rewrite`:
```
return 301 https://$host$request_uri;
```

**Comment by md5** [comment]
See #108

**Comment by jwilder** [comment]
Should be resolved now w/ #108

**Comment by murbanowicz** [comment]
I have similar issue. using VIRTUAL_HOSTNAME=.mydomain.com
is giving working server only mydomain.com, any subdomain or www.mydomain.com is not working at all

I have tried with VIRTUAL_HOSTNAME=mydomain.com, www.mydomain.com and still only without www was working. 
What can be wrong?

**Comment by thomasleveil** [comment]
@murbanowicz, this is not a discussion forum but an issue tracker. Please refrain from commenting on closed issues
