### ISSUE TITLE
Running 2 nginx : jwilder/nginx-proxy:0.6.0 and jwilder/nginx-proxy:alpine

### ISSUE THREAD

**Issue by neryangj** [jwilder/nginx-proxy#1033]
Hi,

Tried to run two different version of nginx images on my ubuntu servers.  
0.6.0 work just fine and can proxified the web services configured to it.  however for alpine, got the below error
bash-4.3# forego start
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
nginx.1    | 2018/01/18 06:02:46 [emerg] 77#77: no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
nginx.1    | nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
forego     | sending SIGTERM to dockergen.1
bash-4.3# nginx -t
2018/01/18 06:03:06 [emerg] 82#82: no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
nginx: configuration file /etc/nginx/nginx.conf test failed
bash-4.3#

Line 55 is 

# udmgitlab.example.co.nz
upstream udmgitlab.exmaple.co.nz {
}
server {
        server_name udmgitlab.exmaple.co.nz;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://udmgitlab.exmaple.co.nz
        }

which is the web service hosted in nginx 0.6.0
Is it normalthat each nginx default configurations will collect all the web services running on my machine

**Comment by neryangj** [comment]
already resolved

**Comment by andrewsosa** [comment]
@neryangj How did you solve the issue?
