### ISSUE TITLE
Cannot stop container - Cannot kill container - 

### ISSUE THREAD

**Issue by evertramos** [jwilder/nginx-proxy#1034]
I am having an issue with the proxy that happens sometimes, not sure what triggered.

But, eventually I try to restart some services and the `docker-containerd.sock` get stuck, and I receive the following message:

``` bash
Error response from daemon: cannot stop container: nginx-web: Cannot kill container f3c5f5....a623482623d2: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown
```

Have you ever faced this issue?

Thanks in advace.

**Comment by evertramos** [comment]
I am using this setup:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

Sepparating docker-gen from webproxy.

**Comment by jmarcos-cano** [comment]
@evertramos probably related to https://github.com/moby/moby/issues/36002

**Comment by evertramos** [comment]
@jmarcos-cano Thank you very much!! Tjhat´s it!!

**Comment by vardhmanandroid2015** [comment]
Updating to latest version helped me to overcome with this issue....
Earlier version when this error was happening - 18.02.0-ce
Updated to 18.06.1-ce
