### ISSUE TITLE
Weird logs in nginx-proxy container

### ISSUE THREAD

**Issue by perarg** [jwilder/nginx-proxy#1040]
I noticed in nginx-proxy container some suspicious logs. I use a custom made domain for testing purposes only, but in nginx-proxy container i get the following requests for unknown domains:

```
nginx-proxy    | nginx.1    | motorsinspiration.com 197.27.60.117 - - [25/Jan/2018:00:52:09 +0000] "GET /wp-login.php HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"
nginx-proxy    | nginx.1    | motorsinspiration.com 197.27.60.117 - - [25/Jan/2018:00:52:10 +0000] "GET / HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"
nginx-proxy    | nginx.1    | tech-inspiration.com 66.249.76.156 - - [25/Jan/2018:00:53:21 +0000] "GET /robots.txt HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

Every request gets a 503 as i see, but who is making these requests !?

**Comment by haster** [comment]
The robots.txt request seems to come from the google web crawler, which crawls the web to index pages for its search engine.

The wp-login.php request might be hackers/script-kiddies/malware scanning the web for vulnerable wordpress sites to hack and add to a botnet or something.

**Comment by perarg** [comment]
That is my first though too, but the weird thing is that the domain is not published, it's an imaginary name, i made up and put in in localhost as `server-ip example.com`. The server-ip is a DigitalOcean droplet where the containers live.

There is a weirdest thing i cannot explain. If i type these urls (ex. motorsinspiration.com) in my browser, the nginx container receives the request! But i have never make a connection to these urls.

**Comment by haster** [comment]
I can `dig motorsinspiration.com` and get 178.62.255.94 as the answer. If I `dig ns` to ask for its nameservers I get arubadns and technorail. It seems somebody reguistered these domainnames to point to your servers.

Maybe digital ocean, or something in your network, auto-published these hostnames? Or somebody else did for you and forgot to tell you?

$ dig ns motorsinspiration.com

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> ns motorsinspiration.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35589
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;motorsinspiration.com.		IN	NS

;; ANSWER SECTION:
motorsinspiration.com.	1800	IN	NS	dns3.arubadns.net.
motorsinspiration.com.	1800	IN	NS	dns2.technorail.com.
motorsinspiration.com.	1800	IN	NS	dns.technorail.com.
motorsinspiration.com.	1800	IN	NS	dns4.arubadns.cz.

;; Query time: 63 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Jan 26 09:32:08 CET 2018
;; MSG SIZE  rcvd: 159
```

**Comment by perarg** [comment]
Wow, thank you @haster for your time and help. I understand that this question is beyond the scope of nginx-proxy, so i have to close the issue and try to figure out what is going on here...
