### ISSUE TITLE
jenkins cannot be proxy

### ISSUE THREAD

**Issue by MicroLord** [jwilder/nginx-proxy#1049]
my docker run : 
docker run -d -p 8084:8080 --name jenkins 
-e VIRTUAL_HOST=jenkins.xxxx.com 
-v /var/run/docker.sock:/var/run/docker.sock 
-v $(which docker):/usr/bin/docker -v /lib64/libltdl.so.7:/lib64/libltdl.so.7 
-v /var/jenkins_home:/var/jenkins_home 
-v ~/.m2:/root/.m2
jenkins/jenkins:lts

ip can access , but the host can't access , ping jenkins.xxxx.com also succeed ! and others host like api.xxxx.com through your config succeed , just the jenkins can't , please help me , thanks

**Comment by PixiBixi** [comment]
I think you shouldn't expose the port but add -e VIRTUAL_PORT=8084

**Comment by MicroLord** [comment]
@PixiBixi thanks for your suggestion ,  see : https://github.com/jwilder/nginx-proxy#multiple-ports . i think the port must be exposed ! and i try your advice , it not work !

**Comment by dopyoman** [comment]
@MicroLord How did you solve your issue?
