### ISSUE TITLE
Per-VIRTUAL_HOST settings

### ISSUE THREAD

**Issue by Archcry** [jwilder/nginx-proxy#1054]
I mounted `/etc/nginx/vhost.d` on my local filesystem to configurure the `client_max_body_size`. I saw that letsencrypt companion adds a block for validating that the domain actually belongs to me in the default vhost config. I set up my vhost to look like this:

```
include /etc/nginx/vhost.d/default;
client_max_body_size 10m;
```

Will the `include` of the default vhost work here?

**Comment by jwilder** [comment]
Hi, I'd like to keep Github issues for actionable bug reports or feature requests.  Please ask questions in the [Q&A Group](https://groups.google.com/forum/#!forum/nginx-proxy).

Thanks!
