### ISSUE TITLE
Howto: Load the chainfile?

### ISSUE THREAD

**Issue by quartzadmin** [jwilder/nginx-proxy#1060]
Looking at the https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl file I can see there is a check for the file's existence...

`{{ if (exists (printf "/etc/nginx/certs/%s.chain.crt" $cert)) }}`

but if I rename my go-daddy bundle file, gd_bundle-g2-g1.crt, with the matching domain name, 'somedomain.com.chain.crt' it does not get added. The site does load the main certificate correctly though. The result is a missing key chain error when validating the site security. 

Am I missing something obvious?

**Comment by jwilder** [comment]
Fixed by #984.  I think the extension needs to be `.pem` now.

**Comment by geedon** [comment]
I'm afraid the naming of the chain fail never did resolve the issue for me on all the testing sites (e.g www.ssllabs.com/ssltest or www.sslshopper.com). All the sites I could find were indicating that the was an missing or invalid chain. 

This could just be a quirk with GoDaddy certs as there's no nginx download option, so I was left using the Apache equivalent. Still gives you the 2 files you expect, but it seems nginx wants you to append the 2 files together into one file, and, to my knowledge simply ignore the chain file option as its now in the original. Took me forever to find this. I wonder why this is not more commonly documented. 

So command would be something like...

cat orig.crt >> orig-bundle.crt  solo-cert-to-place-in-nginx-matching-your-domain-name.crt

Problem solved \o/
