### ISSUE TITLE
Can I serve both 80 and 443 from one url ?

### ISSUE THREAD

**Issue by rivaros** [jwilder/nginx-proxy#1067]
My container has nginx listening on both HTTP and HTTPS
```
server {
      listen 80;
      listen 443 ssl;
```
and exposes both 80 and 443

I tried various combinations of VIRTUAL_HOST, VIRTUAL_PROTO and VIRTUAL_PORT, but in
/etc/nginx/conf.d/default in nginx-proxy it always creates a 301 redirect from 80 to 443.

So I cannot reach my website with HTTP.
I need the ability to use both:
http://mysite.com
and
https://mysite.com

P.S.: mysite.com points to 127.0.0.1 where nginx-proxy has both 80 and 443 ports mapped.

**Comment by rivaros** [comment]
If anybody seeking the same, use HTTPS_METHOD=noredirect

**Comment by janul** [comment]
Hi,
I have the same problem. 
I passed  _HTTPS_METHOD=noredirect_ to the container and 
/etc/nginx/conf.d/default.conf file still contains:
>   server {
        server_name vhost.example.com;
        listen 80 default_server;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
   }


My ENV from container:

>   DOCKER_GEN_VERSION=0.7.4 
  HOSTNAME=79c6e705f913 
  NJS_VERSION=1.13.12.0.2.0-1~stretch  
  NGINX_VERSION=1.13.12-1~stretch  
  DHPARAM_BITS=1024
  PWD=/etc/nginx/conf.d
  HOME=/root
  HTTPS_METHOD=noredirect
  TERM=xterm
  DOCKER_HOST=unix:///tmp/docker.sock
  DEFAULT_HOST=vhost.example.com
  SHLVL=1
  HSTS=off
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin  
_=/usr/bin/env
  OLDPWD=/etc/nginx
