### ISSUE TITLE
Error running notify command: nginx -s reload

### ISSUE THREAD

**Issue by Finkes** [jwilder/nginx-proxy#107]
I can't get the reverse proxy to work. I tried to install several demo wordpress pages to test the proxy but when I access one of the subdomains, only the default nginx page is shown.
I found following entry in the docker logs after starting another container:

dockergen.1 | 2015/02/24 17:57:20 Received event start for container d42067e8c353
dockergen.1 | 2015/02/24 17:57:20 Generated '/etc/nginx/conf.d/default.conf' from 7 containers
dockergen.1 | 2015/02/24 17:57:20 Running 'nginx -s reload'
dockergen.1 | 2015/02/24 17:57:20 Error running notify command: nginx -s reload, exit status 1

**Comment by jwilder** [comment]
Hard to say what the issue from that output.  I'd suggest this trying to debug it by:

1. Start up nginx-proxy w/ a shell:
  - `$ docker run -it -v /var/run/docker.sock:/tmp/docker.sock -p 80:80 jwilder/nginx-proxy bash`
2. run forego to get the error and then ctrl-c to exit it.
  - `$ forego start`
3. Validate the nginx config
  - `$ nginx -t`
4. Take a look at the generated file at `etc/nginx/conf.d/default.conf` to see what might be causing the issue.  You can post it here if nothing stands out.

**Comment by thaJeztah** [comment]
Could it be possible that one container has an invalid value set for `VIRTUAL_HOST` or `VIRTUAL_PORT`, causing a syntax error in the nginx `default.conf`?

You can try copying the generated `default.conf` to check if it contains something wrong.

You can copy the file from the container to the host using the [docker cp](https://docs.docker.com/reference/commandline/cli/#cp) command;

    docker cp <your-nginx-container-name>:/etc/nginx/conf.d/default.conf ./

**Comment by Finkes** [comment]
Thanks for your quick suggestions. The config file seams to be invalid. What confuses me most is this part: 

[...]
server_name _; # This is just an invalid value which will never trigger on a real hostname.
[...]

Here is the complete output:


# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  ''      '';
}

gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';

access_log /proc/self/fd/1 vhost;
error_log /proc/self/fd/2;

# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;

server {
	listen 80 default_server;
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	return 503;
}



upstream blog.mydomain.de {		
		   # mydomain_blog
		   server 172.17.0.90:80;
}

server {
	server_name blog.mydomain.de;

	location / {
		proxy_pass http://blog.mydomain.de;	
	}
}

upstream blog2.mydomain.de {	
		   # mydomain_blog2
		   server 172.17.0.89:80;
}

server {
	server_name blog2.mydomain.de;

	location / {
		proxy_pass http://blog2.mydomain.de;
		
	}
}

upstream ci2.mydomain.de {	
}

server {
	server_name ci2.mydomain.de;

	

	location / {
		proxy_pass http://ci2.mydomain.de;
		
	}
}


upstream ci3.mydomain.de {
}

server {
	server_name ci3.mydomain.de;
	location / {
		proxy_pass http://ci3.mydomain.de;	
	}
}


upstream qwe.mydomain.de {		
		   # testwordpress4
		   server 172.17.0.98:80;
}


server {
	server_name qwe.mydomain.de;
	location / {
		proxy_pass http://qwe.mydomain.de;
		
	}
}

**Comment by md5** [comment]
Looks like your `ci2.mydomain.de` and `ci3.mydomain.de` containers have no backends in their `upstream` block. Can you describe how you ran the containers with those `VIRTUAL_HOST` names?

**Comment by md5** [comment]
Or just provide the output of `docker ps` if that works for you.

**Comment by Finkes** [comment]
yeah sure.

I already hat an mysql container and two jenkins container running. 
First I created the reverse proxy server:

    sudo docker run --name reverseproxy -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy

Then I created the two wordpress containers with an command like this:

    sudo docker run -p 80 -d --name testwordpress2 --link my-mysql:mysql -e VIRTUAL_HOST=blog2.mydomain.de wordpress


And this is my **docker ps** output:


    CONTAINER ID        IMAGE                        COMMAND                CREATED             STATUS              PORTS                         NAMES
    d42067e8c353        wordpress:latest             "/entrypoint.sh apac   49 minutes ago      Up 49 minutes       80/tcp                        testwordpress4        
    48fbbed2fcf7        jwilder/nginx-proxy:latest   "forego start -r"      About an hour ago   Up About an hour    443/tcp, 0.0.0.0:80->80/tcp   reverseproxy          
    807e992098e5        jenkins:latest               "/usr/local/bin/jenk   2 hours ago         Up 2 hours          50000/tcp, 8080/tcp           jenkins2test          
    059c2b55f73a        jenkins:latest               "/usr/local/bin/jenk   2 hours ago         Up 2 hours          50000/tcp, 8080/tcp           backstabbing_carson   
    d585c1f5181a        wordpress:latest             "/entrypoint.sh apac   5 weeks ago         Up About an hour    80/tcp                        mydomain_blog2     
    b23442a9b9f9        wordpress:latest             "/entrypoint.sh apac   5 weeks ago         Up About an hour    80/tcp                        mydomain_blog      
    099952e1b0b5        mysql:latest                 "/entrypoint.sh mysq   5 weeks ago         Up 5 weeks          3306/tcp                      my-mysql

**Comment by md5** [comment]
I believe you want to add `VIRTUAL_PORT=8080` to your two Jenkins containers.

**Comment by md5** [comment]
It would be nice if `nginx-proxy` didn't generate an invalid config file in this case.

**Comment by Finkes** [comment]
Ok so you think this is caused due to not adding a VIRTUAL_HOST env variable to my existing containers?

**Comment by md5** [comment]
Are you saying that your existing containers don't already have `VIRTUAL_HOST=ci2.mydomain.de` and `VIRTUAL_HOST=ci3.mydomain.de` on them? I don't know where else `nginx-proxy` would get those names from.

What I was assuming was that your Jenkins containers already had `VIRTUAL_HOST` and that you need to add `VIRTUAL_PORT=8080`.

**Comment by jwilder** [comment]
Looks like https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L62 probably needs an else clause to avoid generating a broken config.

Maybe it could try and pick the first port starting w/ an `8` (to prefer 8080, 8000, etc..) and then just resort to the first one in this case.  It would just be trying to guess the right one when it gets here.    Better to set `VIRTUAL_PORT` though.

Somewhat related to this, I had planned to add a check/validate option to `docker-gen` so it could run something like `nginx -t` on the new config before updating it.  That would at least print an error in the logs saying the config is invalid and leave nginx in a good state (although out of date).

**Comment by md5** [comment]
@jwilder I'd probably arrange things so that the else condition there didn't generate an `upstream` block at all and the `server` block just has a `return 503` instead of a `location` block.

**Comment by md5** [comment]
Also, :+1: to the check command idea!

**Comment by Finkes** [comment]
I removed all the other containers and after that it was working again. But when I execute following command:

    sudo docker run -d -e VIRTUAL_HOST=jenkins.mydomain.de --name jenkins jenkins

This command however produces an empty entry inside the upstream

**Comment by md5** [comment]
Jenkins exposes both port 50000 and port 8080. That's why you need `VIRTUAL_PORT=8080`.

**Comment by md5** [comment]
@jwilder I realized that you can't exclude the `upstream` block without a lot of hacking, so maybe it would be good to do something like this when the port can't be determined: `server {{ $address.IP }} down;`

That way, the `upstream` would be valid and the server would generate a 5XX error.

**Comment by Finkes** [comment]
Oh i see, thanks. I thought it would detect those ports automatically and choose one of them by default. Thanks!

**Comment by md5** [comment]
If the container exposes more than one port, then the only case in which `nginx-proxy` will choose one by default is if it exposes port 80.

**Comment by jwilder** [comment]
Closing this since this can be resolved by specifying `VIRTUAL_PORT`.  Created #115 to track the broken config that can be generated in some cases.

**Comment by kzhmr1** [comment]
how do you check if the application has started in a container and make sure nginx does not route traffic to it until the application has started ?

**Comment by Glideh** [comment]
First of all thank you @jwilder for this very handy reverse proxy.
I'm getting the empty upstream issue and I don't know how to fix it.

My reverse proxy docker-compose:
```yml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

I have only one python application based on nginx/uwsgi, postgres, redis:
```yml
# ...
        ports:
            - "80"
        environment:
            - VIRTUAL_HOST=my.nice-host.net
            - VIRTUAL_PROTO=uwsgi
# ...
```

Whenever I start my service, I'm seeing nginx-proxy log telling me he can't reload
> Error running notify command: nginx -s reload

Here is the nginx validation:

```
$ docker exec nginx-proxy nginx -t
2016/11/26 10:31:02 [emerg] 101#101: no servers are inside upstream in /etc/nginx/conf.d/default.conf:36
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:36
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Here is the empty upstream config part:

```
$ docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf
[...]
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream u-book.net {
}
server {
	server_name u-book.net;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		include uwsgi_params;
		uwsgi_pass uwsgi://u-book.net;
	}
}
[...]
```

Can someone tell me what I am doing wrong ?

**Comment by Glideh** [comment]
Ok I see in #565 it could be linked to a different network issue
