### ISSUE TITLE
Missing /etc/nginx/network_internal.conf for alpine Docker image

### ISSUE THREAD

**Issue by n3v3rf411** [jwilder/nginx-proxy#1076]
I tried setting the env variable INTERNAL_ACCESS to containers and confirmed that in default.conf, server blocks contains the line `include /etc/nginx/network_internal.conf;` however for alpine image, `/etc/nginx/network_internal.conf` is missing.

In the non-alpine image, it is copied in here: https://github.com/jwilder/nginx-proxy/blob/d6042d08f15ea5d99d9b80cdc496bdfc69629274/Dockerfile#L27

**Comment by smpita** [comment]
+1
