### ISSUE TITLE
Slack or Reddit Support Resource

### ISSUE THREAD

**Issue by j7an** [jwilder/nginx-proxy#1079]
@jwilder The number of issues for the repo is getting out of hand. And there's still many open PRs. My suggestion is to create either a Slack channel(s) or a sub-Reddit for support questions as most are not bugs.

This should allow you and collaborators to focus on the PRs.

**Comment by rodrigoaguilera** [comment]
I see a lot of Free Software communities moving also to https://matrix.org/ and https://riot.im/ because of the limitations that slack imposes on the free tier.

Just a suggestion.

**Comment by jwilder** [comment]
This is a good idea.  I created a google group for Q & A: https://groups.google.com/forum/#!forum/nginx-proxy and will start redirecting questions on GH there.
