### ISSUE TITLE
Problem with HSTS=Off

### ISSUE THREAD

**Issue by MaxenceG2M** [jwilder/nginx-proxy#1080]
Hi there!

I want to use Nextcloud on my server, I use this docker-compose : https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml

But I don't want to enable HTST, so I add environment var like this:

    [...]
    proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      - HSTS=off
      - HTTPS_METHOD=noredirect
    [...]

(two variables, I really don't want to enable HSTS)

But, nothing to do, HSTS is enabled...
Verification with curl: 

    $ curl -s -vv https://myserver.com/ | grep -i Strict
    < strict-transport-security: max-age=31536000

The content of file `default.conf` in `conf.d` clearly have HSTS enabled: 

    $ docker exec -ti nextcloud_proxy_1 cat /etc/nginx/conf.d/default.conf
    [...]
       server {
            server_name myserver.com;
            listen 443 ssl http2 ;
            access_log /var/log/nginx/access.log vhost;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
            ssl_prefer_server_ciphers on;
            ssl_session_timeout 5m;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_certificate /etc/nginx/certs/myserver.com.crt;
            ssl_certificate_key /etc/nginx/certs/myserver.com.key;
            ssl_dhparam /etc/nginx/certs/myserver.com.dhparam.pem;
            add_header Strict-Transport-Security "max-age=31536000";
            include /etc/nginx/vhost.d/default;
            location / {
                    proxy_pass http://myserver.com;
            }
    }

Anyone can help me?
Thanks a lot!

**Comment by kamermans** [comment]
This is happening because `HSTS=off` is ignored if `HTTPS_METHOD=noredirect`.  I'm not entirely sure why that would make sense, although I might be the one that authored it, so let me dive into this and figure out why it is that way!

**Comment by kamermans** [comment]
It was a typo in the logical comparison for these operators - I've fixed it in #1111.

**Comment by MaxenceG2M** [comment]
Hello @kamermans, 
Thank for your anwser, and thank you for the fix! :)

Actually, when I use just `HTTPS_METHOD=noredirect`, I still have HSTS enabled.
(I'm not sur to clearly understand your fix, I suppose it's what you fix ^^)

**Comment by kamermans** [comment]
Hmm, strange, in any case, you can try out my pull-request version by using the image `kamermans/nginx-proxy:bugfix_cant-disable-hsts-noredirect` if you'd like, while we wait for it to be merged.

**Comment by sdanieru** [comment]
When will this be merged? Until it's fixed, I see no way to add any type of global add_header directives, as they get blown away by the dynamic addition of the HSTS add_header in server context in default.conf.

**Comment by kamermans** [comment]
@sdanieru there was a merge conflict with another change, so @jwilder wouldn't have been able to automatically merge it.  I've resolved the conflict, so I'll ping him and see if we can get this merged.

**Comment by kamermans** [comment]
@sdanieru you can set `HSTS=off` to prevent the HSTS header from being added.  This will work in the current version of `nginx-proxy` and my updated one.

**Comment by gingerlime** [comment]
I'm using `jwilder/nginx-proxy:latest` with both `HSTS=off` and `HTTPS_METHOD=noredirect` and I'm still seeing the strict transport headers

```
curl -s -D - https://example.com/  |grep strict-transport
strict-transport-security: max-age=31536000
```

Was this fixed pushed to docker hub?

**Comment by enchained** [comment]
Can confirm, still receiving those headers too, and adding those options doesn't change things for me. I'm adding it to proxy container for this compose: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml it's pulling nginx-proxy:alpine
and when I go inside the container, nginx.tmpl still has the old line
`{{ if (and (ne $https_method "noredirect") (ne $hsts "off")) }}`

**Comment by gingerlime** [comment]
@enchained I don't see an environment set with `HSTS=off` on the docker-compose file you linked to.

One thing that I realized after posting this, is that this environment variable needs to be set on the container being proxied by nginx-proxy (i.e. the one with `VIRTUAL_HOST=...`), rather than on the `nginx-proxy` container itself.
