### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by apnewberry** [jwilder/nginx-proxy#1082]
I'm trying to run [wallabag](https://github.com/wallabag/docker) with `nginx-proxy`. I can run Wallabag directly:

```
$ docker run --detach  -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 wallabag/wallabag
```
and it works (and redirects to the login page):
```
$ curl -I http://localhost
HTTP/1.1 302 Found
Server: nginx
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.1.14
Set-Cookie: PHPSESSID=f3977b6703abd265a234b46a8ef7ab90; path=/; HttpOnly
Cache-Control: no-cache, private
Date: Fri, 02 Mar 2018 07:49:58 GMT
Location: http://localhost/login
```

But then I try running it with `nginx-proxy`
```
docker run -d     --name nginx-proxy     -p 80:80     -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

docker run -d --name wallabag -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -e VIRTUAL_HOST=wallabag wallabag/wallabag
```
and I get this error message. 
```
curl -i http://wallabag.localhost
HTTP/1.1 503 Service Temporarily Unavailable
Server: nginx/1.13.8
Date: Fri, 02 Mar 2018 07:56:38 GMT
Content-Type: text/html
Content-Length: 213
Connection: keep-alive

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>

```

I'm sure it's my fault, but I'm not sure where. Any ideas where I could be messing this up? Thanks!

**Comment by mavais** [comment]
Following. Having the same issue when running reaction commerce with nginx reverse proxy and letsencrypt docker containers. My reaction commerce app runs on port 3000

**Comment by sickill** [comment]
Your `VIRTUAL_HOST` is set to `wallabag` but you're requesting `wallabag.localhost` - these are 2 different hostnames, and nginx-proxy returns 503 when there's no hostname match.

Have you tried with `-e VIRTUAL_HOST=wallabag.localhost` ?

**Comment by apnewberry** [comment]
@sickill Thanks for responding. Here's the result I get when trying that:

```
$ docker run -d     --name nginx-proxy     -p 80:80     -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

$ docker run -d --name wallabag -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -e VIRTUAL_HOST=wallabag.localhost wallabag/wallabag

$ curl -i http://wallabag.localhost
HTTP/1.1 502 Bad Gateway
Server: nginx/1.13.8
Date: Mon, 05 Mar 2018 01:29:41 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>

```

**Comment by sickill** [comment]
No idea what's happening here. But I would suggested dropping `-d` from both `docker run` commands and start them in foreground in 2 separate terminal tabs/windows. This way you can easily see all output/errors from the processes in these containers.

**Comment by apnewberry** [comment]
@sickill Good idea. It works well; the service was still starting up when I tried to connect to it. Running without `-d` allowed me to see when it was ready. Thanks!
