### ISSUE TITLE
502 Bad Gateway Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by neryangj** [jwilder/nginx-proxy#1085]
This works on my dev vm but  stops working on production
Server is ubuntu 16.04.4. Did I missed something?

nginx.1    | 2018/03/06 06:38:39 [error] 52#52: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.152.103, server: one.example.com, request: "GET / HTTP/1.1", upstream: "http://172.19.0.3:80/", host: "one.example.com"

version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    networks:
      - frontend
    ports:
      - "443:443"
      - "80:80"
      - "8080:80"
    volumes:
      - ./ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d

  teampass:
    image: teampass/teampass
    restart: always
    environment:
      VIRTUAL_HOST: one.example.com
depends_on:
      - db
    networks:
      - frontend
      - backend
    volumes:
      - ./teampass:/var/www/html

  db:
    restart: unless-stopped
    image: mysql/mysql-server:5.7
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass

  volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge
~

**Comment by jrichet** [comment]
HOW DID YOU SOLVE THIS?

**Comment by yppdr** [comment]
Up ?

**Comment by indapublic** [comment]
same
