### ISSUE TITLE
remove includeSubdomains

### ISSUE THREAD

**Issue by jgallen23** [jwilder/nginx-proxy#109]
https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L108

I think includeSubdomains should be removed here.  This bit me pretty hard without realizing that dev.app.com and stage.app.com would be automatically redirected to ssl too and I don't have a cert for those urls.

**Comment by jwilder** [comment]
Are you able to override this w/ a custom include?  https://github.com/jwilder/nginx-proxy#proxy-wide

**Comment by jgallen23** [comment]
the problem is that dev.app.com and stage.app.com are running on different servers and in the case of dev, I'm not running behind nginx, but the browser caches that data so I had to host file a different domain to get it to stop redirecting to https.

**Comment by jwilder** [comment]
I meant override it site-wide at the proxy level to remove the subdomain part.   You would add that where you are running nginx-proxy.

**Comment by jgallen23** [comment]
Not sure how I would remove the includeSubdomains when overriding. Can you let me know what the conf would have in it?

**Comment by jgallen23** [comment]
Thanks
