### ISSUE TITLE
Use both X-Real-IP and X-Forwarded-For for Nginx Proxy

### ISSUE THREAD

**Issue by j7an** [jwilder/nginx-proxy#1092]
I currently have the following to get the real IP passed to application containers.

```
set_real_ip_from  172.18.0.0/32;
real_ip_header    X-Real-IP;
real_ip_recursive on;
```

I would also like to add Cloudflare support without losing X-Real-IP. How do I use X-Real-IP for internal Docker IPs and X-Forwarded-For for Cloudflare IPs in same configuration?

**Comment by jwilder** [comment]
Unfortunately, I'm not sure how to do that.  I'd like to keep Github issues for actionable bug reports or feature requests.  Can you ask this question in the [Q&A Group](https://groups.google.com/forum/#!forum/nginx-proxy)?

Thanks!
