### ISSUE TITLE
Hide Nginx Version

### ISSUE THREAD

**Issue by brandon-welsch** [jwilder/nginx-proxy#1094]
Add possibility to hide Nginx Server Version

**Comment by matt-hh** [comment]
Hi, you can create your own version of nginx-proxy:

```
FROM jwilder/nginx-proxy:alpine
RUN echo 'server_tokens off;' > /etc/nginx/conf.d/server_tokens.conf
```

**Comment by brandon-welsch** [comment]
Okay, I'll try this ;)

Is it possible to integrate this, via an optional environment variable ?

**Comment by jwilder** [comment]
You could use a custom template and add something like:

```
{{ if ne $.Env.HIDE_SERVER_TOKENS "" }}
server_tokens off;
{{ end }}
```

And start the proxy with `-e HIDE_SERVER_TOKEN=off` and you custom template.

I think @matt-hh suggestion is simpler though.
