### ISSUE TITLE
Redirect to www subdomain

### ISSUE THREAD

**Issue by brandon-welsch** [jwilder/nginx-proxy#1095]
Hey, can I set up the container somehow to always redirect all requests to www ?

Example :
- domain.com => www.domain.com

**Comment by matt-hh** [comment]
Yes, you can do this with your own version of nginx-proxy.

1. Create this Dockerfile

```
FROM jwilder/nginx-proxy:alpine

ADD domain.com /etc/nginx/vhost.d/domain.com
```

2. Create a file named domain.com

```
if ($request_uri !~ "^/.well-known/acme-challenge")
{
  return 301 https://www.domain.com$request_uri;
}
```

The `if ($request_uri !~ "^/.well-known/acme-challenge")` is neccessary for docker-letsencrypt-nginx-proxy-companion. https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/345 😉

Hope this helps you.
