### ISSUE TITLE
compatibility problem: nginx-proxy - fedora server 21 - weave

### ISSUE THREAD

**Issue by setiseta** [jwilder/nginx-proxy#110]
i've created a issue on weave: https://github.com/zettio/weave/issues/422
but it seems more to be in nginx-proxy / docker-gen
maybe someone here has any suggestions?

nginx log:
forego | starting nginx.1 on port 5000
forego | starting dockergen.1 on port 5100
dockergen.1 | panic: runtime error: index out of range
dockergen.1 |
dockergen.1 | goroutine 16 [running]:
dockergen.1 | runtime.panic(0x779be0, 0x9bfafc)
dockergen.1 | /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
dockergen.1 | main.getContainers(0xc20804c200, 0x0, 0x0, 0x0, 0x0, 0x0)
dockergen.1 | /home/jwilder/go/src/github.com/jwilder/docker-gen/docker_client.go:144 +0xa94
dockergen.1 | main.generateFromContainers(0xc20804c200)
dockergen.1 | /home/jwilder/go/src/github.com/jwilder/docker-gen/docker-gen.go:150 +0x35
dockergen.1 | main.main()
dockergen.1 | /home/jwilder/go/src/github.com/jwilder/docker-gen/docker-gen.go:388 +0x40c
dockergen.1 |
dockergen.1 | goroutine 17 [runnable]:
dockergen.1 | runtime.MHeap_Scavenger()
dockergen.1 | /usr/local/go/src/pkg/runtime/mheap.c:507
dockergen.1 | runtime.goexit()
dockergen.1 | /usr/local/go/src/pkg/runtime/proc.c:1445
dockergen.1 |
dockergen.1 | goroutine 18 [runnable]:
dockergen.1 | bgsweep()
dockergen.1 | /usr/local/go/src/pkg/runtime/mgc0.c:1976
dockergen.1 | runtime.goexit()
dockergen.1 | /usr/local/go/src/pkg/runtime/proc.c:1445
dockergen.1 |
dockergen.1 | goroutine 19 [runnable]:
dockergen.1 | runfinq()
dockergen.1 | /usr/local/go/src/pkg/runtime/mgc0.c:2606
dockergen.1 | runtime.goexit()
dockergen.1 | /usr/local/go/src/pkg/runtime/proc.c:1445

**Comment by md5** [comment]
@squaremo [got it right](https://github.com/zettio/weave/issues/422#issuecomment-76386565) I believe:

> My best guess is that docker-gen is assuming something about the container config that doesn't hold in weave's case. Possibly it's this line, or its ancestor: https://github.com/jwilder/docker-gen/blob/0.3.7/docker_client.go#L152 (assumes that every env entry is of the form "X=Y"), which is at least close to the lines in the stack trace.

I've submitted a possible fix to `docker-gen`: https://github.com/jwilder/docker-gen/pull/65

**Comment by setiseta** [comment]
thx for the fast try to fix this.
i've tested this with lokal build and passed the new docker-gen into jwilder/nginx-proxy with -v
but it seems not to fix this problem.
i'm not familiar with go, so i don't know how to debug or get more information.

i just got this:
root@2e0f48c2694e:/app# forego start -r
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | panic: runtime error: index out of range
dockergen.1 |
forego     | starting dockergen.1 on port 5200
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to nginx.1

and if i run the docker-gen like in the Procfile i get this:
root@2e0f48c2694e:/app# docker-gen -watch -only-exposed -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x796a80, 0x9ec79c)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.getContainers(0xc20804c200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /pool/build/docker-gen/docker_client.go:152 +0xcb3
main.generateFromContainers(0xc20804c200)
        /pool/build/docker-gen/docker-gen.go:157 +0x35
main.main()
        /pool/build/docker-gen/docker-gen.go:395 +0x40c

goroutine 19 [finalizer wait]:
runtime.park(0x41e620, 0x9f0808, 0x9eea49)
        /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9f0808, 0x9eea49)
        /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

if you can give me some advises i can give you more information.

**Comment by md5** [comment]
Are you sure that's a local build of `docker-gen`? Line 152 of `docker_client.go` in my branch is `if len(parts) != 2 {`. I'm not sure how that could result in an `index out of range` panic.

I've pushed another commit that updates the `Makefile` to make sure that `./docker-gen -version` shows a different version for local builds. Could you please build that version with `make` and test again?

**Comment by setiseta** [comment]
hm, ok i re checked this, rebuilded, and now it works.
docker-gen -version shows an empty line if i build it myself.
thx, and sorry for wrong post / build

**Comment by md5** [comment]
You to build with make for -version to show anything.

Glad the fix worked for you!
