### ISSUE TITLE
Hiding backend api containers - proxy_pass does not seem to forward for custom location

### ISSUE THREAD

**Issue by identify1980** [jwilder/nginx-proxy#1102]
Given following scenario:

I have a docker-compose with a few backend api services (e.g. api1.example.com) and a frontend web application (e.g. www.example.com).
My nginx container (following Evert Ramos' example [1]) serves as reverse proxy for the frontend web application and proxy_pass'ing requests to my frontend web application. As I don't want to publish the backend api services, I thought of making them available by a custom location (e.g. www.example.com/api/1).

What have I done?

- I created a file "api.conf" within the mapped "conf.d" directory. Within this file I defined my upstreams matching my containers. Example (given, that api1.api is the container name of my api service):

```
upstream api1.api {
    server api1.api:80;
}
```

- I created a file "www.example.com_location" within the mapped "vhost.d" directory. Within this file I defined my location-specific configuration. Example:

```
location /api/1/ {
    proxy_pass http://api.api;
    proxy_redirect off;
    proxy_set_header Host $host;
}
```

I started my containers, logged in at the nginx-container and dumped the nginx config. Config was valid - api.conf and www.example.com_location were included.

But when I call www.example.com/api/1 in my browser, I receive a 404 and NO request is received by my api service.

What am I doing wrong?

---
[1] https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

**Comment by jwilder** [comment]
Unfortunately, I don't know what's going wrong in your setup.  I'd like to keep Github issues for actionable bug reports or feature requests.  Can you ask questions in the [Q&A Group](https://groups.google.com/forum/#!forum/nginx-proxy).

Thanks!
