### ISSUE TITLE
Add 'always' parameter to Strict-Transport-Security header

### ISSUE THREAD

**Issue by Archcry** [jwilder/nginx-proxy#1109]
When using basic authentication the server will not send the Strict-Transport-Security header when you haven't filled out the username and password field correctly.

`add_header name value [always]:`
> Adds the specified field to a response header provided that the response code equals 200, 201 (1.3.10), 204, 206, 301, 302, 303, 304, 307 (1.1.16, 1.0.13), or 308 (1.13.0). The value can contain variables.

I suggest adding the `always` parameter to also apply the header on other response codes (such as 403):
> If the always parameter is specified (1.7.5), the header field will be added regardless of the response code.

This will make sure the header is also applied to clients that haven't filled out the username or password yet. Since this is specified on a per-`VIRTUAL_HOST` basis it shouldn't hurt.

Alternatively we could only apply the `always` parameter to hosts that have basic authentication turned on.

I can make a pull-request for this, just let me know what you think.

**Comment by kamermans** [comment]
I see no reason why we shouldn't add the `always` parameter.  According to the [HSTS RFC](https://tools.ietf.org/html/rfc6797#section-7):
> When replying to an HTTP request that was conveyed over a secure transport, an HSTS Host SHOULD include in its response message an STS header field that MUST satisfy the grammar specified above in Section 6.1 ("Strict-Transport-Security HTTP Response Header Field"). If an STS header field is included, the HSTS Host MUST include only one such header field.

@jwilder: I don't see any exceptions in the RFC that would suggest that HSTS shouldn't be present for certain response codes (as is the case today), so I would support pulling this change in.

**Comment by Archcry** [comment]
Awesome, this pull request should be merged asap :D

**Comment by jwilder** [comment]
Fixed via #1073
