### ISSUE TITLE
Wrong HTTPS Redirects

### ISSUE THREAD

**Issue by CamoMacdonald** [jwilder/nginx-proxy#1126]
If you point *.domain.com at a server and deploy the proxy with HTTP and go to an invalid domain e.g. http://test.domain.com - you receive a 503 error. This is expected.

However if you make the domains for *.domain.com HTTPS and go to an invalid domain e.g. https://test.domain.com - you will be redirect to the first working page in the default.conf. 

You should receive a 503 for the invalid domain on both HTTP and HTTPS

**Comment by CamoMacdonald** [comment]
a blank/default port 443 section needs added:
```
server {
        server_name _;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/domain.com.crt;
        ssl_certificate_key /etc/nginx/certs/domain.com.key;
        add_header Strict-Transport-Security "max-age=31536000";
        return 503;
}

```

**Comment by matteocng** [comment]
A solution (workaround?) without touching `nginx.tmpl` is to [generate](https://github.com/jwilder/nginx-proxy/tree/master/test/certs) a (wildcard) `default.crt` and `default.key`, to be placed in the `certs` folder being mounted in the `nginx-proxy` container.

#105, #108

**Comment by CamoMacdonald** [comment]
@matteocng I have wildcard certs in the directory however the information is not being added to the default

**Comment by CamoMacdonald** [comment]
do they need to be called default.crt/key ? the other ones have needed to be called that
