### ISSUE TITLE
connection refused when docker daemon is secured

### ISSUE THREAD

**Issue by ArtworkAD** [jwilder/nginx-proxy#113]
I have secured my docker daemon like suggested by docker: https://docs.docker.com/articles/https/ The nginx-proxy stopped working and outputs:
```
dockergen.1 | 2015/03/04 13:48:01 error listing containers: dial unix /tmp/docker.sock: connection refused
dockergen.1 | 2015/03/04 13:48:01 Unable to ping docker daemaon: dial unix /tmp/docker.sock: connection refused
````

How can I run nginx-proxy with a secured daemon?

**Comment by md5** [comment]
You'll need to start your Docker daemon with both a TLS socket and a Unix socket.

How are you starting your Docker daemon?

**Comment by ArtworkAD** [comment]
I run docker via systemd. In /etc/default/docker I have configured docker like this:
```
DOCKER_OPTS='--tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=0.0.0.0:2376'
```

After that nginx proxy stopped working. @md5 any ideas?

**Comment by jwilder** [comment]
When you switched to TLS, you removed the unix domain socket that nginx-proxy uses to connect to docker.  nginx-proxy does not currently support TLS although you should be able to get it to work by mounting in your docker key/cert and starting docker-gen w/ the -tls* flags.  If you don't do that, you'll have to add back the `-H unix:///var/run/docker.sock` to your `DOCKER_OPTS`

**Comment by md5** [comment]
:100:

**Comment by ArtworkAD** [comment]
@jwilder any plans on supporting tls? So I need to create separate containers, one for nginx and one for docker gen?

**Comment by jwilder** [comment]
@ArtworkAD No immediate plan but I added #114.

**Comment by md5** [comment]
@ArtworkAD What's wrong with doing as @jwilder suggested an having Docker listen on both TLS and a Unix socket?

**Comment by md5** [comment]
FWIW, that's how Docker Machine configures the Docker daemons it provisions.

**Comment by ArtworkAD** [comment]
How can I configure this?

**Comment by md5** [comment]
DOCKER_OPTS='--tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock'

**Comment by ArtworkAD** [comment]
@md5 this works, thank you.

**Comment by vallard** [comment]
Any hints on where to configure this in CoreOS?

**Comment by md5** [comment]
@vallard take a look here: https://coreos.com/docs/launching-containers/building/customizing-docker/

**Comment by vallard** [comment]
@md5, thanks!  Funny, I was over there as well trying that out.  I still didn't have success but what I did do was this:
```bash
sudo cp /usr/lib/systemd/system/docker.service /etc/systemd/system/
sudo vim /etc/systemd/system/docker.service
```
Changed the relevant line to be:
```bash
ExecStart=/usr/lib/coreos/dockerd --daemon --host=fd:// -H=tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
```
Then:
```bash
systemctl enable docker.service
sudo systemctl daemon-reload
sudo systemctl restart docker
```
I still got the same error, but maybe this will help someone get on the right track or have them correct me via [Cunningham's Law](http://meta.wikimedia.org/wiki/Cunningham's_Law)
