### ISSUE TITLE
lets encrypt companion overrides custom config

### ISSUE THREAD

**Issue by Fohlen** [jwilder/nginx-proxy#1141]
And that is pretty annoying, since I need it.
Is there any workaround for this?

**Comment by ingwinlu** [comment]
Why would you open an issue here if you have a problem with a different repository?

Anyway no workaround needed because the companion app does respect the configuration as can be [here](seen https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/functions.sh#L26)

**Comment by Fohlen** [comment]
Hello there @ingwinlu 
You are right, this issue should have rather be opened in the `companion` repository.
I figured out (and for anyone stumbling across this) that it does indeed respect the config if given circumstances are met:

- [x] You need to mount the `vhost.d` directory into both, proxy and let's encrypt 
- [ ] You need to put your custom config within that `vhost.d` directory

I previously _"double-mounted" my config like this:

```
volumes:
    - ./vhost.d/bla.domain:/etc/nginx/vhost.d/bla.domain:ro
    - ./vhost.d:/etc/nginx/vhost.d/
```

This way the `companion` will not be able to recognise your config (since it is not in the same path spec).
I assume this can be closed as wrong usage on my side.
