### ISSUE TITLE
Prevent Generating Broken Config

### ISSUE THREAD

**Issue by jwilder** [jwilder/nginx-proxy#115]
https://github.com/jwilder/nginx-proxy/issues/107 resulted in a invalid nginx.conf because a container exposed two ports but neither of them were port 80 and a `VIRTUAL_PORT` env var was not specified.  The generated nginx.conf had a backend section w/ no endpoints listed causing nginx to fail to reload.

The issue is that https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L62 should have an else clause that generates `server {{ $address.IP }} down;` per https://github.com/jwilder/nginx-proxy/issues/107#issuecomment-75837337 to make it more explicit that there is a problem.

If https://github.com/jwilder/docker-gen/issues/67 is implemented, it should also be used.

**Comment by md5** [comment]
I think this one needs to be reopened until a fix is actually added. Looks like GH closed it since I wrote "should make it possible to fix jwilder/nginx-proxy#115".
