### ISSUE TITLE
container is getting killed

### ISSUE THREAD

**Issue by dvalenzuela-com** [jwilder/nginx-proxy#1152]
I am trying to add a container with JIRA by using

`docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira-software:latest -e VIRTUAL_HOST=jira.mydomain.com`

however, when I do `docker ps` I notice the docker instance is not created. When I look at the nginx-proxy logs, I notice the container was created and then killed (logs show the die event), which is why it is not accesible.

If I run the jira docker command without the ENV vars, i.e. `docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira-software:latest` then the container gets created, however the nginx-proxy does not generate the reverse proxy configs. 

What can I do to fix this? Is there a way to "manually" trigger the nginx-proxy to create the correct configuration for a given container?

**Comment by gerrytsui** [comment]
nginx-proxy default to port 80. to use port 8080 you must specify the -e VIRTUAL_HOST=jira.mydomain.com, which you did. However according to Docker run command reference all the [options] must be immediately after the run. ie it should be as follow:
`docker run --detach --publish 8080:8080 -e VIRTUAL_HOST=jira.mydomain.com cptactionhank/atlassian-jira-software:latest `

I would also add -e VIRTUAL_PORT=8080, just to be sure.

I believe your first command ( with the -e at the end) results in the container executing "-e VIRTUAL_HOST=jira.mydomain.com" and failed; thus container exits.

**Comment by dvalenzuela-com** [comment]
Worked like a charm, thanks a lot @gerrytsui <3 :)
