### ISSUE TITLE
auth_basic auth_basic_user_file entries not created in /etc/nginx/sites-enabled/default when adding a htpasswd file 

### ISSUE THREAD

**Issue by ict4ngo** [jwilder/nginx-proxy#116]
on a particular docker platform using the very latest jwilder/nginx-proxy when I add a htpasswd it's not created

I can see them in /etc/nginx/htpasswd

If I add them directly in location / for each vhost in /etc/nginx/sites-enabled/default the authentication works

what's worst if I restart the container the entries are destroyed

**Comment by jwilder** [comment]
Can you post how you are starting the container?  It should be something like:

```
$ docker run -d -p 80:80 -p 443:443 -v /path/to/htpasswd:/etc/nginx/htpasswd -v /path/to/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
```

where `/path/to/htpasswd` should be a directory w/ password files named after your respective `VIRTUAL_HOST` values.  e.g. /path/to/htpasswd/mydomain.com

**Comment by md5** [comment]
This sounds like a really old version if anything involving `sites-enabled` is working.

**Comment by ict4ngo** [comment]
geez 
that's true

thanks
