### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "no such file or directory" on Docker build

### ISSUE THREAD

**Issue by achrjulien** [jwilder/nginx-proxy#1173]
Hello,
I tried to build the docker with
` docker build . -f .\Dockerfile.alpine --tag test-nginx-proxy `
but when I run it
`docker run -it test-nginx-proxy`
I get the following error:
`standard_init_linux.go:190: exec user process caused "no such file or directory"`

Tested build environment: Boot2Docker / Win10

The same arises with
` docker build .  --tag test-nginx-proxy `

**Comment by achrjulien** [comment]
I solved it before submitting but this might be useful to someone.
Basically my system looks like that 
`docker-machine ls`
```
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER          ERRORS
1803      -        generic      Running   tcp://192.168.x.x:2376            v18.03.1-ee-3
myvm1     *        virtualbox   Running   tcp://192.168.x.x:2376           v18.06.1-ce
```

1803 is a Windows VM (run through virtualbox) but nginx runs on myvm1. The problem was that the build context was sent from a Windows computer to the linux VM and as of course, Windows wanted to change line endings of the entrypoint script. This made it silently fail during the building and magic happened next.

**Comment by iamzhengkai** [comment]
I have the same problem, how did you solve it? My docker in running in a Windows VM (run through virtualbox)  too! My Dockerfile is edited by vim in the VM, the VM is centos7.

**Comment by achrjulien** [comment]
@iamzhengkai change the line endings of the entrypoint script from Windows to UNIX style.

**Comment by achrjulien** [comment]
@iamzhengkai I edited my previous comment (in case you only check via emails)
