### ISSUE TITLE
nginx exits with error `1#1: unexpected ":" in /etc/nginx/conf.d/default.conf:76`

### ISSUE THREAD

**Issue by wadkar** [jwilder/nginx-proxy#1183]
Hi,

This is certainly not a question as I already have answer/workaround. Perhaps the same could be added to FAQ/README.md? Let me know and I will be happy to submit a PR.

Issue:
Passing `VIRTUAL_PROTO='HTTPS'` in docker-compose.yml will generate incorrect `/etc/nginx/conf.d/default.conf` and the `nginx` named container will exit with following error:
```
1#1: unexpected ":" in /etc/nginx/conf.d/default.conf:76
```

Please excuse me if this sounds silly for you `YAML` ninjas, but I have been passing `environments:` in the `docker-compose.yml` file with value of the  environment variable in quotes, e.g.

```
environments:
  - VIRTUAL_PROTO='https'
  - VIRTUAL_PORT='5000'
  - VIRTUAL_HOST='foo.example.com'
```

While this works nicely from command line `docker run -e VIRTUAL_PROTO='https' …`, the same fails to generate parsable `default.conf` for nginx when called with docker-compose.

The solution/workaround is to not use quotes around the values for the environment variable.

Thanks,
-Sudarshan

**Comment by kylegoetz** [comment]
I ran into this issue with dockerized gmvault. You have to pass an additional param `-c no` for a certain usage of the container and it fails if you put `c -no` in quotation marks in the yaml file.

**Comment by wadkar** [comment]
I am closing this issue by creating [a section](https://github.com/jwilder/nginx-proxy/wiki/Troubleshooting#configuration-file-errors-for-nginx) in the [troubleshooting page]((https://github.com/jwilder/nginx-proxy/wiki/Troubleshooting) on the wiki.
