### ISSUE TITLE
serving static files nginx <-> django

### ISSUE THREAD

**Issue by prarabdh9909** [jwilder/nginx-proxy#1231]
I have a web app (django served by uwsgi) and I am using nginx for proxying requests to specific containers. 
Here is a relevant snippet from my default.conf.
upstream web.ubuntu.com {
				## Can be connect with "palladium" network
			# palladium-dev-boxpalladium_web_1
			server 172.18.0.9:8080;
}
server {
	server_name web.ubuntu.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		include uwsgi_params;
		uwsgi_pass uwsgi://web.ubuntu.com;
	}
}

Now I want the static files to be served from nginx rather than uwsgi workers. 

So basically I want to add something like:
	location /static/ {
        autoindex on;
        alias /staticfiles/;
    }

to the automatically generated server block for the container

I believe this should make nginx serve all requests to web.ubuntu.com/static/* from /staticfiles folder. 

But since the configuration(default.conf) is generated automatically, I don't know how to add the above location to the server block dynamically :(

I did go through https://github.com/jwilder/nginx-proxy and I only see an example to actually change location settings per-host and default. But nothing about adding a new location altogether. 

I already posted this in Q&A and didn't get a response. 

Please help me if there is a way to achieve this.

**Comment by onemindservices** [comment]
Please search for old issues before posting new ones. The solution is mentioned here: https://github.com/jwilder/nginx-proxy/issues/553#issuecomment-339457619

**Comment by prarabdh9909** [comment]
@onemindservices it didn't show up on my search because it doesn't mention django. Closing this. Thanks for the help.
