### ISSUE TITLE
Alternating 404's on requests to one container

### ISSUE THREAD

**Issue by dman776** [jwilder/nginx-proxy#1240]
I am experiencing this same issue.    I have a python http service behind the proxy AND a few APACHE2 web servers.   When making requests to apache, everything works as expected.   However, on the Python server container, every other request returns a 404.

The logs from nginx-proxy container show the 200/404, 200/404 pattern.  
The logs from the python container, only show the successful 200 request-responses.

uname -a:
Linux otis 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

docker -v:
Docker version 18.09.2, build 6247962

[docker-compose.yml.txt](https://github.com/jwilder/nginx-proxy/files/2916843/docker-compose.yml.txt)

_Originally posted by @dman776 in https://github.com/jwilder/nginx-proxy/issues/1081#issuecomment-468434001_

**Comment by Lewiscowles1986** [comment]
I think this would benefit from closing and addressing via #1081 otherwise it could be unclear from others trying to help what is known and what should have been tried,

**Comment by dman776** [comment]
ok.   can you re-open #1081?  added comments there.
