### ISSUE TITLE
Wilcard subdomain

### ISSUE THREAD

**Issue by LM1LC3N7** [jwilder/nginx-proxy#1244]
Hello,

I have deployed the new cozy-stack app, that uses subdomain to point on different parts of the app.
I tried to use `VIRTUAL_HOST` with a wilcard, but it does not work.

Is it possible to route every sub-subdomains to a container, using a wilcard?
Example: 
```bash
--env VIRTUAL_HOST=*.cozy.domain.com,cozy.domain.com
```
So: 
* `cozy.domain.com` -> Redirected to the Cozy container
* `home.cozy.domain.com` -> Same container
* `user1.cozy.domain.com` > idem

**Comment by LM1LC3N7** [comment]
I used this line and it seems to work:

```bash
--env VIRTUAL_HOST=.cozy.domain.com,cozy.domain.com
```

**Comment by jayhar** [comment]
You can also do the following:
-e VIRTUAL_HOST=.domain.com -e LETSENCRYPT_HOST=cozy.domain.com,home.domain.com,user1.cozy.domain.com

NGINX will see the "." in front of the VIRTUAL_HOST as a wildcard. The LETSENSCRYPT will then generate a wildcard for each domain listed. As a FYI this is not a clean way if you are just attempting to do an overall wildcard for any subdomain.
