### ISSUE TITLE
vhost.d changes not reloading

### ISSUE THREAD

**Issue by johnjelinek** [jwilder/nginx-proxy#125]
After my site was up, I modified my `vhost.d/johnjelinek.com` file and it didn't recognize my conf changes:
```
dockergen.1 | 2015/03/15 21:45:30 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2015/03/15 21:45:30 Watching docker events
```

**Comment by johnjelinek** [comment]
Hmm ... maybe something else is the problem. I recreated the nginx container and my changes aren't being recognized still.

```
$ cat johnjelinek.com
return 301 $scheme://www.johnjelinek.com$request_uri;
client_max_body_size       10m;
```

When I upload a file, I get this:
```
nginx.1    | 2015/03/15 21:49:53 [error] 24#0: *1 client intended to send too large body: 1244403 bytes, client: 23.126.98.223, server: www.johnjelinek.com, request: "POST /ghost/api/v0.1/uploads/ HTTP/1.1", host: "www.johnjelinek.com", referrer: "https://www.johnjelinek.com/ghost/editor/11/"
```

**Comment by md5** [comment]
You seem to have two different problems:

1. `docker-gen` isn't smart enough to send a `SIGHUP` to `nginx` in that situation. It will only send a `SIGHUP` in the case of an event from the Docker daemon that causes the contents of `/etc/nginx/conf.d/default.conf` to change and it isn't smart enough to know that the generated output has includes at the Nginx level.
2. You can't `return` like that. Everything after the `return` inside the enclosing `server` block will be ignored, including your `client_max_body_size`.

**Comment by johnjelinek** [comment]
Ok, I'll reorder it so return is last and do a docker restart nginx-proxy to see if that fixes it.

**Comment by johnjelinek** [comment]
```
$ cat johnjelinek.com
client_max_body_size       10m;
return 301 $scheme://www.johnjelinek.com$request_uri;
```

I did a docker restart and still same problem.

**Comment by md5** [comment]
It's not really clear to me what you're trying to do or what's wrong with your setup.

The following information could be helpful:

1. Which hostnames you expect to respond for your site and how you expect them to respond (i.e. serve a page or redirect).
2. The exact command you're using to run `jwilder/nginx-proxy`
3. The directories listings and (if possible) file contents of any volumes mounted in your `docker run` command for `jwilder/nginx-proxy`
4. The exact commands you're using to start any containers you expect to be proxied

**Comment by johnjelinek** [comment]
1. johnjelinek.com should redirect to www.johnjelinek.com and accept uploads up to 10MB
2. `docker run -d -p 80:80 -p 443:443 --name nginx -v /home/user/vhost.d:/etc/nginx/vhost.d:ro -v /home/user/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock --restart=always jwilder/nginx-proxy`

3.
```
$ tree vhost.d/ certs/
vhost.d/
├── beaneighbor.org
└── johnjelinek.com
certs/
├── beaneighbor.org.crt
├── beaneighbor.org.key
├── johnjelinek.com.crt
└── johnjelinek.com.key
```

4.
```
docker run -d --name johnjelinek.com -e VIRTUAL_HOST=johnjelinek.com,www.johnjelinek.com -e VIRTUAL_PORT=2368 -v /home/user/johnjelinek.com:/ghost-override --restart=always dockerfile/ghost

docker run -d --name beaneighbor.org -e VIRTUAL_HOST=beaneighbor.org,www.beaneighbor.org -e VIRTUAL_PORT=2368 -v /home/user/beaneighbor.org:/ghost-override --restart=always dockerfile/ghost
```

and for completeness:
```
$ cat vhost.d/beaneighbor.org
return 301 $scheme://www.beaneighbor.org$request_uri;

$ cat vhost.d/johnjelinek.com
client_max_body_size       10m;
return 301 $scheme://www.johnjelinek.com$request_uri;
```

**Comment by johnjelinek** [comment]
oooooh -- I think maybe I prolly need to create a new `www.johnjelinek.com` vhost.d conf with the `client_max_body_size` setting.

**Comment by johnjelinek** [comment]
That was it. Sorry :/

**Comment by md5** [comment]
Glad you figured it out :+1:
