### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by bitraten** [jwilder/nginx-proxy#127]
Hi.
Would it be possible to add an option, which adds a listen directive for IPv6?

**Comment by md5** [comment]
It might be nice to get this added in the upstream `nginx` image instead. I just found this IPv6-related issue in their repo: https://github.com/nginxinc/docker-nginx/issues/18

**Comment by bitraten** [comment]
Well, AFAIK IPv6 is already supported by nginx.
What's missing are listen directives in the configuration/template:
```
        listen 443 ssl;
+       listen [::]:443 ssl;
```

**Comment by oleynikd** [comment]
+1
So now all IPv6 traffic can't go through?

**Comment by jackfischer** [comment]
Hate to bump this, but this would be a very helpful option to have

**Comment by Sharsie** [comment]
+1
Yes, had to temporarily disable AAAA records :(
