### ISSUE TITLE
No way to erase logs between restarts

### ISSUE THREAD

**Issue by thomasd3** [jwilder/nginx-proxy#1288]
Right now, if you restart the container and pull the log with the tool 'dry', you can see the whole log history since the container was created (not run / restarted), so the history can be massively long.

It would be good to have a way to clear the log when restarting the container.

**Comment by gerrytsui** [comment]
Your question is pertaining to Docker, nothing to do with this git repo.

Found these on StackOverflow:

To delete the logs on a Docker for Linux install, you can run the following for a single container:
> echo "" > $(docker inspect --format='{{.LogPath}}' <container_name_or_id>)

You can configure docker to automatically rotate logs with the following in an /etc/docker/daemon.json file:
> {
>   "log-driver": "json-file",
>   "log-opts": {"max-size": "10m", "max-file": "3"}
> }
>

**Comment by thomasd3** [comment]
@gerry, I thought that the container had to set up the log rotation, not realizing that it's better to let docker do it. thanks for the info, I'll close this thread.
