### ISSUE TITLE
Nginx-Proxy for TCP 

### ISSUE THREAD

**Issue by wilhelmmi** [jwilder/nginx-proxy#1290]
Hey all, 
sorry for asking here, but i could not open the Q&A Group ( Group: https://groups.google.com/forum/#!forum/nginx-proxy)

So, the question is: Is it possible to change the nginx.conf file in a way that I can use it for TCP? Or is there a better way to do reverse proxying for TCP? Im a beginner with docker and actually am struggling with this issue... 

Thanks in advance !
Mike

**Comment by DaniSchenk** [comment]
@wilhelmmi I started using [traefik](https://traefik.io/). Maybe it's worth a look...

**Comment by jwilder** [comment]
This project probably won’t work well as a TCP proxy out of the box.  It relies on Host headers which are part of HTTP protocol.
