### ISSUE TITLE
Error `/app/docker-entrypoint.sh: line 34: exec: --: invalid option`

### ISSUE THREAD

**Issue by alexanderadam** [jwilder/nginx-proxy#1303]
Images `ebf6755d2523` and `b1eff4ae4617` (current `latest` images) seem to be buggy and won't start.
This is what `docker logs` shows:

```
$ docker logs nginxproxy
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
/app/docker-entrypoint.sh: line 34: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

I'm not seeing any new release so I guess it is me?
The command is not overriden in way.
Maybe it's related to some of my options?

**Comment by alexanderadam** [comment]
My fault: I added `--restart unless-stopped` in **the end** :see_no_evil:

**Comment by gusarov** [comment]
lol, I did the same, thanks for this post, saved my time
