### ISSUE TITLE
default.conf should not generate location for one specific subdomain

### ISSUE THREAD

**Issue by Gutz-Pilz** [jwilder/nginx-proxy#1329]
Hi there,

i really love the nginx-proxy and i use it a lot!

now i want to use a new service that need some special treatment.
And i dont know how to get that accomplished with the jwilder container.
in my conf.d/default.conf 
location / gets generated by the container.

```       location / {
                proxy_pass http://sub.domain.com;
                include /etc/nginx/vhost.d/sub.domain.com_location;
        }
```

proxy_pass is special and needs to be overwritten by its content in vhost.d/sub.domain.com_location:

```       
        proxy_pass http://172.19.0.4:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
```

so basically my problem is, taht the proxy container generates `location/` with ` proxy_pass http://sub.domain.com;`

but i need `location/` with `proxy_pass http://172.19.0.4:80;`

how can i accomplish... that the container wont generate the proxypass in default.conf ?

**Comment by Gutz-Pilz** [comment]
solved it!

**Comment by kimlonglecis** [comment]
> solved it!

Do you mind telling me how you solve it?  I am trying to install Varnish listening on port 80 and need nginx-proxy to reverse proxy to Varnish Local IP port 80.  LIke the problem you had before, the location default to `proxy_pass http://example.com`.
