### ISSUE TITLE
"failed (113: No route to host) while connecting to upstream" when trying to reverse proxy Sonarr

### ISSUE THREAD

**Issue by DigitalJosee** [jwilder/nginx-proxy#1348]
`nginx.1    | 2019/10/30 20:43:01 [error] 707#707: *1077 connect() failed (113: No route to host) while connecting to upstream, client: MY.IP, server: sonarr.domain.tld, request: "GET /vendors~index.js?h=faRhAy83bMn0pnvHe55DnQ HTTP/2.0", upstream: "http://172.18.0.14:8989/vendors~index.js?h=faRhAy83bMn0pnvHe55DnQ", host: "sonarr.domain.tld", referrer: "https://sonarr.domain.tld/"`

This morning, out of the blue, my sonarr instance started to act weirdly, with 502 errors every now and then, after a while it just stopped working. After checking nginx proxy, I've rebuild the Sonarr container multiple times and after checking that accessing IP:8989 was working fine, I went and checked nginx-proxy, and apparently that's what's broken.

Anything I should try? I've seem other similar issues and nothing worked, I already have a VIRTUAL_PORT and VIRTUAL_HOST on my container env's.

All other containers are fine, radarr, plex, nginx website, everything is working.

Hope I've provided enough information!

Thanks!

**Comment by DigitalJosee** [comment]
My nginx config (obtained with: `docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf`):

`# sonarr.domain.tld
upstream sonarr.domain.tld {
                        ## Can be connected with "cloudbox" network
                        # sonarr
                        server 172.18.0.14:8989;
}
server {
        server_name sonarr.domain.tld;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name sonarr.domain.tld;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/sonarr.domain.tld.crt;
        ssl_certificate_key /etc/nginx/certs/sonarr.domain.tld.key;
        ssl_dhparam /etc/nginx/certs/sonarr.domain.tld.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/sonarr.domain.tld.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://sonarr.domain.tld;
        }
}`

**Comment by DigitalJosee** [comment]
Fixed it, apparently it was something with docker itself.

Fixed by updating my Docker version to `Docker version 19.03.4, build 9013bf583a`

**Comment by prbakhsh** [comment]
I had same issue in my bare metal k8s on ingress controller and docker version 20.10.6. After restart my nodes the issue went to the hell. It took me a day :-$

**Comment by chichi13** [comment]
That's odd, I had the same problem with Docker version 20.10.12 and resolved it as @prbakhsh. Just restarted the node and everything is working well now.
