### ISSUE TITLE
Proxy don't work on mac

### ISSUE THREAD

**Issue by osbre** [jwilder/nginx-proxy#1363]
Hello, **i'm using** : 
- MacOS 10.14.5
- DockerDesktop 2.1.0.5 (406930)
- Docker version 19.03.5

**Steps to reproduce:**
```bash
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
docker run -d -p 80 -e VIRTUAL_HOST=webide.local  tutum/hello-world
```

Also, my `/etc/hosts` file content:

```
webide.local	localhost
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Problem:**

When i open http://webide.local/ - i see "server not found", but expect normal 200 response.

Any ideas how to make it work? 

Thanks...

**Comment by osbre** [comment]
Just tried it on ubuntu - all works, it's mac-specific problem.

**Comment by osbre** [comment]
`.local` in domain [seems to be a reserved word](https://apple.stackexchange.com/a/202889), now i changed to `webide.storm`, but there is still a problem

**Comment by LucaVerdecchia** [comment]
In the host file you've reversed the order for IP -- local domain

Your current host:
webide.local	localhost

Fixed host:
localhost webide.local

**Comment by osbre** [comment]
@LucaVerdecchia, Thanks!

Solution:
```
127.0.0.1 webide.local
```
(**127.0.0.1**, not **localhost**)
