### ISSUE TITLE
About /etc/hosts

### ISSUE THREAD

**Issue by kytwb** [jwilder/nginx-proxy#143]
Could we imagine something that would edit the host `/etc/hosts` file? Limited use cases in production, but for development environment based on Docker and using this container as the nginx proxy, that could be cool. Feedbacks?

**Comment by tbal** [comment]
@kytwb did u find a solution or elegant workaround for that? Would be interesting..

**Comment by kytwb** [comment]
I'm mounting my /etc/host in my app container and use [hostile](https://www.npmjs.com/package/hostile) in my nodejs app.
