### ISSUE TITLE
Idea for default page served by nginx-proxy?

### ISSUE THREAD

**Issue by andrewcstewart** [jwilder/nginx-proxy#146]
So if you just go to yourhost:80 obviously you get a 503.  Once you've added some other containers with virtual hosts, those will then be served as vhostname.yourhost, etc...  

I don't know if this is necessarily a suggestion for nginx-proxy's default or possibly a separate 'batteries included' docker image to go with it, but it could be useful for the default yourhost:80 to serve a list of all current vhosts.. maybe as just a list/json, or maybe as hyperlinks.  

Anyway, one for the suggestion box.

**Comment by thaJeztah** [comment]
A default page could be created using; https://github.com/jwilder/nginx-proxy/pull/72

However, a list of all defined host has been discussed in the past, but is a bad idea from a security perspective (ie running in production), for example, you don't want to publicly show "preview.yourclient.com", etc.

**Comment by kentmw** [comment]
I appreciate the call-out that the default "working" nginx-proxy page is a 503. I just spent an hour trying to get the default welcome to nginx page showing after starting this image. Maybe we can add this to the documentation?

**Comment by vfulco** [comment]
+1 on kentmw's rec

**Comment by jwilder** [comment]
I have added "503" question to the Q&A group here: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
