### ISSUE TITLE
Does this work with lan hosts?

### ISSUE THREAD

**Issue by andrewcstewart** [jwilder/nginx-proxy#147]
I know next to nothing about nginx and network routing, so this may just be a matter of my own ignorance, but is nginx-proxy not intended to work on a host on a LAN?  I've been trying to get a vanilla deployment of this going exactly by the book using the examples (and the original blog post).  I have a local server that I can reach at hostname.local but after running through the example setup (and a dozen variations) I cannot get any subdomain.hostname.local to route.  I can reach the web service on the intended subdomain's container just fine, but not through that route.  Looking through the issues here and on docker hub it looks like this might not be possible at all or maybe Im missing something in my local DNS setup (which would be way over my head).  

Anyway, my questions are:

1) Is this not even possible in the first place?

2) If it is, any suggestions on how I can troubleshoot this?

**Comment by thaJeztah** [comment]
you can try if it the nginx-proxy works by temporarily adding the subdomain to the `/etc/hosts` file on your workstation, i.e.

    # IP address of your docker host (where NGINX proxy is running on)
    123.456.789.012    subdomain.hostname.local

That way you don't use the DNS for the subdomain. If that works, your DNS isn't configured properly :)

**Comment by andrewcstewart** [comment]
Thanks @thaJeztah for the advice.  I tried exactly that and subdomain.hostname.local indeed resolves... but it resolves to a 503 which I'm assuming means that subdomain.hostname.local is just resolving to hostname.local and not the subdomain supposedly being served by nginx?

Do I need to run the subdomain's container with -P or -p x:x ?  The container's image is def build with EXPOSE set to the contained web service's port number.

**Comment by thaJeztah** [comment]
-p is not required, the NGINX proxy uses the docker private network to communicate with the container. However, if the webserver in the container is using a non-standard port, you may have to add a `VIRTUAL_PORT` environment variable as well for the container.

**Comment by thaJeztah** [comment]
Also, you can check the logs, `docker logs my-nginx-proxy-container` and check if the generated NGINX config looks okay.

You should be able to copy that file out of the container using 

    docker cp [nginx-proxy-container-name]:/etc/nginx/conf.d/default.conf /destination/path

Then check if the content of the config file looks okay

**Comment by andrewcstewart** [comment]
Aha!!  I got it to work.  Our DNS is def not setup properly to handle the subdomain requests.  Temporarily adding it to my /etc/hosts like you suggested allowed me to try a few things and it worked ( I was setting VIRTUAL_HOST="justsubdomain" instead of VIRTUAL_HOST="subdomain.hostname.local").

Ok, so I've got the source narrowed down.  Now.. any chance you can tell me what I need to ask my friendly neighborhood network engineer to configure on DNS?  (Thanks so much for the tip, this is such an awesome docker image)

**Comment by thaJeztah** [comment]
Basically you need a wildcard DNS server, so that `[whatever].[whatever].hostname.local` resolves to the IP address of your docker host.

If you're the only one that needs to use it, you could even run your own DNS server in a container, and have your workstation use that as it's primary DNS :)

**Comment by andrewcstewart** [comment]
Awesome, thanks again.

**Comment by thaJeztah** [comment]
Good luck! And have fun with Docker :)
