### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by gabeos** [jwilder/nginx-proxy#149]
As in this fork: https://github.com/saidimu/nginx-proxy

Seems like it shouldn't be too hard as long as there aren't security issues or issues with SSL interactions.

Relevant portion of above fork (in `location /` block):

```
		{{/* Only add the websockets Upgrade headers if a WEBSOCKETS env var is set. */}}
                {{ if $value.Env.WEBSOCKETS }}
	                proxy_set_header Upgrade $http_upgrade;
	                proxy_set_header Connection "upgrade";
                {{ else }}
	                proxy_set_header Connection "";
                {{ end }}
```

**Comment by gabeos** [comment]
... Never mind.. sorry, I just saw the `map $http_upgrade $proxy_connection...` portion of nginx.tmpl

**Comment by md5** [comment]
@gabeos :+1:

**Comment by lagerstrom** [comment]
Sorry for bumping this old thread, but how did he get it to work?

**Comment by mikejw** [comment]
Any ideas anyone?
