### ISSUE TITLE
Sticky session support

### ISSUE THREAD

**Issue by schmunk42** [jwilder/nginx-proxy#153]
I found out that the reverse proxy is acting in round-robin mode by default, when you have multiple containers with an identical VIRTUAL_HOST setting. http://nginx.com/resources/admin-guide/load-balancer/#sticky

Wouldn't it make sense to add an option to have a sticky session configuration to `nginx-proxy`?
Or maybe a section to the docs.

**Comment by md5** [comment]
The functionality you suggest sounds reasonable. I'm not sure what there is to document at the moment since I don't see a way to do this with the current `nginx.tmpl`.

How would you envision this being configured? Would a setting on the backend containers trigger this behavior? If so, what would you expect to happen if multiple backends had conflicting configuration settings?

**Comment by md5** [comment]
P.S. You may want to update the title of this issue to be something like "Sticky session support".

**Comment by schmunk42** [comment]
I am not very experienced with nginx configurations, but basically the same way like current settings are changed, although the syntax looks more complex. Bottom line - I don't have an implementation plan :)

You may close this or leave it open as a future enhancement.

**Comment by pilerou** [comment]
As sticky sessions are native in NGINX + but doesn't exist in NGINX community version, i think it should be  better to use another module https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng (not 1.9 compliant yet apparently)

**Comment by jwilder** [comment]
If this is not supported in the stock nginx image, then I won't be able to support it.  Don't want to get into managing custom modules in this image.

**Comment by schmunk42** [comment]
btw ... I just played around with this: https://github.com/schmunk42/nginx-proxy/commit/06172b99d64b8dc8a0e29f25ff259b53f5a84adf ... and it does the job for me, at least with my first tests.

I found this on [nginx.org](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash). 
Sorry, my knowledge about nginx & its module is pretty limited, but this is also available in your image, right?
