### ISSUE TITLE
can't link the domain name with 

### ISSUE THREAD

**Issue by helxsz** [jwilder/nginx-proxy#157]
I have deployed a digitalocean server with domain name/DNS pointed to the IP address of this server. If I ping the domain name, and I can see the pinged IP address is the same with the IP address of my digitalocean server.

now I deploy a ghost blog server on the digitalocean server that I tried 

if I run 
docker run -d -p 8806:2368 --name website3 ghost
the container runs well, and go to the IP address:8806, the browser can show the right website.

However, when typing in 
docker run -d -p 86:2368 --name website3 -e "VIRTUAL_HOST=girlupuk.com"  ghost
from docker logs 'container', the server is running well
I can see the ghost is running well. when going to girlupuk.com, the nginx server show '503 Service Temporarily Unavailable', why is that ?

**Comment by piront** [comment]
Is your container exposing more than two ports (in your dockerfile) ? if yes you have to add the virtual_port env variable : -e "VIRTUAL_PORT=2368"

https://github.com/jwilder/nginx-proxy#multiple-ports
