### ISSUE TITLE
crashdown with multiple virtual hosts

### ISSUE THREAD

**Issue by helxsz** [jwilder/nginx-proxy#159]
currently I am running two virtual server, here is my build-up.

docker run -d -p 86:2368 --name home -e "VIRTUAL_HOST=hostname.com"  ghost //ok
docker run -d -p 85:2368 --name home-blog -e "VIRTUAL_HOST=blog.hostname.com" ghost  // ok

They are all working well, but after a while (sometimes hours or a day), one of the vitual server will break down, and I have to restart the container to make it work.

I wonder why is it happening ?

**Comment by jwilder** [comment]
I'd suggest checking the logs of you nginx proxy container and you ghost containers for more info.
