### ISSUE TITLE
FastCGI proxy

### ISSUE THREAD

**Issue by nubs** [jwilder/nginx-proxy#16]
What are your thoughts on adding the ability to proxy to FastCGI servers in a similar automated fashion?

At first glance there would be a need to control per-application settings as different servers use FastCGI in a wide variety of ways.  I'm not sure if environment variables could work to control everything.

**Comment by kevinsimper** [comment]
@nubs Has this been solved? :smile:

**Comment by HalisCz** [comment]
according to #863 - yes

**Comment by jwilder** [comment]
Fixed via #863
