### ISSUE TITLE
create tags for releases

### ISSUE THREAD

**Issue by schmunk42** [jwilder/nginx-proxy#162]
Would be nice if you could create tags for versions of the reverse proxy.

Either as `0.1.0` `0.2.0` as long if you think there's no stable version.
Or as `1.7-0.1.0` `1.9-0.1.0` if you plan to support different nginx versions.

I noted the change of the base-image from 1.7 to 1.9 recently - it didn't break anything, but it's always good to be able to stay on a specific version.

**Comment by md5** [comment]
Since Nginx, Inc. is no longer publishing an `nginx:1.7` image, I don't think it makes sense to support more than one version of Nginx here. cf. https://github.com/docker-library/official-images/blob/master/library/nginx

**Comment by schmunk42** [comment]
But having tags would be still a nice thing, because it lowers chances of breaking things and also speeds up your development process.

**Comment by ricardoseriani** [comment]
Hello @jwilder 

Any news on this ?

I think it would be really nice to have a tags system. It will help using nginx-proxy with a specific version in docker-compose.yml

Thanks in Advance.

**Comment by jwilder** [comment]
I created a `0.1.0` on the project but docker hub seems to be really broken right now so I can't setup the build.

**Comment by ricardoseriani** [comment]
Thanks @jwilder, it's gonna be very useful when the tag can be pushed to docker hub

**Comment by jwilder** [comment]
The `0.1.0` tag was finally built on docker hub.

**Comment by joegoggins** [comment]
Hey @jwilder , I'm curious what tag you'd recommend pinning to for a production configuration. Usually, I'd assume the highest non "latest" tag would be the one, [in this case `0.3.6`](https://hub.docker.com/r/jwilder/nginx-proxy/tags/) , however, it's 3x bigger than the others and so I'm not sure if this a good idea. It would be awesome if there were a way to link GitHub releases to Docker image tags so folks know what to pin to. It would also be nice if DockerHub showed when the tag was created and based on a what Git commit. I wouldn't have to ask if either of these things existed.

Thanks for building an awesome and incredibly useful docker image!

**Comment by jwilder** [comment]
@joegoggins `0.3.6` is a really old tag.  I think that was from when I first push up this image to docker hub and used the `docker-gen` version as the tag.  I would use `0.1.0` or `0.2.0` which is the latest one that I just pushed up.  Those docker hub tags are build from this repo's github tags so it should be easier to determine what is in the image.

**Comment by thomasleveil** [comment]
@jwilder it seems [quay.io](https://quay.io/) is more convenient to manage tags: https://github.com/sameersbn/docker-gitlab/issues/39#issuecomment-147203458

**Comment by schmunk42** [comment]
@jwilder Docker Hub updated their automated-build repos since a while, so it creates image tags from GitHub tags. Would be nice, if you could enable this feature and tag more often.

I know that it can sometimes be annoying, because Docker Hub tends to be error prone, when it comes to building images.
But on the other hand, I'd really like to stay on a fixed revision, if possible.

**Comment by jareware** [comment]
I realize this issue is pretty old, but seems most topical; @jwilder any chance for more frequent releases/tags? Depending on `jwilder/nginx-proxy:latest` risks inadvertent changes on redeploys.
