### ISSUE TITLE
Use supervisor instead of forego?

### ISSUE THREAD

**Issue by joakim666** [jwilder/nginx-proxy#165]
I want to pass the logs unchanged from nginx, which I've configured to log in JSON, to logstash but forego adds hardcoded formatting of the process name before a bolded pipe character before the output and that breaks things.

Hence I forked the repo in [joakim666/nginx-proxy](https://github.com/joakim666/nginx-proxy) and replaced forego with [supervisor](http://supervisord.org) which allows for unchanged output of the processes stdout/stderr output to stdout/stderr of the docker container.

Is it worth doing a pull request of this? Would it be approved?

**Comment by etopian** [comment]
You should try opening an issue with Forego. Supervisord is not going to be as efficient as Forego. It's Python and not using asyncore.

**Comment by md5** [comment]
I found this PR for forego that removed ANSI escapes, but it was rejected: https://github.com/ddollar/forego/pull/19

**Comment by etopian** [comment]
can the output be piped to something else like this:
http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed

**Comment by joakim666** [comment]
Considering efficiency forego and supervisor just starts processes and monitors them. How efficient do they need to be really? But true that supervisor probably uses more memory given that it’s written in python.

If forego won’t change I guess the proper solution is to fork/rewrite forego but that’s something I’m not that interested in doing. Stripping the ANSI color codes and process name part with regular expressions through some pipe seems like a quite cumbersome way to do it, with the added risk of losing log data if the search-and-replace goes wrong.

**Comment by jwilder** [comment]
I have not tried this myself but you could also try running `nginx-proxy` and `docker-gen` in separate containers and use the `syslog` logging driver on the `nginx-proxy` container to log to your hosts syslog.  You can then configure your hosts syslog to forward to logstash or use a log forwarder on a log file it's configured to write to.

I originally had supervisor in the image but it added a lot of weight to the image so I dropped it to use forego instead.

**Comment by joakim666** [comment]
Using syslog breaks the simplicity of just running [logspout](https://github.com/gliderlabs/logspout) with a logstash adapter though.

Have you considered [runit](http://smarden.org/runit/) as used by the [phusion/baseimage-docker](https://github.com/phusion/baseimage-docker) image?

Anyway, it's not that much work for me to maintain a fork. I just figured there might be more people with similar logging setups.

**Comment by jwilder** [comment]
You can still use logspout with separate containers. The separate container setup just runs docker-gen and nginx in separate containers so forego is not used.

**Comment by joakim666** [comment]
I finally got around to changing to a two container setup with successful result so this issue can be closed.
