### ISSUE TITLE
HTTPS vulnerable for Logjam attacks

### ISSUE THREAD

**Issue by fuerst** [jwilder/nginx-proxy#169]
Looks like the current setup for HTTPS is vulnerable for Logjam attacks. I just used https://weakdh.org/sysadmin.html to verify one of my Docker containers proxied by nginx-proxy. 

Would be nice if you change the defaults to higher security levels. Description how to do this is available at the website mentioned above.

**Comment by kcyeu** [comment]
Fixed in #170, @jwilder please check the PR.

**Comment by fuerst** [comment]
Cool - thanks a lot!
