### ISSUE TITLE
[QUESTION] Use nginx-proxy with Shipyard

### ISSUE THREAD

**Issue by kahnvex** [jwilder/nginx-proxy#17]
Thanks for the reverse proxy, works great.

Wondering if anyone has tried using this with [shipyard](https://github.com/shipyard/shipyard). Shipyard is a little different because it uses a deploy image which boots up several other containers.

**Comment by javaknight** [comment]
If you follow the manual directions here, and include -e VIRTUAL_HOST for the Shipyard application container, and put your SSL in the directory where nginx-proxy expects it, login should work via ssl.
