### ISSUE TITLE
Mount docker.sock readonly?

### ISSUE THREAD

**Issue by rtrauntvein** [jwilder/nginx-proxy#173]
Is there any reason why we wouldn't want to mount the docker.sock as Read Only? 

`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

**Comment by jwilder** [comment]
Should be fine.

**Comment by rtrauntvein** [comment]
Cool, I ran some tests here and seems to be working just fine.

Would you accept a PR if I were to change this throughout the README.md ?

**Comment by jwilder** [comment]
Sure.
