### ISSUE TITLE
Not enable to get ssl/https working

### ISSUE THREAD

**Issue by atom2ueki** [jwilder/nginx-proxy#177]
### Problem:
I've follow the steps from this article : https://gist.github.com/bradmontgomery/6487319
to generate my necessary files for ssl cert, and use the command provided in wiki

`$ docker run -d -p 80:80 -p 443:443 -v /path/to/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

I realised it didn't work for my positive ssl, when I type mydomain.com, it won't show me an Nginx 503 Service Temporarily Unavailable (because I haven't deploy any site, but at least this will shown to prove nginx server is listen to port 443)

### Troubleshoot:
But after I console into nginx container, look at the configure file inside /etc/nginx/conf.d, it still show me listen port 80, not 443
`server {
	listen 80;
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	return 503;
}`

### Question:
May I know where I've missed out for configure and enabling ssl support for nginx-proxy ?

**Comment by jwilder** [comment]
Are you running any containers that were started w/ the `VIRTUAL_HOST` env var?

**Comment by atom2ueki** [comment]
@jwilder no, I only installed nginx-proxy docker

**Comment by jwilder** [comment]
You need to start other containers with that env var so the proxy can generate a config.

**Comment by atom2ueki** [comment]
@jwilder it works, my bad, I thought it will generate the config when the server start, thanks Jason
