### ISSUE TITLE
docker-gen no longer seeing Env.VIRTUAL_HOST

### ISSUE THREAD

**Issue by cybercode** [jwilder/nginx-proxy#179]
About a week ago i updated my docker images (including nginx-proxy) and now the default.conf is never regenerated. The steps i took:

1. start proxy:  `docker run -v /var/run/docker.sock:/tmp/docker.sock --rm --name proxy jwilder/nginx-proxy`
2. start e.g., ubuntu: `docker run -e VIRTUAL_HOST=foo.bar.com -it ubuntu bash -l`

Here's the proxy log:

```
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2015/06/10 22:07:45 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2015/06/10 22:07:45 Watching docker events
dockergen.1 | 2015/06/10 22:07:56 Received event start for container ff32ab0c252f
dockergen.1 | 2015/06/10 22:07:56 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

Here's the Env section from `docker inspect` on the ubuntu container:

```json
"Env": [
     "VIRTUAL_HOST=foo.bar.com"
],
```

as you can see from the log, it does not update the conf file, and in fact there is no upstream section in the conf file, so it seems that the  `{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}` is faiing.

This worked perfectly until recently. Any ideas? I've developed an entire site around the proxy and suddenly it no longer works. (I have deleted and re-download the proxy image just in case.)

BTW,  Docker version 1.6.2, build 7c8fca2.

tia,
rick

**Comment by jwilder** [comment]
Is your container exposing any ports?

**Comment by cybercode** [comment]
well that was a stupid regression (managed to remove the `EXPOSE` from my Dockerfile).  thanx.

**Comment by txomon** [comment]
Please, could this EXPOSE requirement be removed? I have been many hours trying to debug this till I found the issue. If a container already has the virtualenvs setup, why would this be needed?

**Comment by md5** [comment]
@txomon If you know up front what value to give to `VIRTUAL_PORT`, then it isn't random. You can easily expose an ad hoc port at `docker run` time using the `--expose` flag.

**Comment by txomon** [comment]
@md5 Totally forgot about that option. Anyway, can this requirement be mentioned at least in the README? Thanks!

**Comment by md5** [comment]
Sure: https://github.com/jwilder/nginx-proxy/pull/223
