### ISSUE TITLE
Redirect on proxied server returns location with http protocol instead of https

### ISSUE THREAD

**Issue by montgomery1944** [jwilder/nginx-proxy#187]
In our configuration we use nginx-proxy to add SSL to the non secure backend. In our application we have some places, where redirect is sent. Currently our server configuration builds location sent in redirect as an absolute URL, which is producing URL starting with HTTP. This is causing problems on some browsers, that handle such redirects improperly.

Currently we have to override the whole nginx.tmpl to put:
```
proxy_redirect http:// https://;
```
just under "proxy_pass" declaration in SSL config, which is rewriting locations returned in redirects starting with HTTP.

It would be very good if you could fix this issue internally in the nginx-proxy.

**Comment by jwilder** [comment]
Can you do a protocol relative redirect in your application? e.g. redirect to `//domain.com/...`

**Comment by montgomery1944** [comment]
Not really, currently I am using Tomcat as a container and its internal implementation of redirect builds the absolute URL when sending 302 code.

**Comment by jwilder** [comment]
`proxy_redirect http:// https://` might be a bit heavy handed to include in the default image.  If I understand it correctly, that would replace all `http://` with `https://` for any redirects from the backend which could prevent redirecting to valid `http://` locations on other domains.

If it's `proxy_redirect http://domain.com https://domain.com` that might be better but that would still prevent some possibly valid HTTPS to HTTP redirects.  Not sure.

Usually a proxy or load-balancer sets a `X-Forwarded-Proto` or a `Forwarded` [header](https://tools.ietf.org/html/rfc7239#section-5.4) that you're backend can use to determine the protocol to redirect to.  This might already be passed through via nginx though.

**Comment by md5** [comment]
@jwilder You mean like this? https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L1-L6 :wink: :+1:

**Comment by jwilder** [comment]
@md5 Aha! Yes, I forgot that was there.

**Comment by md5** [comment]
@jwilder Just noticed that link to RFC 7239 in your previous comment. It might actually be good for `nginx-proxy` to start setting a `Forwarded` header in addition to `X-Forwarded-Proto` and `X-Forwarded-For`.

**Comment by montgomery1944** [comment]
Our case is a bit more complicated, because on one environment we use nginx-proxy and on the other one we use different proxy, which has this redirect URL rewrite function enabled and we want to keep our application configuration simple and consistent. We were wondering whether this "proxy_redirect" option could become a configuration option in nginx-proxy if you don't want to enable it by default?

**Comment by jaimess** [comment]
@montgomery1944 could solve it?

**Comment by montgomery1944** [comment]
@jaimess, the issue should be resolved by using X-Forwarded-Proto in web server to build a proper Location header for redirect.

**Comment by jaimess** [comment]
Proto header did the trick for just proxy calls. Redirections needed 2 more properties in connector tag in tomcat server.xml file: proxyPort="443" scheme="https"
