### ISSUE TITLE
error listing containers: dial unix /tmp/docker.sock: connection refused

### ISSUE THREAD

**Issue by stuartleeks** [jwilder/nginx-proxy#196]
When running nginx-proxy on my docker host I get the following error in the container log:

```
error listing containers: dial unix /tmp/docker.sock: connection refused
```

I'm connecting remotely to docker host using certificate authentication - is it possible to configure nginx-proxy to use cert auth?

**Comment by stuartleeks** [comment]
I'm guessing that I could set the environment variables as per https://docs.docker.com/reference/commandline/cli/#environment-variables. However, the cert for my docker host doesn't match the host name.

This means that I have to use the --'tis cmd line switch rather than --tlsverify. Looking at the docs I can't see a way to match this in environment variables. Is there a way to trigger this for nginx-proxy/docker-gen?

**Comment by chaos95** [comment]
You can add a hosts entry (using docker run's --add-host param) to the nginx-proxy container that matches the name in the certificate to the IP of the host - would that solve the host name verification issue?

You can then set DOCKER_TLS_VERIFY, DOCKER_HOST and DOCKER_CERT_PATH environment variables on the container in order to configure TLS on the docker client inside nginx-proxy.

**Comment by stuartleeks** [comment]
I don't think so - the name in the cert is wildcarded.

**Comment by chaos95** [comment]
I think the same approach would work, though, wouldn't it? That is, pick a domain that matches the certificate's wildcard and add a host entry in the container which resolves it to the docker host's IP.

**Comment by adambiggs** [comment]
I just ran into this issue after updating to Docker v1.7.1

**Comment by adambiggs** [comment]
Is this related to #166?

**Comment by adambiggs** [comment]
No longer having this issue after rebooting.

**Comment by stuartleeks** [comment]
I got an error when I tried add host with docker run. For now I've just gone with static config. I definitely want to get this working, so will come back to it. I may recreate the docker host without a wildcard cert and then try it :-)

**Comment by tonivdv** [comment]
Had the same issue when upgrading to 1.7.1, and like with @adambiggs rebooting my docker machine solves the issue.

**Comment by stuartleeks** [comment]
I have now got my docker host configured so that --tlsverify works, and nginx-proxy worked first time! Thanks :-)

**Comment by adambiggs** [comment]
@stuartleeks do you mind sharing your final config that got all this working? Rebooting the VM isn't the end of the world, but one less thing for my team to worry about would be great.
