### ISSUE TITLE
Do inter-container requests go out over the internet?

### ISSUE THREAD

**Issue by Stellaverse** [jwilder/nginx-proxy#198]
Hi folks,

First, thanks a tonne for this Jason. Truly great work. And a snap to get up and running.

But I'm unsure of whether or not any requests from one container to another are being routed directly to the `nginx-proxy` container or are they going out over the internet and then back again?

I've run a `traceroute` from within one of my containers, and it looks like the hostname is being resolved to one of my `ELB` instances. But then then first hop is to `172.17.42.1`, which is the `docker0` bridge IP.

Here's what I'm seeing from within my `app.stellaverse.com` container (from which I would send a POST request to my `api.stellaverse.com` container):
```
root@be494527b4c1:/# traceroute api.stellaverse.com
traceroute to api.stellaverse.com (54.174.225.160), 64 hops max
  1   172.17.42.1  0.003ms  0.001ms  0.001ms
  2   216.182.229.6  1.220ms  1.391ms  0.965ms
  3   *  *  *
  4   *  *  *
  5   *  *  *
  6   * ^C
```

Where `54.174.225.160` is the ip of one of my `ELB` instances.

Don't have the networking chops to make sense of this. Can anyone else shed some light on this?

Thanks in advance.

**Comment by jwilder** [comment]
The docker bridge is just the network that containers are assigned IP address from on your host.  By default, `nginx-proxy` just forwards requests from the host IP to the private container IP through your hosts networking.  It shouldn't go out over the internet unless you've got some custom routing/network setup.

**Comment by Stellaverse** [comment]
Thanks for the info, but I'm not sure I'm really following. This isn't urgent by any means, but I'm curious as to how my app container knows to send any requests for any domains setup on the local network to the `nginx-proxy` container instead of out over the internet.

So if I've got `app.myapp.com` as one container, and then `api.myapp.com` as another container on the same host and `app.myapp.com` sends a request to `api.myapp.com`, that request is somehow automagically routed to the `nginx-proxy` container? If so, how does that happen?

Thanks in advance if anyone can help clarify this for me.

**Comment by md5** [comment]
@Stellaverse If `app.myapp.com` tries to connect to `api.myapp.com`, it will first do a DNS lookup for `api.myapp.com`. If that's resolving to your ELB, then that's the IP address to which `app.myapp.com` will connect. There is nothing that `nginx-proxy` can to do to change how your backend container's HTTP client library routes outbound connections.
