### ISSUE TITLE
fastcgi_pass instead of proxy_pass?

### ISSUE THREAD

**Issue by starikovs** [jwilder/nginx-proxy#199]
Hello,

I have a container with php-fpm and my app. Can I use nginx-proxy for it using fastcgi_pass instead of proxy_pass? It is a good idea? Or maybe it's better to use a webserver for each instance of my php-fpm app?

Thanks a lot!

**Comment by md5** [comment]
I briefly discussed this with myself in another ticket (cf https://github.com/jwilder/nginx-proxy/issues/99 :wink), but it's not currently possible. I think it's a good idea, but possibly tricky to get the details right across the different upstream protocols.

**Comment by starikovs** [comment]
@md5 OK, thanks for answer.

**Comment by sandrodz** [comment]
is this still not possible?

**Comment by starikovs** [comment]
@sandrodz, I haven't tested yet after I wrote the question. I use an nginx container in front of my php-fpm app. Nginx-proxy communicates with these front nginx containers.

**Comment by sandrodz** [comment]
in the end I went down the same road.

**Comment by Mirabis** [comment]
Stumbled on the same problem :(

Can't we have the container assume someone intended to mount as readonly? e.g have it auto gen -> stop -> modify it -> Mount as readonly ?

**Comment by vitorsdcs** [comment]
Hey @starikovs @sandrodz could you please explain how you linked both nginx-proxy and nginx? Thanks!

**Comment by starikovs** [comment]
@vitorsdcs first you start jwilder/nginx-proxy container and then you can start any number of nginx containers with -e VIRTUAL_HOST=foo.bar.com param. nginx-proxy detects those containers automatically. Read more here https://github.com/jwilder/nginx-proxy. Did I understand your question correctly?

**Comment by vitorsdcs** [comment]
@starikovs Yes. Thanks!
