### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by leonpegg** [jwilder/nginx-proxy#201]
Problem:
all registered addresses showing 502 Bad Gateway

Steps to Reproduce:
[Put test.internal.dev in DNS/hosts file]
docker run -d -ti --name proxy  -p 8080:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
docker run -d -ti --name test -e VIRTUAL_HOST=test.internal.dev -v /var/www/html:/usr/share/nginx/html:ro nginx

Result:
visiting test.internal.dev:8080 shows 502 Bad Gateway

Expected:
Display webpage hosted in container test

**Comment by ollin** [comment]
same problem here. Part of the generated `/etc/nginx/conf.d/default.conf` file is:

```
...
upstream z.y.com {                                                      
                # test_1
                server 172.17.0.2 down;
}  
...
```

**Comment by md5** [comment]
@leonpegg I just tried to reproduce your issue and couldn't do so. Does `docker logs proxy` say anything interesting? Also, you might want to take a look at the generated config file as @ollin did:

```console
$ docker exec proxy grep -vE '^\s*$' /etc/nginx/conf.d/default.conf
```

@ollin In your case, it looks like `test_1` is exposing more than one port and none of them are port 80. In your case, you'll need to use `VIRTUAL_PORT` to tell `nginx-proxy` which one to use.

**Comment by ollin** [comment]
@md5 That was exactly the problem. Thanks a lot!

**Comment by md5** [comment]
@ollin :+1:

**Comment by leonpegg** [comment]
@ollin I have just run command as you segested and I get this 
server {
	listen 80;
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	return 503;
}
upstream test.internal.dev {
			# test
			server 172.17.0.7:80;
}
server {
	  server_name test.internal.dev;
	location / {
		proxy_pass http://test.internal.dev;
	}
}

So seems correct any ideas

**Comment by md5** [comment]
@leonpegg I would try checking if your service is actually accessible on port 80:

```console
$ docker run --rm buildpack-deps:curl curl -f http://172.17.0.7/
```

The 502 error means that Nginx isn't able to reach the backend. In @ollin's case, that was because of an explicit `down` in the `upstream` block, due to the fact that `nginx-proxy` couldn't determine the correct port to connect to.

In your case, I'm guessing the actual service is not responding correctly on port 80.

**Comment by leonpegg** [comment]
@ollin I have just run command as you segested and I get this 
server {
	listen 80;
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	return 503;
}
upstream test.internal.dev {
			# test
			server 172.17.0.7:80;
}
server {
	  server_name test.internal.dev;
	location / {
		proxy_pass http://test.internal.dev;
	}
}

So seems correct any ideas

**Comment by leonpegg** [comment]
@md5 I am going to close this case as it seems to be a fedora specific problem relating to inter container networking containers can ping each other but call communication between them is blocked

**Comment by blackbarn** [comment]
Sorry to comment on an old ticket, but my issue was pointing VIRTUAL_PORT to my "external" port rather than the default of the service.

e.g., -p "3000:8080"  with VIRTUAL_PORT=3000 failed, with VIRTUAL_PORT=8080 it worked.

Kind of a "duh" moment in hindsight for myself.

**Comment by kamil-kielczewski** [comment]
My container (based on pierrezemb/gostatic image - very small fileserver) works on port 8043 and I have same problem, but when I use `--expose=8043` (despite that my dockerfile already have line `EXPOSE 8043` at the end) it starts to work :)

`docker run -e VIRTUAL_HOST=mydomain.com --expose=8043  -d --name mydomain-com -v $CURRENT_DIR:/srv/http pierrezemb/gostatic `

**Comment by flourishing** [comment]
krohrsb  i have the same problem ,it solved my problem too.  it's weird

**Comment by slavikme** [comment]
One of the common mistakes that may cause this issue is running the container outside of the `nginx-proxy` network, which is eventually unreachable by the `nginx-proxy`.

In order to run it in the same network as `nginx-proxy` you need to find out what in what network it is running. Just run the following command to find out:
```bash
docker network ls -f driver=bridge --format "{{.ID}}" | xargs docker network inspect | grep Name
```
It should give you the something like this:
```js
        "Name": "bridge",
                "Name": "influxdb",
                "Name": "mariadb",
        "Name": "http_proxy",
                "Name": "web-app",
                "Name": "proxy",
                "Name": "grafana",
```
And now I see that the container with the name `proxy` is under a network named `http_proxy`.
Now, I need to run the container within this network by adding the flag `--network http_proxy`:
```bash
docker run -d --name test --network http_proxy -h test.local -e VIRTUAL_HOST=test.local -v "$PWD":/usr/share/nginx/html nginx
```

Hope this helps.
Good luck!

**Comment by tomeady** [comment]
Still have this problem.

**Comment by barisates** [comment]
In CentOS Linux release 8.1.1911 (Core) version, **502 Bad Gateway** problem was solved when I stopped/disabled the firewall;

`systemctl stop firewalld`

`systemctl disable firewalld`

and then reboot VPS.

**Comment by dougalII** [comment]
> In CentOS Linux release 8.1.1911 (Core) version, **502 Bad Gateway** problem was solved when I stopped/disabled the firewall;
> 
> `systemctl stop firewalld`
> 
> `systemctl disable firewalld`
> 
> and then reboot VPS.

YUP! that did it!
But i was not happy with no fw, so i followed:
https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8

now i have nginx-proxy and firewalld

**Comment by barisates** [comment]
> > In CentOS Linux release 8.1.1911 (Core) version, **502 Bad Gateway** problem was solved when I stopped/disabled the firewall;
> > `systemctl stop firewalld`
> > `systemctl disable firewalld`
> > and then reboot VPS.
> 
> YUP! that did it!
> But i was not happy with no fw, so i followed:
> https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8
> 
> now i have nginx-proxy and firewalld


You can solve the problem by authorizing the Docker Network;

 ```
firewall-cmd --permanent --zone=trusted --change-interface=docker0
firewall-cmd --reload
```
