### ISSUE TITLE
VIRTUAL_PORT should override single addresses

### ISSUE THREAD

**Issue by Blaisorblade** [jwilder/nginx-proxy#204]
The documented logic is not what's implemented:
> If your container exposes multiple ports, nginx-proxy will default to the service running on port 80. If you need to specify a different port, you can set a VIRTUAL_PORT env var to select a different one. If your container only exposes one port and it has a VIRTUAL_HOST env var set, that port will be selected.

I have a Dockerfile exposing ports 80 and 22; in the run command, I only actually export port 22, and I want nginx-proxy to connect to port 80. But that fails because VIRTUAL_PORT is ignored in this context!

See https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L61-L71 — the outer if ignores VIRTUAL_PORT:
> ```
{{ range $container := $containers }}
	{{ $addrLen := len $container.Addresses }}
	{{/* If only 1 port exposed, use that */}}
	{{ if eq $addrLen 1 }}
		{{ $address := index $container.Addresses 0 }}
		{{ template "upstream" (dict "Container" $container "Address" $address) }}
	{{/* If more than one port exposed, use the one matching VIRTUAL_PORT env var, falling back to standard web port 80 */}}
	{{ else }}
		{{ $port := coalesce $container.Env.VIRTUAL_PORT "80" }}
		{{ $address := where $container.Addresses "Port" $port | first }}
		{{ template "upstream" (dict "Container" $container "Address" $address) }}
	{{ end }}
{{ end }}
```

**Comment by md5** [comment]
@Blaisorblade you seem to be confusing "exposing" a port in Docker with "publishing" it. There is no such thing as "exporting" a port in Docker terminology.

I also think you're misreading the the template. The `Addresses` struct member is actually a list of *exposed* address:port combinations, so in your case you have two "addresses". 

The use of `docker-gen` by this image includes the `-only-exposed` flag, so it will include any containers that have exposed ports. There is an `-only-published` flag for `docker-gen` as well, but that wouldn't make a lot of sense for this image since it generally only cares about connecting to backend containers on the Docker bridge network (excluding the Docker swarm use case).

**Comment by md5** [comment]
I should also add that `-only-published` currently does nothing to restrict `Addresses` to only include exposed ports with published port mappings.

**Comment by md5** [comment]
Also, I can't help but *tsk-tsk* at the port 22 thing...

**Comment by Blaisorblade** [comment]
Sorry for the confusion, the issue is indeed more complicated; I'm using https://github.com/discourse/discourse_docker, and apparently it does not expose any ports, it only uses `-p` to publish them.

Moreover, if a port is not exposed at all, it's inaccessible, so there's nothing your tool can do — I need to get that changed on the discourse_docker side. So, if there's only one exposed port, it's correct to ignore VIRTUAL_PORT as you do.

And indeed, if I force it to pass `--expose 80` to Docker, your program does what you describe.

```
        "Ports": {
            "22/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "2223"
                }
            ],
            "80/tcp": null
```

On port 22, feel free to _tsk-tsk_ at https://github.com/discourse/discourse_docker ;-)

Hence, I'm closing the issue.

**Comment by md5** [comment]
Just took a look at the Discourse Docker image... Doesn't seem like they're following any Docker best practices I've ever seen, but I suppose it works for them. I fear for the people whose first exposure to Docker is through images like these, but it's not really something that can be helped.

**Comment by ArthurianX** [comment]
I'm having the same issue, multiple containers running behind this nginx-proxy container and the launcher stops when it encounter the VIRTUAL_HOST param. 

Did you find any solution to this issue ?
