### ISSUE TITLE
Container for any domains

### ISSUE THREAD

**Issue by starikovs** [jwilder/nginx-proxy#211]
Hello,

Is it possible to start a container that responses to any domain names?

`docker run -e VIRTUAL_HOST=?? ...`

Thanks a lot!

**Comment by md5** [comment]
It would be possible to use a regex value for `VIRTUAL_HOST`, except that there are currently some issues with that. If #124 gets merged, it should work fine to use something like `-e VIRTUAL_HOST=~^.*$`.

See #117 for additional discussion of regex virtual hosts.

**Comment by starikovs** [comment]
@md5 I've just done it with these containers:

    $ docker run DEFAULT_HOST=localhost -v /var/run/docker.sock:/tmp/docker.sock:ro -v /vagrant/certs:/etc/nginx/certs -p 80:80 jwilder/nginx-proxy
    $ docker run -e VIRTUAL_HOST=localhost app

So, because of `DEFAULT_HOST` which sets `default_server` nginx option, the app container gets all the requests for any domains.
