### ISSUE TITLE
with -e VIRTUAL_PROTO=https upstream server still listening on port 80

### ISSUE THREAD

**Issue by ict4ngo** [jwilder/nginx-proxy#217]
the configuration generated by nginx-proxy when using this option is like this

```
upstream www.example.com {
                        # example_com_live
                        server 172.17.0.96:80;
}

server {
        server_name www.example.com;
        location / {
                proxy_pass https://www.example.com;
        }
}
```

I'd rather expect it to listen to 443 like this :

```
upstream www.example.com {
                        # example_com_live
                        server 172.17.0.96:443;
}

server {
        server_name www.example.com;
        location / {
                proxy_pass https://www.example.com;
        }
}
```

**Comment by md5** [comment]
`VIRTUAL_PROTO` only controls how the proxy connects to the backend, as you've found. In order to have the proxy accessible on port 443, you'll also need to configure SSL support according to the instructions: https://github.com/jwilder/nginx-proxy#ssl-support

**Comment by ict4ngo** [comment]
the proxy listen externally to both :80 and :443 ports and if I drop a certificate and its key in the certs folder it will serve the backend container with https. However for specific reasons the ssl is on backend container. I just need to transparently pass the requests to the apache container with ssl.

**Comment by md5** [comment]
Nginx isn't capable of "transparently" proxying SSL. SSL is terminated by the `nginx-proxy` container and another SSL connection is made to the backend.

I'm not sure what problem you're actually having.

**Comment by adambiggs** [comment]
I just ran into this issue. I'm using `nginx-proxy` to mimic AWS ELB for local development. 

We're switching ELB to TCP mode in production so that we can have a backend service handle SSL negotiation. But I'm not sure how to mirror this for local development.

Any advice?

**Comment by adambiggs** [comment]
FWIW I was able to work around the issue by setting up `dnsmasq` to forward requests for that particular service directly to the backend server, removing `nginx-proxy` from the chain in this specific scenario.
