### ISSUE TITLE
Choose between duplicate VIRTUAL_HOST containers based on version number?

### ISSUE THREAD

**Issue by markrendle** [jwilder/nginx-proxy#218]
Is there any way to handle having two containers running simultaneously with the same VIRTUAL_HOST value, and pick the one with the highest value in another environment variable such as VERSION_NUMBER? Thus allowing for seamless upgrade of running containers? Or, is there another way to achieve this? I don't want to have to jump to the complexity of something like Deis or Shipyard, as I can't afford to be running clusters.

**Comment by jwilder** [comment]
Multiple containers with same `VIRTUAL_HOST` are load-balanced.  You can start one and stop the other once it's up to minimize downtime.

**Comment by grahovam** [comment]
What kind of load-balancing are having two containers with the same VIRTUAL_HOST? Is there a documentation for this?
