### ISSUE TITLE
Error running notify command: nginx -s reload, exit status 1

### ISSUE THREAD

**Issue by hbbio** [jwilder/nginx-proxy#226]
I'm using:

```
docker run -d -p 443:443 -p 80:80 -v /local/path/to/certs:/etc/nginx/certs --name nginx -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

where the path contains the certs.

Then, I run the http container (which contains `EXPOSE 80`) with:

```
docker run -e "VIRTUAL_HOST=my.host.name" --name server -d ...
```

The http container runs fine (as checked via curl from the host). But the proxy returns:

- 503 for http
- ERR_CONNECTION_REFUSED for https.

Using `docker logs nginx`, it shows that:

```
dockergen.1 | 2015/08/26 17:26:32 Received event start for container 51b0438c6a54
dockergen.1 | 2015/08/26 17:26:32 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
dockergen.1 | 2015/08/26 17:26:32 Running 'nginx -s reload'
dockergen.1 | 2015/08/26 17:26:32 Error running notify command: nginx -s reload, exit status 1
```

What am I doing wrong? I tested with http only and have the same problem.

**Comment by thaJeztah** [comment]
Could be that an invalid nginx configuration was generated; you can copy the generated config file out of your container, to check if it contains something weird, something like

    docker cp nginx:/etc/nginx/conf.d/default.conf .

That should copy the file out of the container to your local file system

**Comment by md5** [comment]
It would still be nice to have a check command in `docker-gen`: https://github.com/jwilder/docker-gen/issues/67

That would allow `nginx -t` to be run automatically and return a decent error message.

**Comment by hbbio** [comment]
Here is the gist: https://gist.github.com/hbbio/4a29b68b460d46bd6d28

(Naturally, `the.domain.com` is the actual domain. All the empty lines are present in the file, is it normal?)

**Comment by jwilder** [comment]
Try running `docker exec -it $CONTAINER_ID nginx -t` where `$CONTAINER_ID` is the id/name of you `nginx-proxy` container.

**Comment by hbbio** [comment]
Thanks for your help.

Turns out the SSL certificate chain was in wrong order, hence the following error: `SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch`. Because of that, even the http proxy was not available.

**Comment by FallenRiteMonk** [comment]
Hy, I'm pretty new to this, so could you please explain how you them fixed the problem?

**Comment by wader** [comment]
@FallenRiteMonk i think he means that he crt file was concatenated in the wrong order, see http://nginx.org/en/docs/http/configuring_https_servers.html#chains (search for "order")
