### ISSUE TITLE
Error inspecting container: High memory allocation (1.073741824e+09)

### ISSUE THREAD

**Issue by m-kuhn** [jwilder/nginx-proxy#237]
I am trying to run owncloud behind the nginx-proxy

```
$ docker run --name "proxy" -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

```
$ docker run -e "VIRTUAL_HOST=cloud.mydomain.org" -d -m 1g --expose 80 --name="owncloud" -v /var/owncloud/data:/var/www/owncloud/data -v /var/owncloud/config:/var/www/owncloud/config btobolaski/owncloud
WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
```

I get a 503 http error in the browser. Checking the logs gives:

```
$ docker logs proxy
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2015/09/21 15:49:27 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2015/09/21 15:49:27 Running 'nginx -s reload'
dockergen.1 | 2015/09/21 15:49:27 Watching docker events
dockergen.1 | 2015/09/21 15:49:38 Received event start for container f27fe0a43ddd
dockergen.1 | 2015/09/21 15:49:38 error inspecting container: f27fe0a43ddd6871e3ddbf6cd4095dc9e8edb8f2fd43e490be4476d30dbd6a2b: json: cannot unmarshal number 1.073741824e+09 into Go value of type int64
dockergen.1 | 2015/09/21 15:49:38 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

Checking where the value in question comes from:

```
$ docker inspect f27fe0a43ddd68 | grep 1.07374
"Memory": 1.073741824e+09
```

**Comment by m-kuhn** [comment]
Workaround: running the other container without the `-m 1g` parameter it is picked up by the proxy

**Comment by md5** [comment]
This seems to have been fixed in this PR back in July 2014: https://github.com/fsouza/go-dockerclient/pull/111

Are you using a really old version of the image or something?

**Comment by md5** [comment]
Actually, it looks like you may be using an old version of Docker? See here: https://github.com/fsouza/go-dockerclient/issues/129

**Comment by m-kuhn** [comment]
I am using the `docker.io` package from ubuntu 14.04

```
$ docker --version
Docker version 1.0.1, build 990021a
```

**Comment by md5** [comment]
You should definitely look at upgrading. You're going to have a hard time getting support for such an old version of Docker.

**Comment by m-kuhn** [comment]
And I thought it's a good idea to go for the LTS version...

**Comment by md5** [comment]
Going with the LTS version of Ubuntu is a fine and good choice. Using the Ubuntu-provided packages for Docker is going to be a problem though. You should have a look here: https://docs.docker.com/installation/ubuntulinux/

**Comment by m-kuhn** [comment]
It works with

http://www.ubuntuupdates.org/ppa/docker

```
$ sudo sh -c "echo deb https://get.docker.io/ubuntu docker main \
> /etc/apt/sources.list.d/docker.list"
$ sudo apt-get update
$ sudo apt-get install lxc-docker
```

Thanks a lot
