### ISSUE TITLE
Forwarding VIRTUAL_HOST to other containers in docker-compose.yml

### ISSUE THREAD

**Issue by georgediaz88** [jwilder/nginx-proxy#253]
I'm using a `docker-compose.yml` to run my web app and have brought in `nginx-proxy` as a container:

```
# docker-compose.yml

nginxproxy:
   restart: always
   image: jwilder/nginx-proxy
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
   ports:
     - "80:80"

web:
  build: .
  command: ./script/start_docker
  environment:
    VIRTUAL_HOST: app.docker
    VIRTUAL_PORT: 3000
  ports:
    - "3000:3000"
    - "3010:3010"
  links:
    ...

other-container:
  ...
  ^^ can't reach app.docker:3000
```

This works fine and is reachable by my web app container if I pass a `VIRTUAL_HOST=app.docker` and `VIRTUAL_PORT=3000`. However, in other containers, where I'd like to reach the `VIRTUAL_HOST`, I **can't**. Even in my "web" container I can't curl by the `VIRTUAL_HOST`. Any ideas how to make the `VIRTUAL_HOST` available on my other containers? Do I need to pass `VIRTUAL_HOST` for every container? I'm still unsure. Any help would be appreciated. Thanks.

**Comment by jwilder** [comment]
You need to send the request from your other containers _to_ your `nginxproxy` container's port 80 and specify the correct `Host` header. You could probably specify some [extra_hosts](https://docs.docker.com/compose/yml/#extra-hosts) config options to your other containers to create hosts entry for `app.docker   <your host ip>`.    You could also look at: http://engineering.ifttt.com/oss/2015/10/06/developing-with-docker/ which uses `dnsmasq` to handle DNS resolution locally.

**Comment by georgediaz88** [comment]
@jwilder thanks for response.

Okay, that makes sense. It seemed I was missing a step somewhere. It was almost too easy ;). I'll take a look at both solutions. Thanks.
