### ISSUE TITLE
Example using nginx-proxy for mailservers

### ISSUE THREAD

**Issue by shl-berlin** [jwilder/nginx-proxy#258]
First I like to thank you for one of the greatest docker apps. Everything is fine but I am struggling a little bit how to get it working as a Mail-Proxy-Server (Imap,smtp,postfix, http).
What is the best way to do it? Create a new template? Per vHost-Configuration?

I hope someone could help. For sure I would share my experience with the nginx-proxy community.

Regards

**Comment by md5** [comment]
Since Nginx itself can't proxy SMTP, it's not going to be possible for this image to support it.

What are you trying to achieve? Are you looking for a container that can accept SMTP connections for a bunch of different domains and proxy incoming messages for different domains to different backend containers?

**Comment by md5** [comment]
I should say Nginx in its default configuration can't do SMTP. It does support it with [`ngx_mail_core_module`](http://nginx.org/en/docs/mail/ngx_mail_core_module.html), but that's not compiled into the `nginx` executable used by this image.

**Comment by jwilder** [comment]
@shl-berlin You could probably run a custom nginx image and the separate container install instructions here: https://github.com/jwilder/nginx-proxy#separate-containers  Probably would need a custom template as well: https://github.com/jwilder/nginx-proxy#custom-nginx-configuration

**Comment by shl-berlin** [comment]
Hey! 
Thanks for your answers. In my case I have two Mailservers. One is in the production state and the other one I want to prepare to take over the first one.
The first one is installed on the host system directly, without docker. The second one should be in a docker container. At the moment I am planing what is the best solution and the beay way to switch over. For testing proposes I thought it would be nice to do a kind of subdomain splitting.

This means:
first mailserver = masterdomain.com
second mailserver = testing.maildomain.com 

Thanks a lot for you help guys.
