### ISSUE TITLE
nginx-proxy does not work with protected Docker sockets

### ISSUE THREAD

**Issue by sebflipper** [jwilder/nginx-proxy#261]
I currently have my Docker service configured and running using public/private key authentication, following the [official documentation on protecting the Docker daemon socket](https://docs.docker.com/articles/https/).

When running the default run command:
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

`docker-gen` appears to hang in the container and does not generate or output an nginx configuration, so when I try to go to any of my other containers I get the default nginx welcome page.

I've managed to get around this issue by using the following run command. This forwards the TLS keys to the container and sets the environment so that `docker-gen` uses TLS and is able to connect to the host without sharing the socket.

```
docker run -d --name nginx-proxy \
  -p 80:80 \
  -e DOCKER_HOST=tcp://<docker-hostname-or-ip-address>:2376 \
  -e DOCKER_TLS_VERIFY=1 \
  -e DOCKER_CERT_PATH=/etc/pki/docker/ \
  -v /etc/pki/docker:/etc/pki/docker \
  jwilder/nginx-proxy
```

Is this the correct way to connect to a secure Docker host? If so it might be worth adding this tidbit to your README.

**Comment by md5** [comment]
It sounds like your Docker daemon is only listening on the TLS-protected
TCP socket.

You can either do what you've done with DOCKER_TLS_* or you can have it
listen on both the TLS socket and the Unix socket by adding “-H unix://" to
your command line. The Unix will only be accessible to root and users in
the “docker" Unix group on the Docker host itself.

**Comment by sebflipper** [comment]
Good spot! Didn't know you can get Docker to listen on multiple hosts.

I've changed my `/usr/lib/systemd/system/docker.service` so it now includes the default host:
```
ExecStart=/usr/bin/docker daemon -H fd:// \
        --tls=true \
        --tlsverify \
        --tlscacert=/etc/pki/docker/ca.pem \
        --tlscert=/etc/pki/docker/server-cert.pem \
        --tlskey=/etc/pki/docker/server-key.pem \
        -H tcp://0.0.0.0:2376
```

It now works both ways, so I've switched my setup to use the standard `run` command.

Cheers!

**Comment by md5** [comment]
:+1:
