### ISSUE TITLE
How to deal with different ports? IE - example.com(:80) and example.com:3000

### ISSUE THREAD

**Issue by JulianKingman** [jwilder/nginx-proxy#267]
How can I set up multiple ports such that a an exposed port is available at the URL? For example, if I'm running a web app at example.com (port 80), and it's database on port 3000, how can I publicly access example.com:3000 and have it pointing at the right container?

If I understand the VIRTUAL_PORT variable correctly, it maps port 80 of the URL to the specified port of the container, so what I want to do is kind of opposite of that. I hope that makes sense, or perhaps I'm not understanding things correctly...

**Comment by md5** [comment]
This image is only able to proxy HTTP and related protocols. It can't proxy database protocols.

**Comment by JulianKingman** [comment]
OK, so is the best solution here to just use the IP address and a unique port?

**Comment by md5** [comment]
I'm not sure what problem you're trying to solve, so I can't say.

**Comment by md5** [comment]
If you're trying to access your database on a public port, I'd recommend against doing that. For container-to-container communication, you can use Docker links.

If you're trying to access your database server from a desktop client for administration purposes, I'd recommend using SSH tunneling. In the case of MySQL Workbench, here's an overview of how to do that: https://dev.mysql.com/doc/workbench/en/wb-mysql-connections-methods-ssh.html

To make that work with Docker, you would indeed need to expose each database with a different port on localhost, using invocations like `-p 127.0.0.1:3000:3306`, `-p 127.0.0.1:3001:3306`, etc. to expose each database container's port 3306 as a different port on localhost.
