### ISSUE TITLE
multiple containers using 443 and mapped 443 to 1044X

### ISSUE THREAD

**Issue by miguelqvd** [jwilder/nginx-proxy#269]
Hi, 

Congrats for your excellent solution.

I'm using docker-compose to build my ci environment and I have several web sites for which I map the port 443 to other in other to co-exists.
 
container1: 192.168.99.100:443 -> 192.168.99.100:10443
container2: 192.168.99.100:443 -> 192.168.99.100:10444
container3: 192.168.99.100:443 -> 192.168.99.100:10445

then I've specified for each one corresponding VIRTUAL_HOST and VIRTUAL_PROTO=https

I success to connect to https://container1.dommain:10443 and so on but I fail to connect to https://container1.domain:443.

How should I deal in this case with multiple containers exposing ssl services?

**Comment by jwilder** [comment]
Did you start the proxy using the instructions here: https://github.com/jwilder/nginx-proxy#ssl-support.  `nginx-proxy` will need access to the SSL certs for each container if you you are trying to connect to the proxy over SSL.

**Comment by miguelqvd** [comment]
Thanks for your replay. Yes, I did exactly that. I've generated all the certificates like in the specs but it doesn't work still. Here's my docker-compose.yml, I've simplified it just to have nginx-proxy and redmine. Redmine goes out throught port 10444 (https://redmine.mydomain:10444) but what I want to achieve is https://redmine.mydomain:443 in coexistence with other web apps in the same docker server also mapping 443 to other ports.

container1: "10443:443" --> https://container1.mydomain:443 (to the public)
container1: "10443:443" --> https://container1.mydomain:443 (to the public)
container2: 192.168.99.100:443 -> 192.168.99.100:10444
container3: 192.168.99.100:443 -> 192.168.99.100:10445

reverseproxy:
  image: jwilder/nginx-proxy
  ports:
    - "443:443"
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /mnt/sda1/srv/reverseproxy/certs:/etc/nginx/certs

postgresql_redmine:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=redmine
    - DB_PASS=redminedev
    - DB_NAME=redmine_production
  volumes:
    - /mnt/sda1/srv/redmine/postgresql:/var/lib/postgresql

redmine:
  image: sameersbn/redmine:latest
  links:
    - postgresql_redmine:postgresql
  environment:
    - VIRTUAL_HOST=redmine.mydomain
    - VIRUTAL_PROTO=https
    - VIRTUAL_PORT=443
    - TZ=Europe/Berlin
    - REDMINE_PORT=10444
    - REDMINE_HTTPS=true
    - REDMINE_HTTPS_ONLY=true
    - REDMINE_HTTPS_HSTS_ENABLED=true
    - REDMINE_HTTPS_HSTS_MAXAGE=2592000
    - SSL_KEY_PATH=/app/setup/certs/redmine.pem
    - SSL_CERTIFICATE_PATH=/app/setup/certs/redmine.crt
    - SSL_DHPARAM_PATH=/app/setup/certs/dhparam.pem

**Comment by vfulco** [comment]
Reviewing OP's file since I am stuck port mapping to nginx-proxy, noticed you have a mis-spelling "- VIRUTAL_PROTO=https".

**Comment by miguelqvd** [comment]
Awesome!I had already given up! Now I'm able to have my whole infrastructure running on https.

 Thank you much for watching this!

**Comment by miguelqvd** [comment]
The issue is solved. Bad Typo. 

Thanks!
