### ISSUE TITLE
Custom 503 error page

### ISSUE THREAD

**Issue by trescst** [jwilder/nginx-proxy#275]
I am trying to customize the 503 error page that is being shown when for example you hit the nginx-proxy using its IP adress instead of a domain known to nginx-proxy, or when your backend container is not up-and-running due to an upgrade.

I edited the `nginx.tmpl` as follows, but this doesn't seem to be doing anything:
```
{{ end }}

server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;

        error_page 503 @503;
        return 503;
        location @503 {
          try_files /usr/share/nginx/html/maintenance.html =503;
        }
}

{{ if (and (exists "/etc/nginx/certs/default.crt") (exists "/etc/nginx/certs/default.key")) }}
```

Anybody any suggestions on how to make this work?

**Comment by maaarghk** [comment]
Hi @trescst  - if you don't have this already it's:

```
{{ end }}

server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        error_page 503 /503.html;
        location = /503.html {
                root /usr/share/nginx/html;
                internal;
        }
        location / {
                return 503;
        }
}

{{ if (and (exists "/etc/nginx/certs/default.crt") (exists "/etc/nginx/certs/default.key")) }}
```

My dockerfile looks like:
```
FROM jwilder/nginx-proxy
COPY ./nginx.tmpl /app/nginx.tmpl
COPY ./503.html /usr/share/nginx/html/503.html
```

**Comment by trescst** [comment]
Hi @maaarghk, ,many thanks, that indeed dit the job!

**Comment by hadpro24** [comment]
Someone find solution for that ?

**Comment by maaarghk** [comment]
I've just checked @SkylerGhostly and nginx.tmpl is a lot more complex since my comment above so I think you're right that's it a bad move to edit it. The 50x.html ships with nginx and is part of the default configuration; but indeed even in there it specifically needs to be activated with a server directive to take effect - from the horse's mouth:

https://github.com/nginx/nginx/blob/9e1a000f2bb5d32d0fa8ff804ce8a0f7539694d7/conf/nginx.conf#L50-L55

The readme now states you can add a file instead to the location `/etc/nginx/vhost.d/default_location` and it will be included in all location blocks. Only this section from the above snippet would be required:

```
error_page 503 /503.html;
location = /503.html {
    root /usr/share/nginx/html;
    internal;
}
```

(the purpose of `internal` is so that someone can not go to http://yoursite.com/503.html for the error page)

**Comment by SkylerGhostly** [comment]
Thanks for the info, @maaarghk

I've tried using the  `default_location` file with your given settings with no change. I still see the generic errors. I suppose I should also mention that I'm using `nginxproxy/acme-companion` alongside `jwilder/nginx-proxy` for SSL encryption. Both containers have access to the html directory, vhosts.d, and conf.d.

The only thing I can seem to get to work is using a file in `/etc/nginx/vhost.d` with these contents:
```
server {
    server_name _; # This is just an invalid value which will never trigger on a real hostname.
    server_tokens off;
    
    listen 80 default_server;
    listen 443 ssl http2 default_server;

    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    access_log /var/log/nginx/access.log vhost;
    ssl_certificate /etc/nginx/certs/default.crt;
    ssl_certificate_key /etc/nginx/certs/default.key;

    error_page 500 /500.html;
    location = /500.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 503 /503.html;
    location = /503.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 503;
    }
}
```

Even with this, the 500 error isn't even overridden. This is all a bit confusing and I'm probably not apt to fix it myself.

**Comment by f616** [comment]
Can this issue be reopen? Need to implement customer 50x.html page and the `/etc/nginx/vhost.d/default_location` doesn't seem to take any effect on this.

This is my `docker-compose.yml` file:

`version: '3.9'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy-1-nginx
    restart: "always" # Always restart container
    ports:
      - "80:80" # Port mappings in format host:container
      - "443:443"
    networks:
      - nginx-proxy # Name of the network these two containers will share
    volumes: # Volumes needed for container to configure proxies      
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default_location:/etc/nginx/vhost.d/default_location:ro
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - ./nginx/html:/usr/share/nginx/html/err:ro`

And this is my `default_location` file:

`error_page 503 /503.html;
location = /503.html {
    root /usr/share/nginx/html;
    internal;
}`

**Comment by SkylerGhostly** [comment]
Any update on this issue would be much appreciated ...

**Comment by Prime1Code** [comment]
Push

**Comment by buchdag** [comment]
#2430 should take care of this.
