### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dropfen** [jwilder/nginx-proxy#279]
Help,
this is the second time I am working with nginx-proxy and the first time everything worked pretty well, now something is wrong.

The difference of the both cases is the COMMAND of the proxy container when you look at docker ps:

### Working case
jwilder/nginx-proxy:latest   **"forego start -r"**      4 months ago        Up 4 months         0.0.0.0:80->80/tcp, 443/tcp                          sharp_franklin      

### Not working case (started the same way, as the first one)
jwilder/nginx-proxy:latest   **"/app/docker-entrypoi"**   7 seconds ago       Up 6 seconds        0.0.0.0:80->80/tcp, 443/tcp   kickass_panini

I've actually no clue, why the COMMAND is different, but I know, that the first case is working, and the second not. Any ideas?

**Comment by md5** [comment]
The entrypoint command was added in https://github.com/jwilder/nginx-proxy/pull/235

You're going to have to give some more information about what exactly is not working. The output of `docker logs` for your `jwilder/nginx-proxy` container might be helpful in this regard. It would also be good to describe how you're testing your proxy setup and what response you're seeing

**Comment by dropfen** [comment]
Sure, I am going to setup a simple nginx server (for static content), and which should get an own virtual host.. Imagine this is a fresh ubuntu14.04, so my steps are:

1. run the vhost proxy
2. run the nginx server on the a special vhost

So, after step one, I expected to see some response from the running nginx, even if it's a **503 Service Temporarily Unavailable** response..

Have I missed something?

**Comment by dropfen** [comment]
docker logs for nginx-proxy:

forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2015/10/30 22:44:20 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2015/10/30 22:44:20 Running 'nginx -s reload'
dockergen.1 | 2015/10/30 22:44:20 Watching docker events

**Comment by md5** [comment]
It doesn't look like the nginx-proxy container is seeing any containers
other than itself. Otherwise, there would usually be a “Generated" message
with a number greater than 1.

Are both containers running on the same Docker host? What do your “docker
run" commands look like.

**Comment by dropfen** [comment]
True, only the proxy was running in this case. this is the output when both are running:

forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2015/10/30 22:44:20 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2015/10/30 22:44:20 Running 'nginx -s reload'
dockergen.1 | 2015/10/30 22:44:20 Watching docker events
dockergen.1 | 2015/10/30 23:15:21 Received event start for container 8c904e330e15
dockergen.1 | 2015/10/30 23:15:21 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2015/10/30 23:15:21 Running 'nginx -s reload'

But, even if the second is not running, shouldn't I see a nginx response anyway, like **503 Service Temporarily Unavailable** ?

**Comment by dropfen** [comment]
Sorry, I guess there are some Server Management Issues with this machine, because when I do
`curl localhost`
I get the expected result. So the error is somewhere else. Thank you for your attention @md5

**Comment by md5** [comment]
@dropfen :+1:
