### ISSUE TITLE
How to expose port ranges?

### ISSUE THREAD

**Issue by ir-fuel** [jwilder/nginx-proxy#281]
Hi

In the readme I can see that if my container uses a different port than port 80,or exposes multiple ports I can use VIRTUAL_PORT to chose the one I want to expose. In my case however I have to run an FTP server, which exposes about 100 ports (on top of 21) to support PASV mode. How can I use this proxy to expose a portrange to a certain subdomain, so that all `ftp.mydomain.com` calls would map to all those ports?

Thanks

**Comment by jwilder** [comment]
Nginx doesn't support proxying FTP so this project won't work for your use case.
