### ISSUE TITLE
support for webdav broken

### ISSUE THREAD

**Issue by quentinburley** [jwilder/nginx-proxy#287]
nginx seems to have some issues with webdav.  (not specifically related to 'nginx-proxy' but the base image nginx.)

It gives 405 HTTP status errors for example in this log:
"PROPFIND / HTTP/1.1" 405 318 "-" "WinSCP/5.7.6 neon/0.30.1"

perhaps it is required the module: nginx-dav-ext-module

as described here

http://stackoverflow.com/questions/24666457/nginx-webdav-could-not-open-collection

Any thoughts?

**Comment by jwilder** [comment]
Webdav isn't supported by this project.   You could certainly extend the image and add new modules that you need though.
