### ISSUE TITLE
How to reverse proxy SSH?

### ISSUE THREAD

**Issue by chazmuzz** [jwilder/nginx-proxy#289]
Is there any way to run an SSH service using this project or will it handle HTTP traffic only?  If not then what can I use for sshing to virtual hosts?

**Comment by jwilder** [comment]
This isn't possible with this image.

**Comment by jmls** [comment]
urgh - we just hit this as well. Is there a solution anywhere ?

**Comment by wader** [comment]
What is the use case, dynamically proxy SSH connections to containers somehow? there does not seem to be anything similar to SNI for ssh at the moment.

**Comment by jmls** [comment]
yes, we have multiple containers that are running ssh, and I want to be able to use nginx to proxy to them, just like we do with https

**Comment by wader** [comment]
I guess you need to proxy based on key pair, username as hostname does not seem to available. Maybe something like https://github.com/tg123/sshpiper combined with docker-gen? but i think this functionality should probably be a separate project.

**Comment by jmls** [comment]
@wader thanks for the help and pointers - I don't suppose that you have an example of how to use docker-gen and sshpiper ? I am struggling to get it working with docker containers

**Comment by wader** [comment]
@jmls nope, sorry
