### ISSUE TITLE
Allow to set the value for client_max_body_size

### ISSUE THREAD

**Issue by zedtux** [jwilder/nginx-proxy#29]
I'm trying to make ownCloud working and everything work great until I try to upload a file of more than 3 Mb.

It seems that the instruction `client_max_body_size` is missing.

It would be nice to add another variable to manipulate the `client_max_body_size` value.

**Comment by Nitesedge** [comment]
can we merge this? I tested out jperville's template change and it appears to work for what I need with owncloud.

**Comment by StormBP** [comment]
merge this. please

**Comment by md5** [comment]
@StormBP I can't speak for @jwilder, but I don't think that https://github.com/zedtux/nginx-proxy is in a state to be merged. It has a bunch of redundant but incompatible changes along with changes that could be done in other ways.

In terms of setting `client_max_body_size`, that can be done currently on a proxy-wide basis by creating a file under `/etc/nginx/conf.d` that includes `client_max_body_size 100m;` or whatever you want. The same thing can be done for the `server_tokens off;` in `zedtux/nginx-proxy`. That file can be either created in a `Dockerfile` that derives `FROM jwilder/nginx-proxy` or it can be mounted in with `-v`.

The other case that people seem to want is the ability to set `client_max_body_size` on a per-`VIRTUAL_HOST` basis. For this, as for other things, I don't think a proliferation of environment variables is the right approach. I prefer the idea proposed by @thaJeztah in https://github.com/jwilder/nginx-proxy/issues/29#issuecomment-65275492, namely the ability to add a per-`VIRTUAL_HOST` conf file that will be loaded based on a naming convention. This is more in line with the way other things are done in this image (cf. SSL, basic auth).

The only other change I noticed in the @zedtux fork that should be added is the addition of `application/javascript` to `gzip_types`. That could be added in a simple PR for just that change.

**Comment by jwilder** [comment]
Yeah, @md5 summed up my thoughts as well.  I don't think adding another env var for this feature is the right way to go.  I think supporting custom templates per vhost would be much more extensible.

**Comment by zedtux** [comment]
I agree with @md5. What I'm doing in my fork is just dirty but working stuff for my personal use.

Implementing those idea in the perfect way is the responsibility of this upstream repository in my opinion, meaning when done my fork is no more needed.
