### ISSUE TITLE
Noob teething problems with https:  still

### ISSUE THREAD

**Issue by vfulco** [jwilder/nginx-proxy#290]
Still a bit lost on https setup.  Some of it could be because containers I am trying have their own SSL policies I have to work around (l3iggs/owncloud). So close and yet so far:

Any simple container (flask test) works on http except when I name the default_host while running nginxy-proxy, get a #503 naturally.

For HTTPS, am I correct that I need:

1) to set up a certificate (in my case self-signed) for each vhost and link the folder holding them from server to nginx-proxy (-v /path/to/certs:/etc/nginx/certs \)? Is a wildcard self-signed possible?  Googling didn't surface any. 

2) set up passwords for each vhost and link the folder holding them on the server: (-v /path/to/htpasswd:/etc/nginx/htpasswd)

3) For each container being run I need to name each of these: CERT_NAME=foo.bar.asia -VIRTUAL_HOST=foo.bar.asia and VIRTUAL_PROTO=https?

4) Expose any ports except for 80 and 443 within the docker run statement?

What is the need for naming a default_host if nothing is being served from it? I see some are using it and some are not.  Wouldn't another container be addressing the URL in question?

Thanks in advance

**Comment by vfulco** [comment]
Now I get a #502 error when the URL and the certificate indicate the exact same thing cloud.foo.asia while trying to access the owncloud docker container which is running

**Comment by vfulco** [comment]
Saw the DNS cache flushing others tried and it worked for me.  Still feels a bit fragile and I would like to understand the debate between terminating SSL at nginx-proxy vs. by container if anyone has some thoughts.

**Comment by jwilder** [comment]
SSL termination happens at nginx-proxy because it does not support TCP proxying by default.  I believe Nginx Plus R5 supports TCP proxying, but this image is not based on Nginx Plus.  If you wanted to terminate SSL at the backends, HAProxy might be a better fit since it can proxy TCP connections.
