### ISSUE TITLE
How to extend the dockerfile?

### ISSUE THREAD

**Issue by kentmw** [jwilder/nginx-proxy#293]
If I want to extend this container to perform some actions and maybe copy some files from a personal context, and then run nginx, how might I do it?

This is what I'm thinking of doing:
```
FROM jwilder/nginx-proxy:0.2.0
COPY myFile /etc/nginx/
CMD ["forego", "start", "-r"]
```
I'm not sure what happens to the CMD line that was in the parent's Dockerfile. Do I also have to restate the entrypoint?

**Comment by wader** [comment]
You should be able to just skip it and the CMD from `jwilder/nginx-proxy` will be used

**Comment by kentmw** [comment]
Thanks @wader I'll give it a shot
