### ISSUE TITLE
nginx-proxy to multiple containers

### ISSUE THREAD

**Issue by Toub** [jwilder/nginx-proxy#297]
I would like to deploy my application using 2 containers, e.g. one for client (static javascript single application) and one for server rest api.

I could user 2 different domains, (myserver.com & api.server.com), but what if I want to keep both in the same domain (myserver.com & myserver.com/api) ?

What is the most elegant way to link my 2 containers to nginx-proxy configuration?

**Comment by jwilder** [comment]
I think you would need #47 which this image does not support yet.  Adding that is somewhat complicated right now.

**Comment by Toub** [comment]
Work in progress : https://github.com/jwilder/nginx-proxy/pull/254 and https://github.com/jwilder/nginx-proxy/pull/259
