### ISSUE TITLE
(Auto-)Update Docker Hub image

### ISSUE THREAD

**Issue by fbender** [jwilder/nginx-proxy#307]
The [Docker Hub](https://hub.docker.com/r/jwilder/nginx-proxy/) image is still built with `nginx:1.9.5`, according to the [Dockerfile](https://hub.docker.com/r/jwilder/nginx-proxy/~/dockerfile/). The badge in the README says `nginx:1.9.2`. Can you please update both (or you may want to delete the badge)?

You might want to link the Hub image with this repo to auto-update the image on push. When you relax the version constraint for nginx, e.g. to `FROM nginx:1.9` and link the image to the upstream image (current version is 1.9.7), you'll get automatic updates there as well. Either way, you can link to the upstream Debian image to at least receive automatic package updates if you want to stay on a fixed version of nginx for the image (or link both for max effect).

**Comment by thaJeztah** [comment]
See this https://github.com/jwilder/nginx-proxy/pull/57#issuecomment-65462239 for pinning to a specific version :smile:

**Comment by fbender** [comment]
@jwilder There seems to be an issue with [your latest builds on Docker Hub](https://hub.docker.com/r/jwilder/nginx-proxy/builds/). It seems they were auto-generated. This broke my auto-generated custom "child" builds, too. Can you take a look at this?

BTW, you can set e-mail notification if a build on Docker Hub fails.

**Comment by jwilder** [comment]
@fbender I kicked it and setup notifications.  Didn't know about the notifications... thanks!

**Comment by fbender** [comment]
Awesome, looks good!

**Comment by fbender** [comment]
Oh yeah, did you link the build with the upstream Debian and nginx images, so your build gets updated once they are updated?

**Comment by md5** [comment]
@fbender Linking with the `debian` image should not be necessary since the Official Images build process rebuilds all child images when there are changes to the parent images.

**Comment by jwilder** [comment]
@fbender I linked it to the `nginx` image.

**Comment by fbender** [comment]
Cool thanks!

**Comment by md5** [comment]
I just remembered that this image has a specific version requirement for the `nginx` image, so version bumps of the official `nginx` image won't have any effect even if the automated build is linked.

**Comment by md5** [comment]
The only case where it will have an effect is if the version that `nginx-proxy` is using is still the latest version and the `nginx` image is updated for some reason other than a version bump (e.g. a rebuild of the parent `debian` image).
