### ISSUE TITLE
nginx-proxy is in legacy registry!

### ISSUE THREAD

**Issue by ermaker** [jwilder/nginx-proxy#313]
I have a warning message when pulling the nginx-proxy.
Do you have any idea about this problem?

```
Status: Downloaded newer image for nginx:latest
Pulling nginx-proxy (jwilder/nginx-proxy:latest)...
Pulling repository docker.io/jwilder/nginx-proxy
Status: Downloaded newer image for jwilder/nginx-proxy:latest
docker.io/jwilder/nginx-proxy: this image was pulled from a legacy
registry.  Important: This registry version will not be supported in future vers
ions of docker.
```

**Comment by thomasleveil** [comment]
@ermaker what does `docker version` shows on your machine?

**Comment by thaJeztah** [comment]
I've seen this happen occasionally, I think it happens if there's a network hiccup and the registry V2 endpoint takes too long to respond, in that case docker automatically switches to the V1 registry

**Comment by ermaker** [comment]
@thomasleveil , @thaJeztah 

My docker version is attached blow (It might be the latest version).
I think @thaJeztah 's idea is right, so I close this issue.

Thank you!

```sh
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
