### ISSUE TITLE
HypriotOS / Raspberry

### ISSUE THREAD

**Issue by rgarrigue** [jwilder/nginx-proxy#315]
Hi guys

I'm trying to get the container to work on my raspberry pi 2. I'm getting errors about can't run container, most likely that's an arch issue. Anyone with a similar experience? @jwilder do you think this could be provided on docker's hub ?

Thanks & regards

**Comment by md5** [comment]
@rgarrigue The `jwilder/nginx-proxy` image on Docker Hub is built using the Automated Builds feature, which currently only support x86_64.

This issue tracks the addition of other architectures for Docker Hub automated builds: https://github.com/docker/hub-feedback/issues/427

**Comment by rgarrigue** [comment]
Thanks for the intel. 

So, how should I do that meanwhile ? Get all the intermediate images' Dockerfile, rename them, edit `FROM` field and build my own setup I guess ?

**Comment by md5** [comment]
Are there ARM builds of `nginx`? I don't see any in the Nginx `*.deb` repository at http://nginx.org/packages/mainline/debian/

**Comment by rgarrigue** [comment]
Most likely yes. You can find some rpi-nginx and a couple of armv7-nginx
container on hub.docker.I'm gonna try whenever I can.

2015-12-15 9:30 GMT+01:00 Mike Dillon <notifications@github.com>:

**Comment by djmaze** [comment]
@rgarrigue, @md5: I built armhf images for both [nginx](https://hub.docker.com/r/armhfbuild/nginx/) and [nginx-proxy](https://hub.docker.com/r/armhfbuild/nginx-proxy/). (The base image used is [armhfbuild/debian](https://hub.docker.com/r/armhfbuild/debian/).)

I also set up nightly builds, so the images should stay up-to-date with the latest code changes. No version tags yet.

**Comment by md5** [comment]
:+1:

**Comment by rgarrigue** [comment]
Thanks @djmaze, I'm gonna try this as soon as I get some free time.

Closing the ticket as it should be ok for me :)

**Comment by djmaze** [comment]
@md5, @rgarrigue I just realized I promised a bit too much with the nightly builds. Will have to adjust the build process for that to work.

**Comment by Brain-Gamer** [comment]
I tried to use this container on my raspberry pi 3 but it wouldn't work..
So I compiled it myself. I needed to make many changes in the dockerfile but it works now.
You can have a look at it [here](https://hub.docker.com/r/braingamer/nginx-proxy-arm/)
Would be great if you could support arm out of the box

**Comment by HelloEdit** [comment]
I allow to restart the debate, a Dockerfile.rpi would be extremely useful out of the box!

**Comment by snodnipper** [comment]
It would be great if nginx-proxy was [multi-arch](https://blog.docker.com/2017/11/multi-arch-all-the-things/) similar to the official images.

_Why the excitement with arm processors?  Because we might be running the [next generation financial systems on things like raspberry pi nodes](https://github.com/Stadicus/guides/blob/master/raspibolt/README.md)...and it would be great to have an awesome proxy image on those nodes!_ 😜
