### ISSUE TITLE
Automatic valid SSL Creation with https://letsencrypt.org/

### ISSUE THREAD

**Issue by philkunz** [jwilder/nginx-proxy#326]
Since "Let's Encrypt" is now in public beta, nginx-proxy would be a really nice place to automatically fetch valid SSL certs.

Domain Validation is done by providing a special file at the related domain.

**Comment by thaJeztah** [comment]
see this issue; https://github.com/jwilder/nginx-proxy/issues/274

**Comment by philkunz** [comment]
Ah, ok, thanks! I'm closing this one :)
