### ISSUE TITLE
Can't customize 502 error page

### ISSUE THREAD

**Issue by ManuelGysin** [jwilder/nginx-proxy#329]
Hello

I tried to adjust the template to support customized error pages:

```
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        error_page 502 /50x.html;
        return 503;
}
```

```
server {
        server_name {{ $host }};
        listen 80 {{ $default_server }};
        access_log /var/log/nginx/access.log vhost;
        error_page 502 /50x.html;
```

But it seems not to work correctly, I'm still getting '502 Bad Gateway'.
Any ideas?

Thanks
Manuel

**Comment by kevinsimper** [comment]
It is unclear of what you actually did. Can you explain it in another way?

**Comment by graphnode** [comment]
Check the issue #275 
Basically, because of nginx shenanigans, you need the `return 503;` line inside a `location /`.
