### ISSUE TITLE
https://www.ssllabs.com/ssltest/analyze.html - I get a B-rating only

### ISSUE THREAD

**Issue by freiit** [jwilder/nginx-proxy#330]
I have tried different options and settings to get rid of the 'weak Diffie-Hellman (DH) key exchange parameters', but with no success.
Can anyone help me out and maybe make the setting the default?

**Comment by md5** [comment]
Did you try this: https://github.com/jwilder/nginx-proxy#diffie-hellman-groups?

**Comment by freiit** [comment]
Did this
    openssl dhparam -out certs/domainname.dhparam.pem 2048
and it worked :)

Thanks!
