### ISSUE TITLE
SSL Lets encrypt - chained certificate

### ISSUE THREAD

**Issue by joschua011** [jwilder/nginx-proxy#331]
I have been using this image for a while now and it works really well, great work!

However i have run into an issue, i am trying to use this as a reverse proxy with SSL certificates from letsencrypt.org, so i copied the certs generated by letsencrypt to the cert folder and it works as expected, on a desktop browser the website works with ssl encryption, no problem here.

However mobile devices throw a invalid certifacte warning because they need the full certificate chain to check the cert, how would i add the full chain for one specific domain only?

Thanks for any help!

**Comment by kerongon** [comment]
I had the same problem. Just copy the fullchain.pem and rename it domain.com.crt like you did with the cert.pem.

**Comment by md5** [comment]
@kerongon Is right. Nginx expects the full chain to be in a single file. See the docs here: http://nginx.org/en/docs/http/configuring_https_servers.html#chains

**Comment by joschua011** [comment]
Thanks guys, overlooked this.closed.
