### ISSUE TITLE
kubernetes: Any support planned?

### ISSUE THREAD

**Issue by ManuelGysin** [jwilder/nginx-proxy#336]
Hello

Is it planned to support kubernetes in the future? I did some testing and it seems not to work with kubernetes.

Greets
Manuel

**Comment by kevinsimper** [comment]
Kubernetes has built in load balancer and it is also using a another api, so any support would not be likely.

**Comment by dgdosen** [comment]
Just out of curiosity - why would one use this nginx-proxy and kubernetes together?  I kind of feel this (nginx-proxy) gives you some of the same capabilities that you'd get from kubenetes.  Kind of like kubernetes light.  Would you agree? 

I kind of think nginx-proxy is the gateway drug to kubernetes :)  You kind of test the water and then you want more.   Then you're ready to use multiple hosts as well.  Somebody please correct me if I'm wrong.

**Comment by evaldasou** [comment]
nginx proxy has some features kubernetes services/loadbalancers does not have.
even simple proxy header manipulation which is required for me to work on Kubernetes:
               proxy_set_header X-ProxyScheme "http";
               proxy_set_header X-ProxyHost $http_host;
               proxy_set_header X-ProxyPort 80;
               proxy_set_header X-ProxyContextPath "";

How would I achieve the same on Kubernetes? As far as I know I need nginx somewhere in the middle...

**Comment by cnaslain** [comment]
I did not dig the code, but 1/ does nginx-proxy uses docker inspect to find VIRTUAL_HOST, LETSENCRYPT_HOST, LETSENCRYPT_EMAIL... environment variables or 2/ does it parses the docker-compose file?
If 1/ maybe it could works on k8s?... if 2/ it's dead :-(

Anyway; it would be great to have it works on k8s too ^
