### ISSUE TITLE
Is it possible to let a certain proxy server only serve a certain group of containers based on the port of proxy server?

### ISSUE THREAD

**Issue by qazbnm456** [jwilder/nginx-proxy#340]
As titled, I an gonna start several proxy servers with different ports on my host, and I want to start several containers which are the same that can be forwarded to depending ports of proxy servers. 

For instance, I have two proxy servers listening on port 80 and 81, and I start two same containers with same VIRTUAL HOST. Is it possible that I can access each container depenging the port that proxy server listened. I thought maybe adding an another env variable and modifing some template code might do the work? Or is there any better solution?

Hope that you can understand the situation I described ;(

**Comment by qazbnm456** [comment]
After I modify the template code... Problem solved :)

**Comment by jwilder** [comment]
This might be possible by running multiple `nginx-proxy` containers and attaching them to separate networks.

**Comment by roba91** [comment]
How should it work? I guess all `nginx-proxy` instances will see all containers staring with env var `VIRTUAL_HOST` set. Am I wrong?
