### ISSUE TITLE
[Proposal] Change error code 503 for non-usable SSL certs

### ISSUE THREAD

**Issue by schmunk42** [jwilder/nginx-proxy#341]
As described in https://github.com/jwilder/nginx-proxy#how-ssl-support-works you get a 503 if your SSL cert is not usable, eg. you have a default cert, but none for the currently requested virtual-host.

This is a bit confusing IMHO, because you also get a 503 error, when a virtual-host does not exists at all.

I looked through the list of [HTTP error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), but there's none for the described case. But what's about `421`.

> The 421 (Misdirected Request) Status Code

>   The 421 (Misdirected Request) status code indicates that the request
>   was directed at a server that is not able to produce a response.
>   This can be sent by a server that is not configured to produce
>   responses for the combination of scheme and authority that are
>   included in the request URI.

via https://tools.ietf.org/html/rfc7540#section-9.1.2

**Comment by jwilder** [comment]
Sounds reasonable, but that RFC says that status code must not be returned by proxies.

500 or 502 might work though.

**Comment by schmunk42** [comment]
Oh :) thank you for noticing. I'd say 500 is fine, it's easy to customize. I was just debugging SSL with fresh template, PR upcoming...
