### ISSUE TITLE
Custom Headers not being forwarded during the Rest Request

### ISSUE THREAD

**Issue by mrvini** [jwilder/nginx-proxy#345]
Hi All,

I am faced with an issue when trying to execute rest request with the custom header. Once request getting proxied to the container, those headers getting stripped. What I am doing wrong?

I have the following setup

nginx-proxy
```
docker run -d --name nginx-proxy \
        -p 80:80 -p 443:443\
        --restart=always \
	-v /home/test/config/ssl:/etc/nginx/certs:ro \
        -v /var/run/docker.sock:/tmp/docker.sock:ro \
        jwilder/nginx-proxy
```
api container
```
docker run -d --name api -p 8181\
    --restart=always \
    --link db --link redis  \
    -e VIRTUAL_PORT=8181 \
    -e VIRTUAL_PROTO=https \
    -e VIRTUAL_HOST=api.test.com \
    -v /home/test/web/ \
    -w /opt/web/ \
   node:4.2.3 \
    bash -c 'pm2 start util/pm2/local.json && pm2 logs --timestamp --lines 0'
```

When I make REST request to the api.test.com, my custom headers and one standard one not being forwarded, headers are "access_token" and "Content-Type"

I've tried creating proxy.conf file and added ```proxy_pass_request_headers on;```, but that did not help

any advice?

**Comment by wader** [comment]
Is the header exactly `access_token: <some token>`? If so i'm guessing it's because underscore is not allowed in header names. See [underscores_in_headers](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers) for how to enable it anyway. But i would recommend to rename it.

**Comment by mrvini** [comment]
@wader, thanks for the hint, i'll try that and will keep you posted. how about Content-Type?

**Comment by wader** [comment]
Content-Type removed or replaced?

**Comment by mrvini** [comment]
yep, I am not even seeing Content-Type on the API server, 

this is my request headers

when I make request to  https://api.test.com i send this header
```
Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
access_token: xyzbkjsdlkfjf
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

and thats what I get on the server

```
 host: 'host: 'api.test.com',
 'x-real-ip': '172.17.0.1',
  'x-forwarded-for': '172.17.0.1',
'x-forwarded-proto': 'https',
   'content-length': '0',
  origin: 'chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo'
``

However when I make same request to https://api.test.com:32768, i am getting different headers

```
host: 'api.test.com:32768',
connection: 'keep-alive',
   'content-length': '0',
 origin: 'chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo',
 access_token: 'xyzbkjsdlkfjf',
'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36',
'content-type': 'application/json',

```

I must have doing something wrong

**Comment by wader** [comment]
Hmm weird, is this a HEAD request? can you do "copy as curl" in chrome etc?

**Comment by mrvini** [comment]
Thank you @wader for quick responses. You are totally right about access_token header, no dice for me, I've finally re implemented the solution to use "access-token", everything seems to work. 

curl did helped me to fix it completely in my code. I was using Chrome client to issue rest request and that one for some reason was not passing "Content-Type" when "access_token" header is sent first.

Anyway, thanks to you, everything is identified and fixed now, Thanks again for such a great product!

**Comment by wader** [comment]
Glad you fixed it :+1: but weird about the Content-Type hmm
