### ISSUE TITLE
Allow self-signed certificates

### ISSUE THREAD

**Issue by athyuttamre** [jwilder/nginx-proxy#346]
I'm trying to use this locally, and would appreciate the ability to use self-signed certificates, perhaps with an environment variable that explicitly allows them.

In particular, it should work for `localhost` as well as other domains, say `myapp.dev` (the latter I have to use for other requirements, and would edit my hosts file for.)

**Comment by jwilder** [comment]
It already supports this. See the README for how to setup SSL support.

**Comment by athyuttamre** [comment]
@jwilder thanks for the response. I get a 503, the app doesn't launch. Should I be using self-signed certs that have a common name `localhost`?

**Comment by athyuttamre** [comment]
Whoops, sorry, got it!

I just had to generate self-signed certs for the local domain that I wanted. For others' reference, i went to http://selfsignedcertificates.com/, entered `myapp.dev`, and downloaded the appropriate cert and key.
