### ISSUE TITLE
Values to use for HTTP_PROXY and HTTPS_PROXY

### ISSUE THREAD

**Issue by athyuttamre** [jwilder/nginx-proxy#347]
I'm running a Meteor app in a container behind this proxy, and am running into some trouble. Meteor needs the variables `HTTP_PROXY` and `HTTPS_PROXY` set for it to handle connections properly.

Here's the reference doc: https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy.

Here's the error I get from Meteor:

```
root@72ba091b11a4:/app# meteor update 
Unable to update package catalog (are you offline?)
                                              
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:  https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
                                              
This project is already at Meteor 1.2.1, the latest release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: unknown package in top-level dependencies: athyuttamre:accounts-saml2
```

What values should I be using for these environment variables?

**Comment by athyuttamre** [comment]
@jwilder would appreciate any help! :D

**Comment by wader** [comment]
I have no experience with meteor but reading the wiki article it seems to be about the meteor command line tools and not the server. So is this because the container does not have internet access or maybe the network the host is connected to is behind a proxy?

**Comment by athyuttamre** [comment]
Thanks @wader!

The container has network access, I'm able to `curl http://google.com` for example. However, it can't access some sites, such as `https://packages.meteor.com`, and the known reason is that this happens when Meteor runs behind a proxy. Their solution is to set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

The host (my laptop) also has internet access, and isn't behind a proxy.

From what I read, these environment variables are not Meteor-specific, but are recognized by other command line tools too. I'm just not sure how to set them when running `jwilder/nginx-proxy`.

**Comment by athyuttamre** [comment]
But you're right, the server I'm trying to access has no issues. It's Meteor that needs these variables to make those specific connections.

**Comment by wader** [comment]
You can set environment variables for the container when starting it using `docker run -e HTTP_PROXY=...`. But `HTTP_PROXY` is usually for specify which HTTP client proxy to use, and pointing it to a nginx-proxy seems weird. Maybe i'm misunderstanding something how meteor works.

**Comment by athyuttamre** [comment]
Hmm, it makes sense that `HTTP_PROXY` is for when the client is behind a proxy, such as a corporate firewall. Meteor works fine on my host machine though (Mac OS X).

Is it possible the nginx-proxy is interfering with client connections Meteor is making?

**Comment by wader** [comment]
It shouldn't interfere. The only thing I can think of is if meteor uses the same environment variables (VIRTUAL_HOST etc) but that is not the case right?
Is is possible to run `meteor update` in debug or verbose mode?

**Comment by athyuttamre** [comment]
Pretty sure it doesn’t use those variables. Unfortunately can’t run in debug or verbose mode. :/

**Comment by athyuttamre** [comment]
Okay, this is extremely strange.

To give you more context, I've been running Meteor as part of a fork of `meteorhacks/meteord`, a container for running Meteor apps. I'm able to open a `bash` session in the container and run `meteor update`, but it doesn't work when I'm running it as part of a script.

Either way, I'm convinced it has nothing to do with `nginx-proxy` now. Thanks so much @wader!

**Comment by wader** [comment]
No problem. Yeah that is strange but glad you could work around it :+1:
