### ISSUE TITLE
Not receiving external requests

### ISSUE THREAD

**Issue by athyuttamre** [jwilder/nginx-proxy#351]
I'm running Docker on a Debian server, and none of the external requests are being received by the nginx proxy.

The container is running normally, and `curl mydomain.com` and `curl localhost` returns something (either a 503 or my app, but at least an HTML page.)

But any requests I make to the public IP address or the DNS just hang indefinitely in the browser. What could be wrong?

**Comment by wader** [comment]
Some firewall dropping the packets on the way? does any other kind of traffic work, ssh, ping etc?

**Comment by athyuttamre** [comment]
Ping and curl is working. I tried running other servers without nginx-proxy and they seem to be failing too.
So I guess it's not related to this proxy, but any other thoughts on what might be the reason?






On Wed, Jan 27, 2016 at 10:21 AM -0800, "Mattias Wadman" <notifications@github.com> wrote:












Some firewall dropping the packets on the way? does any other kind of traffic work, ssh, ping etc?

**Comment by wader** [comment]
Ok, sounds like firewall or maybe routing problem. Maybe tcpdump or traceroute can give some clue?

**Comment by athyuttamre** [comment]
Thank you, I'll try!

**Comment by athyuttamre** [comment]
Got it working, was a firewall issue. Thanks @wader!

**Comment by wader** [comment]
@athyuttamre Ok :+1:
