### ISSUE TITLE
Modding code for Nginx access to private S3 buckets?

### ISSUE THREAD

**Issue by vfulco** [jwilder/nginx-proxy#352]
Still a noob at Nginx and devops in general.  Have a perfectly running setup on AWS EC2 with multiple containers.  Need to provide password protected individualized access to S3 buckets (really files within) and mulling over using Nginx as a proxy as seen in the following links.  

http://dodwell.us/using-nginx-to-proxy-private-amazon-s3-web-services/

https://coderwall.com/p/rlguog/nginx-as-proxy-for-amazon-s3-public-private-files

Do any other users have experience with this?  Is there something obvious I am missing that will upset the apple cart?  Not looking for anyone to do work for me; just looking for any cautionary/successful stories if around.  TIA.

V.

**Comment by jwilder** [comment]
This project is meant for automatically creating nginx proxy configurations for docker containers.   Not really designed for S3 proxying.
