### ISSUE TITLE
auth_basic fails with (21: Is a directory)

### ISSUE THREAD

**Issue by sxamit** [jwilder/nginx-proxy#357]
I created a directory /etc/nginx/htpasswd/my.hostname.com , created .htpasswd file
ran the docker with - 
`docker run -d -p 80:80  -v /var/run/docker.sock:/tmp/docker.sock:ro -v /etc/nginx/htpasswd:/etc/nginx/htpasswd jwilder/nginx-proxy`

when cURL-ing the host I receive - 

> 2016/02/08 08:39:44 [crit] 26#26: *1 pread() "/etc/nginx/htpasswd/my.hostname.com" failed (21: Is a directory), client: 32.42.29.204, server: my.hostname.com, request: "POST /something HTTP/1.1", host: "my.hostname.com"

I changed the nginx.tmpl file -
from
 `auth_basic_user_file    {{ (printf "/etc/nginx/htpasswd/%s" $host) }};`
`auth_basic_user_file    {{ (printf "/etc/nginx/htpasswd/%s/.htpasswd" $host) }};`

and now it seems to work fine. Am I doing something wrong? or is it a bug in the template?

(running docker 1.9.1 and jwilder/nginx-proxy:latest built 5 days ago)

**Comment by wader** [comment]
Im pretty sure the htpasswd file is suppose to be named `/etc/nginx/htpasswd/$VIRTUAL_HOST`. The readme is a bit confusing "... you have to create a file named as its equivalent VIRTUAL_HOST variable on directory /etc/nginx/htpasswd/$VIRTUAL_HOST". Maybe change the last part to "... in directory /etc/nginx/htpasswd"?

**Comment by sxamit** [comment]
Thanks you are right - the file name is VIRTUAL_HOST (for example - myhost.com) inside directory /etc/nginx/htpasswd/

and run docker with - 
`docker run ... -v /etc/nginx/htpasswd:/etc/nginx/htpasswd`
