### ISSUE TITLE
Templating fails when using networks - no upstream :80

### ISSUE THREAD

**Issue by rwrnet** [jwilder/nginx-proxy#358]
With docker-compose.yml version 2, docker-compose generates isolated networks by default.

If this applies, IPAddress of the proxied container is not found anymore, which results in missing upstream due to resulting configuration:

```
upstream container {
                        # container
                        server :80;
}
```

It looks like, with networks enabled ```docker inspect``` does report IPAddress not under NetworkSettings but under NetworkSettings.Networks.{project_default}.IPAddress. I guess, this affects docker.gen here.

I had to fix the issue quickly on my side (switching back to docker-compose.yml version 1), so I don't had time to document all the findings. Let me know, if the issue cannot be easily reproduced, then I would look into setting up a generic example.

**Comment by josteinbf** [comment]
Could this be the same issue as #304 ?

**Comment by rwrnet** [comment]
You are right. I was briefly checking the issues, and missed it, as I assumed, it was kind of introduced with compose.yml 2, where issues shouldn't had been older than mid of January. Thanks for pointing out.
