### ISSUE TITLE
Added VIRTUAL_ALLOW to limit access to container

### ISSUE THREAD

**Issue by itsafire** [jwilder/nginx-proxy#36]
I did a change to nginx.tmpl to provide a VIRTUAL_ALLOW environment variable to limit access to containers. Adding -e VIRTUAL_ALLOW=10.1.1.0/24,10.1.3.55 will result in:

allow 10.1.1.0/24;
allow 10.1.3.55;
deny all;

**Comment by md5** [comment]
I believe this can be closed since #106 was merged. See the README for instructions: https://github.com/jwilder/nginx-proxy/blob/master/README.md#custom-nginx-configuration

**Comment by moul** [comment]
Hi, even if #106 lets us do the equivalent of this PR, 

I think this PR is a better solution when you want to handle all the configuration from the proxyfied container with environment variables.
It's a little by annoying to put some configuration in the proxyfied container and update a file on the host.
particularly when you use nginx-proxy as *the* host nginx and want to just handle new containers without thinking about it

What do you think about keeping #106 to handle every cases, and use this PR as an additional method ?

**Comment by aimxhaisse** [comment]
:+1:

**Comment by piront** [comment]
:thumbsup:

**Comment by md5** [comment]
@moul You guys might want to check out the discussion in #134. Two possible options discussed there are a JSON-formatted `VIRTUAL_HOST_CONFIG` variable or a naming convention for variables starting with `NGINX_PROXY_*` to expose any (or perhaps just most) Nginx settings.

**Comment by thaJeztah** [comment]
Perhaps labels are an option too; e.g. `org.jsonwilder.nginx-proxy.something=val`

**Comment by md5** [comment]
@thaJeztah Thanks for the reminder about labels. I haven't gotten around to playing with them yet, unfortunately.

Looks like label support was added to `go-dockerclient` here: https://github.com/fsouza/go-dockerclient/commit/bd32742a065748632a860c9ffd8adf42cc4e140f

**Comment by md5** [comment]
This is relevant too: https://github.com/jwilder/docker-gen/issues/81
