### ISSUE TITLE
how to setup upload file-size?

### ISSUE THREAD

**Issue by zhukainet** [jwilder/nginx-proxy#376]
Hello,
I need to upload some attachments in my program, but if file size is large than 1024KB, the server will return error code 413. The error that means file size is too large.
My Dockerfile like this:

FROM jwilder/nginx-proxy
RUN echo "client_max_body_size 50m;" >>  /etc/nginx/nginx.conf

But it's not work.
Please help me to solve it, thanks!

**Comment by wader** [comment]
Have a look at #233 #161

**Comment by zhukainet** [comment]
Please see code in this paragraph:
https://github.com/schmunk42/nginx-proxy#proxy-wide

And the question can be solve.
