### ISSUE TITLE
Reload nginx on configuration change

### ISSUE THREAD

**Issue by TheBlusky** [jwilder/nginx-proxy#377]
Hi !
I don't know if it's already possible.
But any idea how to "watch" the "/etc/nginx/vhost.d" folder, and if any file change, nginx is automaticly reloaded / restart,
I often change configuration files, and each time I perform a change, I have to restart the whole container.
Thanks !

**Comment by mjaverto** [comment]
@TheBlusky you didn't find an answer to this did you?

**Comment by TheBlusky** [comment]
Sorry, I didn't find any "clean" way to do this, so I used Inotify (https://en.wikipedia.org/wiki/Inotify) as a workaround to resolve my issue.
Hope that can help you.

**Comment by mjaverto** [comment]
@TheBlusky I realize now I didn't the same requirement as you, I was trying to just make sure my nginx.tmpl was being regenerated and I also found something in the comments here:

http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/

> docker-gen detects when a new container with the same virtual host is started and regenerates the nginx proxy config and reloads nginx. When that happens both containers are part of the reverse proxy config. When you stop the old container, docker-gen regenerate the config and reloads nginx again.

**Comment by ryneeverett** [comment]
> So for me, I just needed to stop/start another container for the new template to be picked up.

Alternately, send docker-gen a SIGHUP, per jwilder/docker-gen/pull/147.

`docker kill --signal=HUP docker-gen`

**Comment by artm** [comment]
Our solution: 

0. the app container is running already
1. we run a `rm /etc/nginx/vhost.d/${VIRTUAL_HOST}*` with a docker exec on the app container.
2. we run the configuration script that generates the new vhost file(s) wit `docker run` on the copy of the app container (with `VIRTUAL_HOST` defined).

When the (2) starts up there are no config files, the `/etc/nginx/conf.d/default.conf` is regenerated without the includes. When (2) exits there are config files and the `/etc/nginx/conf.d/default.conf` is regenerated with the includes. 

These steps are integrated into our deployment solution.

**Comment by jesteves** [comment]
A few moments ago we've just restarted our proxy after putting some settings under `vhost.d` for one or our virtual hosts.

We issued a `nginx -s reload`, but nothing happened.  So went with `nginx -s stop` which stopped the container and then, after `docker start` we saw changes applied.

While checking the logs we saw the reason:

```
dockergen.1 | 2017/06/09 17:28:26 Running 'nginx -s reload'
dockergen.1 | 2017/06/09 17:28:27 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

So, we're guessing next time we'll need to `touch default.conf` before `nginx -s reload`.

**Comment by jwilder** [comment]
@jesteves You need to send a `sighup` signal to `nginx-proxy` container or `docker-gen` container (if running separate containers) to trigger regeneration of the template.  Just putting files in the directly will not include them automatically because the template checks for their existence before adding the appropriate `include` directives.

**Comment by jwilder** [comment]
To the answer the OP questions, there is no support for watching a dir and reloading nginx automatically.  You can send a `signup` to trigger a regeneration/reload of nginx config when something has changed, but you'd need to use something else to detect the change or trigger the reload.  There are other filesystem watching tools out there that could be used to do this though.
