### ISSUE TITLE
Getting 503 after restarting from docker compose

### ISSUE THREAD

**Issue by kiangj** [jwilder/nginx-proxy#381]
Got everything setup and running correctly, and was able to go to the correct container from my browser.  However once I do a docker-compose down && docker-compose up, I can no longer access the page from my browser, all I get is a 503 Service Temporarily Unavailable and this on the docker-compose logs

`nginx-proxy_1 | nginx.1    | local-cart-api.jkiang.com 192.168.99.1 - - [04/Mar/2016:18:51:31 +0000] "GET /favicon.ico HTTP/1.1" 503 614 "http://local-cart-api.jkiang.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36"`

Here is my docker-compose.yml
`nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

coordinator:
  image: jkiang/coordinator
  environment:
    - VIRTUAL_HOST=local-coordinator.jkiang.com
    - jkiang_ENV=docker-coordinator
  volumes:
    - /var/www/apps
    - ./logs/:/var/log/jkiang

cart-api:
  image: jkiang/apache2
  environment:
      - VIRTUAL_HOST=local-cart-api.jkiang.com
      - jkiang_ENV=docker
  volumes:
    - /Users/jkiang/PhpstormProjects/cart_api:/var/www/html
    - ./src/apache_config/vhosts/cart-api.conf:/etc/apache2/sites-enabled/000-default.conf
  links:
    - coordinator
  volumes_from:
    - coordinator

api:
  image: jkiang/apache2
  environment:
      - VIRTUAL_HOST=local-api.jkiang.com
      - jkiang_ENV=docker
  volumes:
    - /Users/jkiang/PhpstormProjects/api:/var/www/html
    - ./src/apache_config/vhosts/api.conf:/etc/apache2/sites-enabled/000-default.conf
  links:
    - coordinator
  volumes_from:
    - coordinator
`

I looked in /etc/nginx/conf.d/default.conf, and see that the upstream for "local-cart-api.jkiang.com" is no longer there.  But local-api.jkiang.com is still there, so I used my browser to test, and was able to get to the page.  However, after the next docker-compose restart, local-api.jkiang.com upstream is also gone from the config file.

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
