### ISSUE TITLE
Help with flask

### ISSUE THREAD

**Issue by microspace** [jwilder/nginx-proxy#384]
I try to run simle flask app behind nginx-proxy
I use this repo https://github.com/danriti/gunicorn-flask
I run container with this command:
`docker run -d -p 5000:80 -e VIRTUAL_HOST=mydomain.com danriti/gunicorn-flask`
In browser I get 503 error. Please help me!

**Comment by wader** [comment]
How do you start `nginx-proxy` and with what config?
Can you paste the generated config? `docker exec <nginx-proxy-container-id> cat /etc/nginx/conf.d/default.conf`

**Comment by microspace** [comment]
`docker run -d --name nginx-reverse-proxy -p 80:80 -p 443:443 -v /var/run/docker.sock:/tmp/docker.sock:ro --restart=always jwilder/nginx-proxy `
Here is nginx.conf
https://gist.github.com/microspace/5393079aabaf1d6a09be

**Comment by wader** [comment]
Thanks,
Does the docker logs for nginx-proxy say anything interesting?
How do you start the mydomain2.ru container?
Is the 172.17.0.3:80 address correct for the mydomain2.ru container?
Maybe good to make sure that mydomain2.ru container actually response on port 80. Try from another container and by exec:ing into it.

**Comment by microspace** [comment]
Thank you for your help! Issue is over. Your last post was very helpful!
This is what I've done:
1) git clone danriti/gunicorn-flask
2) in gunicorn_config.py changed bind = "0.0.0.0:5000" to bind = "0.0.0.0:80"
3) build container 
4) `docker run -d -p :80 -e VIRTUAL_HOST=domain2.ru myflask`
I'm not sure, did I setup ports correctly?

**Comment by wader** [comment]
Ah nice :+1:
Yes i guess the change to port 80 probably fixed it. Do you know if there a `EXPOSE 80` in the Dockerfile you use? nginx-proxy will proxy to the exposed port. I think you can skip `-p :80` that will publish port 80 on the container to a random port on the host, that is not needed by nginx-proxy as it uses the internal docker network.
