### ISSUE TITLE
www and non-www

### ISSUE THREAD

**Issue by microspace** [jwilder/nginx-proxy#385]
I've setup small site behind nginx-proxy.
I can access site via domain.com, but can't access via **www**.domain.com.
I've setup A record for domain name
``` 
@	A	1.2.4.6	 			

www	A	1.2.4.6	
```

Also I start container with wildcard host like his: `VIRTUAL_HOST=*.domain.com,domain.com`
Isn't this enough?
Should I write redirect rule in nginx.conf?
This is part of nginx.conf
```
 server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
stream *.domain.com {
			# gigantic_banach
			server 172.17.0.5:80;
}
server {
	server_name *.domain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://*.domain.com;
	}
}

upstream domain.com {
			# gigantic_banach
			server 172.17.0.5:80;
}
server {
	server_name domain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://domain.com;
	}
}
`

**Comment by wader** [comment]
Anything interesting in the nginx-proxy log? do you see the request?

**Comment by microspace** [comment]
Yes, there are requests. server responds with 200 on www.domain.com and with 503 on .domain.com
Here is link to  [screenshot](https://cloud.mail.ru/public/4LkC/uxhswvtii)

**Comment by wader** [comment]
Are you sure the 404 is from nginx-proxy and not the webapp container web server? try something like `docker run --rm tutum/curl curl -v -H "Host: www.domain.nu" http://$(docker inspect -f '{{.NetworkSettings.IPAddress}}' <container-id-for-webapp>):80`

**Comment by microspace** [comment]
404 is for favicon.ico
I've solved this problem. There was a small typo at launching the container.
