### ISSUE TITLE
“413 Request Entity Too Large” Error

### ISSUE THREAD

**Issue by 9cat** [jwilder/nginx-proxy#39]
base on:  http://stackoverflow.com/questions/10454850/413-request-entity-too-large-error-rails-3-2-passenger-phusion?rq=1

you should add:

client_max_body_size 4g;
in http section in nginx.conf file.

**Comment by md5** [comment]
I believe this can be closed since #106 was merged. See the README for instructions: https://github.com/jwilder/nginx-proxy/blob/master/README.md#custom-nginx-configuration

**Comment by kamil-kielczewski** [comment]
problem still exist :( (only <2MB file upload is allowed)

**Comment by hk0i** [comment]
I'm not super knowledgeable about nginx, is that `nginx.tmpl` usable as-is? When I drop in the template under my `vhosts.d` I get a 503. I see that there's some kind of templating going on with the `{{ }}` but I don't know if that's something from NGINX or something else. Either way I am not too sure why it's not working, I really just want to increase the `client_max_body_size` for my dev environment only and only for one particular vhost.

**Comment by kamil-kielczewski** [comment]
I have in past similar problem (in PHP, docker):
https://stackoverflow.com/q/44605469/860099

**Comment by hk0i** [comment]
Thanks! I wish I had seen that sooner. It's so succinct.

**Comment by egorpavlikhin** [comment]
> client_body_max_size 500M

Correct term is ``client_max_body_size``

**Comment by jasonheecs** [comment]
Run into this issue as well. I made a derived docker image that increases the max upload size to 10 MB: https://github.com/jasonheecs/docker-nginx-proxy
