### ISSUE TITLE
Question: Possibility to use this with PHPFarm

### ISSUE THREAD

**Issue by richardtape** [jwilder/nginx-proxy#392]
Hi,

Thanks for putting this together and maintaining it. It's a really, really useful resource.

I was investigating whether it was possible to use this as a way to allow me to put nginx in front of https://github.com/splitbrain/docker-phpfarm

PHPFarm exposes several ports for the different versions of PHP that it supports. i.e. hitting [docker-ip]:5053 uses PHP 5.3, [docker-ip]:5054 uses PHP 5.4 etc.

I've tried the following:

`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxydocker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

`docker run --rm -t -i -e VIRTUAL_HOST=test53.somedomain.dev -e APACHE_UID=$UID -v $PWD:/var/www:rw -p 8053:8053 splitbrain/phpfarm:wheezy`

and have `192.168.99.100 test53.somedomain.dev` in my `/etc/hosts` file

However, going to http://test53.somedomain.dev/index.html in the browser gives me a 502 Bad Gateway error from nginx

Going directly to `http://192.168.99.100:8053/` however, shows me the contents of an index.html file appropriately. and `http://192.168.99.100:8053/index.php` the appropriate PHP file (which I have outputting the PHP version and it's showing `PHP Version: 5.3.29` )

So, I've clearly misunderstood something somewhere. Any possibility of giving me a hint?

My goal is to have something like test52.somedomain.dev, test53.somedomain.dev, test54.somedomain.dev etc. which are using the appropriate PHP version.

**Comment by uptownhr** [comment]
Hi, I'm trying to understand the purpose of the PHPFarm docker image. Can you provide some use cases?

**Comment by richardtape** [comment]
Hi @uptownhr 
As a PHP Dev (stop laughing) the projects I work on are often deployed on a variety of shared hosting (stop crying) servers and as such I'm never 100% certain what version of PHP is being used. Therefore I need a way to easily test my codebase on different versions of PHP. (Also HHVM but that's a different game altogether)

PHPFarm allows me to do that. The docker container I linked to uses apache to serve different versions of PHP on different ports.

I mainly work within the WordPress world (stop groaning) and even at my day job we have multiple platforms which run on different versions of PHP across campus.

I'm in the process of building an open-source tool to allow folks to spin up an environment which will allow them to test their code on different versions of PHP (and there's a deployment part to it too, but that's irrelevant here). I'm hoping I can use nginx-proxy in front of PHPFarm to allow people to use a much cleaner URL for their testing (as well as actually testing on an nginx web server in general).

**Comment by uptownhr** [comment]
After reviewing your docker run command for phpfarm, I see that you are exposing 8053, is this a requirement? It might work if you remove the port expose.

**Comment by richardtape** [comment]
I've managed to get this working in a separate way using docker-compose, so I'm going to close this. For those interested it'll be up here: https://github.com/richardtape/testit
