### ISSUE TITLE
Can nginx-proxy be used to reverse proxy SMTP?

### ISSUE THREAD

**Issue by daryl-williams** [jwilder/nginx-proxy#400]
Subject pretty much says it all. I've seen aticles stating that nginx can act as a reverese proxy for SMTP traffic and I've been trying to get it to work with nginx-proxy so far unsuccessfully. Has any body tried this?

Regards,

Daryl

**Comment by md5** [comment]
This was discussed in #258. I'm not aware of anyone actually doing it.

**Comment by md5** [comment]
I will add that even the `ngx_mail_core_module` module that I mention in #258 doesn't appear to allow for "virtual hosting". There is no mention of domain names in its configuration docs. And although the docs mention proxying to a backend, it isn't apparent to me how that backend would be specified.

**Comment by daryl-williams** [comment]
Thanks for your replies. I'm surprised this isn't a more requested/desireable feature. It sounds like if the ngx_mail_core_module where complied into the nginx executable used by the nginx-proxy image that it might work. I guess I'll try looking into your suggestion about using a separate container for now.

Thanks again. Really love this image by the way, it's a great service!

**Comment by jwilder** [comment]
@daryl-williams You could always run `docker-gen` and a custom `nginx` container separately with a custom config too.  Going to close this because SMTP is not supported currently.

**Comment by daryl-williams** [comment]
Jason, Thaks for the information and suggestion. I'm going to try using the seperate nginx container and docker-gen and see how far I can get.
