### ISSUE TITLE
Forego binary is unavailable

### ISSUE THREAD

**Issue by barsteadr** [jwilder/nginx-proxy#403]
The docker build is failing on this line with a `503 Service Unavailable` error:

`RUN wget -P /usr/local/bin https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego`

FYI, the binary download [link](https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego) on the [forego repository](https://github.com/ddollar/forego) is also broken and gives this error:

```
An error occurred in the application and your page could not be served. 
Please try again in a few moments.
If you are the application owner, check your logs for details.
```
The links have been broken for at least 16 hours. I have registered an issue on the Forego project. For now is there a workaround?

**Comment by jwilder** [comment]
https://github.com/ddollar/godist/issues/1

**Comment by krknopp** [comment]
Is there a way around this?
