### ISSUE TITLE
Switching to docker-compose.yml V2 breaks nginx-proxy

### ISSUE THREAD

**Issue by elju** [jwilder/nginx-proxy#414]
Upon switching my `docker-compose.yml` to the V2 layout, nginx-proxy has stopped working. I poked around inside of the container and saw that inside of `/etc/nginx/conf.d/default.conf` there were upstreams like this:
```
upstream sub.hostname.org {
            # testservices_test_1
            server :4000;
}
```

It appears like nginx-proxy is no longer able to find the IP address for these containers, although I can't figure out what would be causing that. On reverting back to the V1 version of `docker-compose.yml`, everything fixed itself.

**Comment by wader** [comment]
Yes people are working on fixing it, see #304

**Comment by elju** [comment]
Oh great, thanks
