### ISSUE TITLE
change ssl_ciphers

### ISSUE THREAD

**Issue by La-source** [jwilder/nginx-proxy#428]
Hello

_I use a translator, sorry for my English._

I want to change the ssl_ciphers directive because when I test a domain on ssllabs.com I get the rank B for the following reason: `This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B` More info [here](https://weakdh.org/sysadmin.html)

I understand that for reasons of compatibility it is not necessarily possible. Will it be possible you however to help create an environment variable to indicate which result I want? (Allow a host by parameterization be good)

Tanks you

**Comment by jdoubleu** [comment]
How did you change the cipher directive, @La-source ?

**Comment by wader** [comment]
@jdoubleu you can fix the weak dh params by generating your own see https://github.com/jwilder/nginx-proxy#diffie-hellman-groups no need to change ssl_ciphers

To change ssl_ciphers you probably need to create your own derived Dockerfile and do som sed:ing etc.

**Comment by jdoubleu** [comment]
Yeah okay thanks.

Only looked for different cipher suites.
I'm using `jwilder/docker-gen` in combination with `nginx` now to have my own templates.

Thanks anyway
