### ISSUE TITLE
Let's encrypt integration

### ISSUE THREAD

**Issue by La-source** [jwilder/nginx-proxy#429]
Hello

_I use a translator, sorry for my English._

We can use certificates in the proxy, however, when a server supports multiple domain it is tedious to copy and rename the certificates one by one from `/etc/letsencrypt/live/<domain.tld>`.

It will be great to add volume letsencrypt pointing to the file and the proxy makes the connection automatically.

Tanks you.

**Comment by saesh** [comment]
Hey @La-source, you can use this [companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for letsencrypt integration.

**Comment by La-source** [comment]
Thank you very much, that exactly meets my needs :)

In addition it also meets my other issues #428, I thought that the assessment of a site certificate depended on proposed ciphers hence my request to modify them. As the companion answers this question is awesome.
