### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mmorejon** [jwilder/nginx-proxy#435]
Hi,

Your work is very good, but right now I get the message "503 Service Temporarily Unavailable " when I run the following command:

```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

Any suggestion?

**Comment by wader** [comment]
Probably need some more information to able to help. How did you start the other containers you want proxy to? environment variables, other config etc, docker-compose? what does nginx-proxy log?

**Comment by mmorejon** [comment]
Hi,
To start the container I use the following command:
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```
Like is the first time Docker pull the image and after initialize a new container with this image. I'm not using Docker Compose this time to start the process.

Best,

**Comment by wader** [comment]
Ok but you also have to run some other container at the same time with `VIRTUAL_HOST` set. Otherwise nginx-proxy wont have any thing to forward requests to.

What do you plan to use nginx-proxy for? it's not a normal HTTP proxy, it's a reverse HTTP proxy.

**Comment by mmorejon** [comment]
Ok, you are right, but in previous versions when I start the image without any other container the browser show me the Nginx default page. Maybe the behaviour has been changed and now I receive this message when I don't have any other container running.
The Nginx default page tells me the proxy is running correctly no matter others things.
The question is: Should I expect the message   "503 Service Temporarily Unavailable" if I don't have any other container running?

**Comment by wader** [comment]
Aha did not know that. I tried running without any proxied containers and i get the 503 error also.

**Comment by revolunet** [comment]
https://github.com/jwilder/nginx-proxy/issues/582#issuecomment-249425260

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
