### ISSUE TITLE
HTTP Connection header is not really cleared

### ISSUE THREAD

**Issue by julianxhokaxhiu** [jwilder/nginx-proxy#439]
Hi,

I'm having a question related to this line:

https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L31

Reading the related comment on top, you're saying that if we're not getting an `Upgrade` header, we just clear them. But in fact you're not clearing it, you're just throwing `Close`.

Is this on purpose? Actually this issue affects UI-for-Docker project. See https://github.com/kevana/ui-for-docker/issues/204

I tested it and if I patch that line like this:

```
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' ''; # before: '' close;
}
```

Then it works just fine. And it should exactly met the purpose of HTTP 1.1.

I'm just trying to understand the drawbacks of this, if any. Thanks in advance for any help!

**Comment by julianxhokaxhiu** [comment]
A MUCH better resolution imho is to always pass to the proxy the header sent from the client, so you don't have to manipulate literally nothing.

```
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' $http_connection; # before: '' close;
}
```

This one I think it's a perfect solution

**Comment by wader** [comment]
There seems to be some discussion about it in #46

**Comment by md5** [comment]
It's been a while since #46 and #49 were discussed and I'm not seeing that I provided any rationale besides deferring to the Nginx docs.

My guess is that the reason the Nginx docs suggest `close` is to avoid clogging up the proxy with long-running HTTP connections, but since the rest of that `map` statement is facilitating WebSockets that may not be a great rationale.

**Comment by julianxhokaxhiu** [comment]
Any update on this? I still see that it has not been fixed. Why?

**Comment by julianxhokaxhiu** [comment]
Fixed via https://github.com/jwilder/nginx-proxy/commit/124b8cd757c7d99c83048ea08b96722403c887b4
