### ISSUE TITLE
http2 

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#449]
So in my architecture I've nginx-proxy and nginx-webserver. Nginx-proxy relayes everything to nginx-webserver.

nginx-proxy is https and supports http2 but nginx-webserver listens on 80.

I'd like to move to http2, do I need to enable http2 for the second web server?

**Comment by wader** [comment]
Nope, then i think you already are doing http2. nginx-proxy will default talk http2 publicly if the client wants but the forwarded request internally to "nginx-webserver" will be unencrypted http (or https if `VIRTUAL_PROTO=https`). If you wan to verify you can bring up the network tab in chrome developer tools and see if the request has ":"-prefixed headers or open chrome://net-internals/#http2

But i wonder how tricky it would be for nginx to support http2 for proxy_pass. Im guessing in a couple of years there will be more and more http2 only webservers that one might want to proxy. Also some http2 server seems to be TLS only so to proxy that i guess you only use hostname (via SNI) or do MITM tricks.

**Comment by sandrodz** [comment]
Yes I checked so client <> nginx-proxy is http2 and nginx-proxy <> nginx-webserver is http1.

I get bad gateway when using VIRTUAL_PROTO=https

**Comment by wader** [comment]
When you did `VIRTUAL_PROTO=https` did your nginx-webserver container support https and have valid certs? check the nginx-proxy logs and you will probably see something useful.

**Comment by sandrodz** [comment]
yep looked through the logs, nginx-webserver doesn't have valid certs. I'm using nginx-letsencrypt-companion to generate certs. I should probably re-use them?

**Comment by wader** [comment]
Ah i see, yes. Not sure how to do that conveniently, maybe a shared volume somehow? also note that let's encrypt certs have quite short expire date (90 days i think) so your container needs to know when to reload them.

**Comment by sandrodz** [comment]
apparently nginx supports http2 without ssl. So I did

`80 http2;`

but instead of loading the page it downloads this:

```
0000 1204 0000 0000 0000 0300 0000 8000
0400 0000 0000 0500 ffff ff00 0004 0800
0000 0000 7fff 0000 0000 0807 0000 0000
0000 0000 0000 0000 01
```

**Comment by wader** [comment]
Hmm weird, where did you configure that, nginx-proxy or the proxied server? i guess `80 http2` will mean unencrypted http1 and unencrypted http2? is that the exact output or hex dump of the output?

**Comment by sandrodz** [comment]
weird indeed. I configured that in proxied server. I guess nginx-proxy doesn't know how to deal with it.

yes that's exact dump. looks like http2 header?

**Comment by wader** [comment]
and no `VIRTUAL_PROTO=https` for nginx-proxy? very weird with text hex dump as answer, do you know how is replying with that, nginx-proxy or the proxied, see any request to the proxied server in the nginx-proxy log?

**Comment by sandrodz** [comment]
nope, no vproto, since we don't do nginx <> nginx with ssl. I'm scanning logs, but don't see anything weird.

**Comment by wader** [comment]
Could this be it https://serverfault.com/questions/741191/nginx-with-http2-enabled-downloads-everything? seems chrome and firefox only support http2 over tls

**Comment by wader** [comment]
Seems to be the case, wikipedia says "Although the standard itself does not require usage of encryption,[22] most client implementations (Firefox,[23] Chrome, Safari, Opera, IE, Edge) have stated that they will only support HTTP/2 over TLS, which makes encryption de facto mandatory.[24]"

**Comment by sandrodz** [comment]
wait, client <> nginx-proxy use http2 and ssl. 

nginx-proxy <> nginx web server uses 80 and http2.

**Comment by wader** [comment]
I don't think `proxy_pass` supports http2 but i could be wrong. Does your proxied web server only speak http2? If you want to run a dummy proxied web server i've done something like before:
```
docker run -ti --rm --expose 80 -e VIRTUAL_HOST=<domain> debian:jessie sh -c "apt-get update && apt-get -y install netcat bsdmainutils && while true ; do nc -v -l -p 80 | hexdump -C ; done"
```

**Comment by sandrodz** [comment]
could this be an answer? http://stackoverflow.com/questions/34839292/how-to-forward-http-2-protocol-version-via-proxy

**Comment by wader** [comment]
Not sure, i think that will only add a header that client talks http2 to proxy-proxy but will still talk http1 to the proxied web server.

**Comment by wader** [comment]
Could you do a curl directly to the proxied server (not thru nginx-proxy) and see what happens? maybe test with and without `curl --http2`

**Comment by sandrodz** [comment]
http://serverfault.com/questions/765258/use-http-2-0-between-nginx-reverse-proxy-and-backend-webserver/765337#765337

its not possible with reverse proxy.

**Comment by wader** [comment]
Ok! thanks for the link, have been looking for discussion about it.
But what was the actual problem? proxied server only talked http2?
