### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by jmls** [jwilder/nginx-proxy#45]
is it possible to load balance as well with nginx-proxy ?

For example, I want to fire up 2 docker containers, and use them as a round-robin

-e VIRTUAL_HOST=foo.myapp.com:[1|2|..n]

which means that I have 2 foo.myapp.com hosts (1 & 2) 

would it be possible for nginx to then create the appropriate round-robin / load balancing config files ?

**Comment by pascalandy** [comment]
I confirm that LB works well.
