### ISSUE TITLE
OnlyOffice and nginx-proxy via SSL Cert not working correct

### ISSUE THREAD

**Issue by dboecker** [jwilder/nginx-proxy#452]
Hi everyone,

at first very much thanks to the author for this awesome plugin!

My Setup:
ubuntu 16.04 root-machine with onlyoffice via docker and nginx-proxy (including all dependencies)

So lets start with my issue, which i can't really solve (sitting in front of that around 12hours+):
I installed the Docker-Suite of OnlyOffice, which works absolutely flawless via HTTP without and with nginx-proxy. OnlyOffice without the proxy works as it has to be, but HTTPS with the nginx-proxy cause some errors with some (not all) JS- and/or CSS- and/or ICO-Files.

A little overview, what is working and what's not working:
OO HTTP (direct) => OK
OO HTTPS (direct) => OK
OO HTTP -> NRP HTTP => OK
OO HTTP -> NRP HTTPS => SINGLE FILE ERRORS (see attached error i.e.)
OO HTTPS -> NRP HTTPS => SINGLE FILE ERRORS (see attached error i.e.)

Some of my errors out of the docker log (`$ docker logs -f nginx-proxy`):
`nginx.1    | 2016/05/10 13:10:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: <CLIENT_IP>, server: foo.bar.com, request: "GET /discbundle/projects/javascript/PWIpMOuaLmhajOxFRYXnLg2.js?ver=264 HTTP/2.0", upstream: "http://172.17.0.2:443/discbundle/projects/javascript/PWIpMOuaLmhajOxFRYXnLg2.js?ver=264", host: "foo.bar.com", referrer: "https://foo.bar.com/"`

`nginx.1    | 2016/05/10 13:10:01 [warn] 31#31: *1 upstream server temporarily disabled while connecting to upstream, client: <CLIENT_IP>, server: foo.bar.com, request: "GET /discbundle/projects/javascript/PWIpMOuaLmhajOxFRYXnLg2.js?ver=264 HTTP/2.0", upstream: "http://172.17.0.2:443/discbundle/projects/javascript/PWIpMOuaLmhajOxFRYXnLg2.js?ver=264", host: "foo.bar.com", referrer: "https://foo.bar.com/"`

And my starting commands of OnlyOffice & nginx-proxy:

```
sudo docker run -i -t -d --name onlyoffice-community-server -e VIRTUAL_HOST=foo.bar.com \
    -h foo.bar.com \
    --restart always \
    --link onlyoffice-mail-server:mail_server \
    --link onlyoffice-document-server:document_server \
    -v /apps/onlyoffice/Logs:/var/log/onlyoffice  \
    -v /apps/onlyoffice/Data:/var/www/onlyoffice/Data  \
    -v /apps/onlyoffice/MySQL:/var/lib/mysql \
    onlyoffice/communityserver
```

`sudo docker run --name=nginx-proxy -d -p 80:80 -p 443:443 -v /apps/nginx-proxy/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

I don't know what's going wrong and what i have to do next (i read a lot since the problem persists). Additionally i'm not a real UNIX-Pro, it's a hobby to me since a long time, it would be nice to take a lil' bit care of that. ;)

Many thanks for helping me out of this situation! :)

P.S: here is the issue in my browser:
```
uR0ZwCfbuOc-MBj2l0XwvQ2.js?ver=264:13:
Uncaught TypeError: Cannot read property 'UserCaption' of null
(anonymous function) @ uR0ZwCfbuOc-MBj2l0XwvQ2.js?ver=264:13
requests.(anonymous function).callback @ FzoIB9G4wyYJlDezn5C0WA2.js?ver=264:38
AjaxPro.Request.endRequest @ FzoIB9G4wyYJlDezn5C0WA2.js?ver=264:38
AjaxPro.Request.doStateChange @ FzoIB9G4wyYJlDezn5C0WA2.js?ver=264:38
```

this file is reachable through the nginx-proxy.

**Comment by wader** [comment]
Hi, the `http://172.17.0.2:443` part in the log looks suspicious, trying to talk https on port 443... also `Connection refused` seems strange, i would expect some other error if it actually listen on 443.

Some more information would be nice, can you run:
```
docker network inspect $(docker network ls -q)
````
and
```
docker exec <nginx-proxy-container-id> cat /tmp/nginx/default.conf
```

**Comment by dboecker** [comment]
Hi wader,

yes, i was wondering about it too, so i gave it a fresh install (where the 172.17.0.2 -> onlyoffice-document-server is not any more part of my virtual-host-table) and the error is going stranger (or better).. :/

there is no error anymore in `docker logs -f <nginx-proxy-container-id>` while im refreshing the page (with persisting JS error in browser). But refreshing the page under the host-IP:port is resolving in a non-error-page.

`docker network inspect $(docker network ls -q)`:
https://gist.github.com/dboecker/e8954f0091892183641dd5d742de3c8b


`docker exec <nginx-proxy-container-id> cat /tmp/nginx/default.conf` can't be found, but i've /etc/nginx/conf.d/default.conf... if this is the right, here the log:
https://gist.github.com/dboecker/218bbc11a93d19abc662bd75e224bb27

**Comment by wader** [comment]
Sorry, wrong conf path, copy paste error. Sure VIRTUAL_PROTO or VIRTUAL_PORT are not set somehow? The "HTTPS" in caps for proxy_pass looks like proto is set somehow.
How do you access the container dirctly btw? Exposing port to the host?

**Comment by dboecker** [comment]
No problem mate and sorry for the confusion... In my last post i had a config with backend-ssl to my container, with the following start-sequence:
```
sudo docker run -i -t -d --name onlyoffice-community-server -e VIRTUAL_HOST=foo.bar.com -e VIRTUAL_PORT=443 -e VIRTUAL_PROTO=HTTPS -p 80 -p 5222 -p 443 \
    -h foo.bar.com \
    --restart always \
    --link onlyoffice-mail-server:mail_server \
    --link onlyoffice-document-server:document_server \
    -v /apps/onlyoffice/Logs:/var/log/onlyoffice  \
    -v /apps/onlyoffice/Data:/var/www/onlyoffice/Data  \
    -v /apps/onlyoffice/MySQL:/var/lib/mysql \
    onlyoffice/communityserver
```

I tried it at this point with non-ssl-backend to nginx-proxy-ssl, which is leading into the same as before:
start-sequence:
`sudo docker run -i -t -d --name onlyoffice-community-server -e VIRTUAL_HOST=foo.bar.com -p 80 -p 5222 -p 443 \
    -h foo.bar.com \
    --restart always \
    --link onlyoffice-mail-server:mail_server \
    --link onlyoffice-document-server:document_server \
    -v /apps/onlyoffice/Logs:/var/log/onlyoffice  \
    -v /apps/onlyoffice/Data:/var/www/onlyoffice/Data  \
    -v /apps/onlyoffice/MySQL:/var/lib/mysql \
    onlyoffice/communityserver`

`docker exec <nginx-proxy-container-id> cat /etc/nginx/conf.d/default.conf`
https://gist.github.com/dboecker/ad204dbd6dd6cd6a895a7ee030507c5b

BTW: yes, i'm going directly via exposed ports for (A-/B-)testing purposes.

**Comment by wader** [comment]
So with both of those two ways of starting you see no `Connection refused` error anymore? the example config looks good to me. Both only JS errors when going thru nginx-proxy? maybe compare request/responses and see what differs? looking at the browser error about `UserCaption` it looks like a XHR request is missing data etc

**Comment by dboecker** [comment]
Thanks, i'm currently checking the issue with your tips. All other docker containers (owncloud i.e.) works absolutely perfect.

At the current intermediate result i figured out that this issue is only happening in Chrome & Opera, in Firefox and IE (Edge) it's working fine. after some more results i'll write again.

**Comment by dboecker** [comment]
So, after investigating the behaviour of those js-files and its dependencies, im not sure if this is an issue of this nginx-proxy or an issue of the onlyoffice-software.

Since reading a lot (and a lot of things i currently don't understand at all points :D) about js issues in chrome, it is possible that the nginx-proxy cause this issue, but isn't the main-issue.

I'll open another issue in the git of onlyoffice and link it to this, maybe this clarify my problem. It would be great if this issue can stay open while i'm checking those other options.

And thanks wader, you helped me a lot until now, it is most appreciated.

**Comment by wader** [comment]
No problem. Yeah sounds nginx-proxy unrelated... only thing i can think of is if there is some difference in headers between the browsers. Is it a new version of Opera that is webkit based?... maybe a clue why only Chrome and Opera 😄
Don't think there is any problem keeping the issue open until you know more, good luck and let me know how it goes 👍

**Comment by dboecker** [comment]
Hi all,

after a big bunch of time (thanks to my job, hehe) i can give an update:

My issue have totally nothing to do with this awful nging-proxy. 👍 
(It was related to the onlyoffice-software, where the docker container isn't bugfree yet, which makes it impossible to use in a productive area. So i'm gonna do this via their linux-suite wrapped in a LXC.)

Thanks a lot @wader! :)
