### ISSUE TITLE
QUESTION: Since IPP is HTTP can I proxy IPP

### ISSUE THREAD

**Issue by majochoc** [jwilder/nginx-proxy#457]
Can I modify the configuration of nginx to listen on port 631 and reverse proxy containers that run IPP services?

Is this a bad idea?

**Comment by wader** [comment]
Hi, you mean listen externally? maybe try to add an extra `-p 631:80` when starting the container? (or 443 if you use https)

**Comment by majochoc** [comment]
Yeah, I just was wondering if that would work. I'll test that out.

**Comment by majochoc** [comment]
Yeah, that should work. Sorry I was being dense.

**Comment by wader** [comment]
:+1:
