### ISSUE TITLE
configuration changes for nginx.conf

### ISSUE THREAD

**Issue by sxamit** [jwilder/nginx-proxy#464]
I am trying to change the default /etc/nginx/nginx.conf configuration. specifically - the worker_processes and - events { worker_connections } configs.

I am not sure if I should change the nginx.tmpl file, add proxy.conf file or any other option

Any help?

**Comment by wader** [comment]
I don't think nginx like to have duplicate configuration so you probably have to change `/etc/nginx/nginx.conf` somehow. You could volume mount your own nginx.conf or create your own extended docker image.

**Comment by sxamit** [comment]
I extended Dockerfile -

```
FROM jwilder/nginx-proxy
COPY . /app/
RUN { \ 
    # Increased the number of worker_processes from any number to 4
    sed -i 's/\(worker_processes\s*\)[0-9]*;/\14;/' /etc/nginx/nginx.conf; \
    # Increased the number of worker_connections from any number to 19000
    sed -i 's/\(worker_connections\s*\)[0-9]*;/\119000;/' /etc/nginx/nginx.conf; \
}

**Comment by KevinDanikowski** [comment]
@sxamit  Can you give more information on that extended dockerfile? For example, what is that `COPY` command being run against? Because I'm not sure what you would be copying since you only need that script added
