### ISSUE TITLE
GitLab container doesn't respond when served via SSL (502)

### ISSUE THREAD

**Issue by dj-hedgehog** [jwilder/nginx-proxy#465]
I've deployed GitLab using the [official CE docker image](https://registry.hub.docker.com/u/gitlab/gitlab-ce/). It's sitting behind Jwilder's [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy/).

Now I'd like to switch to serving Gitlab via SSL. I placed the certificate in the appropriate place. 
It's also working on the Nginx side. However once I restart the Nginx-container with `external_url` starting with `https://` instead of `http://` I only get `502` errors.

```
environment:
    GITLAB_OMNIBUS_CONFIG: |-
      external_url 'https://git.example.com'
```
![image](https://cloud.githubusercontent.com/assets/7140800/15532763/c4f776b6-2261-11e6-8a15-7bd2a5e00e94.png)

When I use `http://` the browser complains about `mixed content` 

![image](https://cloud.githubusercontent.com/assets/7140800/15532786/ce3b9374-2261-11e6-9b9c-b5d26b75dc66.png)

What am I doing wrong?

**Comment by dj-hedgehog** [comment]
Passing these options to `GITLAB_OMNIBUS_CONFIG` fixed my problem:

```
nginx['listen_port'] = 80
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
```

**Comment by pascalandy** [comment]
Thanks for sharing your solution!
