### ISSUE TITLE
wordpress php-fpm 502 Bad Gateway

### ISSUE THREAD

**Issue by andruwa13** [jwilder/nginx-proxy#467]
Hey. If you connect the container wordpress php-fpm 502 Bad Gateway

Haproxy:
`proxy:
  image: 'jwilder/nginx-proxy:latest'
  ports:
    - '80:80'
    - '443:443'
  restart: always
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/root/vhost.d:/etc/nginx/vhost.d'
    - '/root/certs:/etc/nginx/certs:ro'
    - /usr/share/nginx/html
proxy-companion:
  image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
  restart: always
  volumes:
    - '/root/certs:/etc/nginx/certs'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
  volumes_from:
    - proxy
`

Wordpress:
`mariadb:
  environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_ROOT_PASSWORD=awdawd
  image: 'mariadb:latest'
  restart: always
  volumes:
    - '/root/docker2.pro/mysql:/var/lib/mysql'
memcached:
  image: 'memcached:latest'
  restart: always
wordpress:
  environment:
    - 'LETSENCRYPT_EMAIL=email@domain.com'
    - 'LETSENCRYPT_HOST=docker2.pro,www.docker2.pro'
    - 'VIRTUAL_HOST=docker2.pro,www.docker2.pro'
  expose:
    - '80'
    - '443'
    - '9000'
  image: 'wordpress:fpm'
  links:
    - memcached
    - 'mariadb:mysql'
  restart: always
  volumes:
    - '/root/docker2.pro/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    - '/root/docker2.pro/html:/var/www/html'
`

**Comment by md5** [comment]
See #99, #199, and #437 for some previous discussions around the possibility of supporting a FastCGI upstream.

**Comment by auchri** [comment]
+1 it's the same for the piwik container: https://hub.docker.com/_/piwik/. It exposes fpm on port 9000.

**Comment by brunocascio** [comment]
+1 for support to php-fpm

**Comment by cardonator** [comment]
This seems like important functionality. The container doesn't really support any CGI so you can't use any PHP apps directly behind the proxy.

**Comment by brunocascio** [comment]
Hi everyone,

I fix this using an image with Nginx:
https://github.com/celerative/wordpress

--------------               ---------------------------
| nginx-proxy | ------> |    celerative/wordpress   |
--------------               ---------------------------
