### ISSUE TITLE
Multiple hosts, one is not created?

### ISSUE THREAD

**Issue by ArneCoder** [jwilder/nginx-proxy#473]
Hi, 

using the following:

```
docker run  \
    --name nginx_frontend \
    --restart=always -d \
    -e "VIRTUAL_HOST=www.urdevtopia.com,urdevtopia.com" \
    -e "LETSENCRYPT_HOST=www.urdevtopia.com,urdevtopia.com" \
    -e "LETSENCRYPT_EMAIL=xxx@yahoo.de" \
    arnecoder/minas_tirith
```

Does not 100% work. - https://www.urdevtopia.com is fine, https://urdevtopia.com goes to "http". When i look into my nginx/certs folder i can see:

```
drwxr-xr-x 2 root root 4096 Jun  6 18:27 rancher.urdevtopia.com
lrwxrwxrwx 1 root root   38 Jun  6 18:27 rancher.urdevtopia.com.crt -> ./rancher.urdevtopia.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  6 18:27 rancher.urdevtopia.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   32 Jun  6 18:27 rancher.urdevtopia.com.key -> ./rancher.urdevtopia.com/key.pem
lrwxrwxrwx 1 root root   34 Jun  6 18:04 urdevtopia.com.crt -> ./www.urdevtopia.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  6 18:04 urdevtopia.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   28 Jun  6 18:04 urdevtopia.com.key -> ./www.urdevtopia.com/key.pem
drwxr-xr-x 2 root root 4096 Jun  6 18:04 www.urdevtopia.com
lrwxrwxrwx 1 root root   34 Jun  6 18:04 www.urdevtopia.com.crt -> ./www.urdevtopia.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun  6 18:04 www.urdevtopia.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   28 Jun  6 18:04 www.urdevtopia.com.key -> ./www.urdevtopia.com/key.pem
```

Looks like the folder "urdevtopia.com" is no created? did i miss something

**Comment by wader** [comment]
Hi, my certs looks the same when i have multiple hosts for one container. I think simp_le client will generate a cert with CN set to the first host name and SAN to all hosts. Have look with `openssl x509 -in fullchain.pem -text` and you will see CN and Subject Alternative Name.

About the other issue i don't really follow. What does "goes to http" mean, https:// redirects to http://? when I check with curl i see this:
```
$ for i in http://urdevtopia.com https://urdevtopia.com http://www.urdevtopia.com https://www.urdevtopia.com ; do echo $i ; curl -sI $i | grep -E '^(HTTP|Location)' ; echo ; done
http://urdevtopia.com
HTTP/1.1 301 Moved Permanently
Location: https://urdevtopia.com/

https://urdevtopia.com
HTTP/1.1 200 OK

http://www.urdevtopia.com
HTTP/1.1 301 Moved Permanently
Location: https://www.urdevtopia.com/

https://www.urdevtopia.com
HTTP/1.1 200 OK
```

Isn't that what you want?

**Comment by ArneCoder** [comment]
Thanks for you answer,

I want both URLs available via SSL connection:

- https://www.urdevtopia.com
- https://urdevtopia.com

Second is not working.

**Comment by wader** [comment]
Ah ok, so work as it should now? i've seen similar things like this before... my guess is that there is some issue with how lets encrypt companion creates and reloads hmm

**Comment by ArneCoder** [comment]
Yepp everything works "now" like a charm - great Container!

**Comment by wader** [comment]
Nice! Close issue if you like
