### ISSUE TITLE
GitLab - Nginx-Proxy & companion

### ISSUE THREAD

**Issue by ArneCoder** [jwilder/nginx-proxy#475]
I am bit confused, trying to run GitLab behind Reverse Proxy with SSL via Companion.

I am using the following "docker-compse.yml"

> gitlab:
>       restart: always
>       network_mode: "bridge"
>       image: sameersbn/gitlab:8.7.0
>       environment:
>           DEBUG: "false"
>           TZ: Europe/Berlin
>           GITLAB_TIMEZONE: Berlin
>           GITLAB_SECRETS_DB_KEY_BASE: 
>           GITLAB_HOST: git.urdevtopia.com
>           GITLAB_HTTPS: "false"
>           VIRTUAL_HOST: git.urdevtopia.com
>           LETSENCRYPT_HOST: git.urdevtopia.com
>           LETSENCRYPT_EMAIL: arnecoder@whatever.de
>           GITLAB_OMNIBUS_CONFIG: |
>             nginx['listen_port'] = 80
>             nginx['listen_https'] = false
>             nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }

When i try to clone via: git clone https://git.urdevtopia.com/WHATEVER i get: fatal: unable to access 'https://git.urdevtopia.com

When i use "git clone http://git.. " i am asked for password/user (https://git.urdev..) is this normal behaviour ? Thanks for your time.

**Comment by wader** [comment]
Hi, try setting `GITLAB_HTTPS: true`, from https://hub.docker.com/r/sameersbn/gitlab/ it says "However, when using a load balancer you MUST set GITLAB_HTTPS to true".

**Comment by ArneCoder** [comment]
Already tried it, that everything on the UI looks fine (no https errors etc.) but when i try to clone a repository (git clone http**s**://urdevtopia..), i get an error "unable to access / find server". 

If i do a curl/wget i get "You are redirected"

**Comment by wader** [comment]
Ok, and everything work are it should if you run without HTTPS?

**Comment by ArneCoder** [comment]
without https, everything is fine ... the problem is when i try to do git clone via https i get an redirect.

**Comment by ArneCoder** [comment]
Mehh.. seems to be OS X related, my windows slave works (-: Sorry to bother you with this.

**Comment by wader** [comment]
Ah 😄
