### ISSUE TITLE
Not redirecting to https

### ISSUE THREAD

**Issue by dmp1ce** [jwilder/nginx-proxy#481]
I have been using TLS with JrCs/docker-letsencrypt-nginx-proxy-companion and today nginx_proxy stopped redirecting to https. I assume a caught a breaking change with one of the new commits, but I have no idea what it is.

I fixed my image to 0.3.0 instead of latest and now the site is working.

In the nginx-proxy logs I wasn't getting anything when trying to access https. My browser immediately said I was blocked from viewing the site.

**Comment by jwilder** [comment]
@dmp1ce I merged some changes today related to SSL, but I'm surprised it broke things.  I just pushed up an `0.4.0` tag that is just before the merges from today.  Would you be able to test that tag (when it's built) to see if one the recent merges the cause?

**Comment by dmp1ce** [comment]
As soon as 0.4.0 is built, I'll give it a try.

**Comment by jwilder** [comment]
It's up now.

**Comment by dmp1ce** [comment]
`0.4.0` and `latest` seem to be working now. I just tested both of them. Closing.
