### ISSUE TITLE
Timeout when using SSL on static website nginx image

### ISSUE THREAD

**Issue by tgemes** [jwilder/nginx-proxy#486]
Hi, thanks for the great work on this package.

I tried it with several images before they all worked fine on HTTP. Today I tried to put HTTPS on my simple static website on nginx with LETSENCRYPT. The certs generated just fine and nginx-proxy tried to redirect to HTTPS as per the documentation. However, my website always gives a timeout as a response.

Just to confirm, I ran the same setup with HTTPS_METHOD=noredirect and getting the same results. When I go to my website on nginx through http:// it works fine and I see from the console that it got the requests. But no request gets to the website on nginx through https://, the result is a timeout.
I'm using a Chrome Incognito Window each time.

Steps:
- Running nginx proxy:
`docker run -d -p 80:80 -p 443:443 --name nginx-proxy -v /var/certs:/etc/nginx/certs:ro -v /etc/nginx/vhost.d -v /usr/share/nginx/html -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`
- Running the companion:
`docker run -d -v /var/certs:/etc/nginx/certs:rw --volumes-from nginx-proxy -v /var/run/docker.sock:/var/run/docker.sock:ro jrcs/letsencrypt-nginx-proxy-companion`
- Building the website:
`docker build -t landing_test .`
Dockerfile:
```
FROM nginx
COPY . /usr/share/nginx/html
EXPOSE 80
```
- Running the website container
`docker run -e VIRTUAL_HOST=mysite.com -e LETSENCRYPT_HOST=mysite.com -e LETSENCRYPT_EMAIL=hello@mysite.com -e HTTPS_METHOD=noredirect landing_test`

My docker containers:
```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
d46bdade4e1a        landing_test                             "nginx -g 'daemon off"   16 minutes ago      Up 16 minutes       80/tcp, 443/tcp                            hungry_bartik
a6621e1bd2d2        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entry"   18 minutes ago      Up 18 minutes                                                  sleepy_rosalind
af20b30df08b        jwilder/nginx-proxy                      "/app/docker-entrypoi"   18 minutes ago      Up 18 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy
```

Have I missed some configuration? I'm happy to provide more details if someone can point me in the right direction.

Thanks.

**Comment by wader** [comment]
What does `curl -I https://mysite.com` say? can you verify that the browser can make a port 443 TCP connection to nginx-proxy?

**Comment by tgemes** [comment]
Thanks. That really helped. It looks like the cloud provider we're using had a firewall restriction not to let 443 through to the host machine. It works totally fine now.
