### ISSUE TITLE
nginxproxy_default network?!

### ISSUE THREAD

**Issue by kesopeso** [jwilder/nginx-proxy#487]
Hi, when I start nginx-proxy container, it creates nginxproxy_default network.
I tried adding
networks:
    - bridge
to my docker-compose.yml but to no avail.

When I start the container with 'docker-compose up -d' command, I get this error:
ERROR: Service "nginx-proxy" uses an undefined network "bridge"

This is the output of 'docker network inspect $(docker network ls -q):
[
    {
        "Name": "bridge",
        "Id": "b99dbca30dd33abf166403b05393e70bdbac2729ddbfbb6bfd999c0649f91046",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.42.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "50e3a578a4b8311cd9d742eee330e3ccfc85e7aa9b2b39f31fd3a2f4d0b88d53": {
                "Name": "docker-registry",
                "EndpointID": "faf93cc4b7f0e911f8170e64905dfbb529e3def0b9db72e932ff964436e3242f",
                "MacAddress": "02:42:ac:11:00:01",
                "IPv4Address": "172.17.0.1/16",
                "IPv6Address": ""
            },
            "6894e7710c05c06d581dfed43ba9d4159a1a03c3e1bc431385cd6e083abc4836": {
                "Name": "scrapyd",
                "EndpointID": "1a36dd189c6bc0857e7dec75696997e2ee7d86b7f4a81f4dbe23bf6929154595",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "a4118c3e4b49d6878eb2e4ba1aa2a4a8be10706504e137d857d3f1912f619ddc": {
                "Name": "gitlab-ce",
                "EndpointID": "40b39d6640fffbde08f86094bd8111671c451d7670fa6bf7610daed944e32dcc",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    },
    {
        "Name": "host",
        "Id": "106b4fa5864f498b043b807421d31ef8325916bea3cbe3d9e4de1ea6a3b25ca5",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    },
    {
        "Name": "nginxproxy_default",
        "Id": "4122e05d7b80c8777702a6f203f53edea38200616d216f98efab9a5fbd73e2b9",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    },
    {
        "Name": "none",
        "Id": "547586364a3b31e5c2ab121019310608be95ed863cbd5f29395e65f5f796c224",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

why is nginx-proxy creating this new network? where is this behaviour defined? I can't seem to find it.

Thank you!

**Comment by wader** [comment]
It's default docker compose behaviour, not related to nginx-proxy

**Comment by kesopeso** [comment]
thx! found the solution, to connect to preexisting network, i had to add this to my compose file

networks:
    default:
        external:
            name: bridge



found it in docker compose network documentation.
thx again!

**Comment by wader** [comment]
👍 close?

**Comment by leyyinad** [comment]
Does this work with multiple services (like some db), will they be able to see each other?

**Comment by wader** [comment]
@leyyinad not sure i follow, can you give an example?

**Comment by leyyinad** [comment]
The following doesn't work for me. The `web` service can't find the `db` host. Any idea?

```yml
version: '2'
services:
  web:
    image: rocket.chat
    links:
      - db:db
    command: "/bin/bash -c 'sleep 5 && node main.js'"
    environment:
      VIRTUAL_HOST: chat.dkr
    network_mode: "bridge"
  db:
    image: mongo
    command: --smallfiles
    network_mode: "bridge"
```

**Comment by wader** [comment]
Hmm ok, can the web container resolve the hostname "db" to something? try without links, with the new docker networking you don't need to use links anymore... but maybe things get weird when mixing with bridge mode.

Have a look at https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by leyyinad** [comment]
Doesn't work with or without the `links` section. I can't reach the hostname `db` from the `web` container.

```
$ getent hosts
127.0.0.1       localhost
127.0.0.1       localhost ip6-localhost ip6-loopback
172.17.0.5      aab72d161cbd
```

Maybe I need to assign the container some hostname. That's what I tried using the links. I'll thoroughly read through the docs once more, thank you!

**Comment by wader** [comment]
Can you get it working using version 2 compose config and skip links and `network_mode: "bridge"`? also make sure that the mongo service is not exiting immediately for some reason... i've been bitten by that.
When using links i think you should see entries in the hosts file (at least with olders verisons of docker) but when using the new networking support there will only be an entry pointing to the internal DNS server that will take care of resolving things.

**Comment by leyyinad** [comment]
I had this before – this way the services do work and the `web` container can ping the `db` container and everything looks fine, except for that nginx-proxy won't setup the `upstream` part, which leads to a `503` error when trying to access the app. It seems I can either have my web service find the db or nginx-proxy find my web service, not both, when using v2 style configs.
 
```
upstream chat.dkr {
}
server {
	server_name chat.dkr;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://chat.dkr;
	}
}
```

**Comment by wader** [comment]
Ok. How do you run nginx-proxy? what i think is missing now is that your web service needs to be connected to a network that is common with nginx-proxy, try to add:

```yml
version: '2'
services:
  web:
    ... config cut ....
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

This is assuming nginx-proxy container is running connected to a network named "nginx-proxy". Have a look with `docker network ls` etc.

**Comment by leyyinad** [comment]
I'm running nginx-proxy from a compose v2 file with `network_mode: "bridge"`. If I add

```yml
networks:
  default:
    external:
      name: bridge
```
I get, when running `docker-compose up`:

> `ERROR: for web  Network-scoped alias is supported only for containers in user defined networks`

Of course, I can define a network `nginx-proxy` in my nginx-proxy's `docker-compose.yml`, then connect my app to the external network `nginxproxy_nginx-proxy`. I had this running as well, this works. But, then my problem is that I lose v1-compatibility on our production and staging servers, none of my v1 apps could be accessed by nginx-proxy, which means, I would have to update all my companies projects to v2 and then redeploy all our websites at once only to be able to run one app using v2. Or stay with v1 forever.

It would be super helpful to connect containers to user defined networks and the bridge network at the same time, which clearly is a compose issue.

Thank you very much for your help and patience!
