### ISSUE TITLE
upstream declared as down with monit

### ISSUE THREAD

**Issue by port22** [jwilder/nginx-proxy#498]
Hi,
I built a docker image based on alpine and installed monit. It runs via supervisor in foreground-mode and is configured to listen on port 80.
The container was started with -e VIRTUAL_HOST=monit.mydomain.com
I can `curl -I 172.17.0.9` and get the monit basic auth reply.

```
HTTP/1.0 401 Unauthorized
Server: monit 5.15
WWW-Authenticate: Basic realm="monit"
```

But anyhow, the docker-nginx-proxy generated default.conf upstream stanza is stated down:

```
upstream monit.mydomain.com {
				## Can be connect with "bridge" network
		# monit
		server 172.17.0.9 down;
}
```

I don't know how to solve that cleanly without hacking in manual .. any ideas?
I think everybody can reproduce that.

If I manually delete the word "down" and `nginx -s reload`, it's working fine.
After the next `docker restart jwilder/nginx-proxy` the upstream is marked down again.

Maybe it just has something to do with the basic auth itself so that nginx-proxy recons it as down because of the HTTP Error 401?

**Comment by wader** [comment]
I think this happens when nginx-proxy knows about the container but it does not expose any port. Try to add `EXPOSE 80/tcp` to your Dockerfile or run with `--expose 80`.
