### ISSUE TITLE
Error on nginx.conf generation with VIRTUAL_PROTO=https leads to Nginx 502 Bad Gateway

### ISSUE THREAD

**Issue by emathias** [jwilder/nginx-proxy#501]
Hi, 

I'm facing an issue with the generation of nginx.conf when using SSL configuration. 

In nginx.tmpl  you have: 

location / {
		proxy_pass {{ trim $proto }}://{{ trim $host }};
		...
}

This means that if proto is https your resulting proxy_pass config leads to recursion, which result in an Nginx 502 Bad Gateway.   See example of generated nginx.conf below  (proto in bold)

Instead, I believe you should replace 'https' by 'http'. 

Thanks!

Elton

server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
upstream site.local {
                         ## Can be connect with "bridge" network
                        # hackme
                        server 172.17.0.4:80;
}
server {
        server_name site.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name site.local;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_certificate /etc/nginx/certs/site.local.crt;
        ssl_certificate_key /etc/nginx/certs/site.local.key;
        add_header Strict-Transport-Security "max-age=31536000";
        location / {
                proxy_pass **https**://site.local;
        }
}

**Comment by wader** [comment]
Not sure i follow. Your using `VIRTUAL_PROTO=https`? `VIRTUAL_PROTO` is what protocol to use between nginx-proxy and the container.

**Comment by emathias** [comment]
Hi Wader, 

Yes, that's what I'm doing.   The problem is that the current template in master is like this
(from: https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl)

...
server {
	server_name {{ $host }};
	listen 443 ssl http2 {{ $default_server }};
 ... 
location / {
		proxy_pass {{ trim $proto }}://{{ trim $host }};		
                ...
	}
...
}

As a result, the generated nginx file listen to 443 and endup proxy_pass(ing) it to 443 because of the  {{ trim $proto }} and the upstream is never reached.

Replacing  {{ trim $proto }} by http seems to solve the issue. 

BR

**Comment by wader** [comment]
But `proxy_pass https://site.local` in this case will refer to the server group called "site.local" defined by `upstream site.local { ... }` not the actual hostname. So `proxy_pass https://site.local` will result in nginx proxying requests to `172.17.0.4:80` using https.

So im gussing your actual problem is that you should either don't use `VIRTUAL_PROTO=https` (use default "http" instead) or make sure your container actual can talk https on 80 (have certificates etc). If your container listens to both 80 and 443 you can use `VIRTUAL_PORT=443` in combination with `VIRTUAL_PROTO=https`.

**Comment by emathias** [comment]
Oh yes ... thanks for clarifying that for me. 

I believed the generation of the SSL nginx config depended on the `VIRTUAL_PROTO=https`. 

My intended behavior was to have the container talking 'http' and 'https' handled by nginx. 

I'm closing the issue. 

Thanks a lot Wader!
