### ISSUE TITLE
Problem with nginx.tmpl when using docker-compose based deployments

### ISSUE THREAD

**Issue by thesmartguild** [jwilder/nginx-proxy#506]
Line 81 should be:
	{{ range $knownNetwork := $container.Networks }}
not
	{{ range $knownNetwork := $CurrentContainer.Networks }}

The compose generated network is not picked up correctly and the result is an empty "upstream" definition.

Thank you - Todd O'Connell
The Smart Guild LLC

**Comment by wader** [comment]
Hello, it was changed to `$CurrentContainer.Networks` in #337 to support the new docker networking support. Hmm i guess your change works but might act strange if more than one independent nginx-proxy containers are running? not sure :)

Could your problem be solved without this change? do you run separate containers and docker-gen with `-only-exposed`?

**Comment by thesmartguild** [comment]
This is the docker-compose.yml I am testing with:
[docker-compose.yml.txt](https://github.com/jwilder/nginx-proxy/files/366451/docker-compose.yml.txt)
I am using -only-exposed.

I'm not sure why, but $CurrentContainer.Networks was empty and so the range loop was never executed.

**Comment by wader** [comment]
It's string dump of a slice of some struct i guess. Try to remove the -only-exposed argument and restore to original template

**Comment by thesmartguild** [comment]
Thank you!   Removing the -only-exposed argument worked with the original template.

**Comment by jedwards1211** [comment]
Removing -only-exposed doesn't seem to work for me
