### ISSUE TITLE
Unable to send emails from container via SMTP after enabling HTTPS

### ISSUE THREAD

**Issue by patrickc91** [jwilder/nginx-proxy#508]
I have a Jenkins and Gitlab container running behind this reverse proxy. Both tools used to send me emails upon failed builds or various other situations, but after enabling HTTPS these tools are no longer able to connect to my SMTP server (hosted somewhere else on my domain).

The odd thing is that I'm able to `bash` into the containers and send emails through the command line using `ssmtp`. It's only through the tools themselves that I'm running into issues.

Gitlab doesn't really give me any useful information at all, but Jenkins returns a 554, which in my experience indicates IP has been blacklisted. That's not the case here as I'm able to send emails from the server itself, as well as through the bash terminals of each of these containers without issue.

Could the Nginx proxy be playing a role in this? Perhaps it's blocking the outgoing request? I'm not really sure how to determine where the issue lies here, but I feel like I've narrowed it down to the proxy.

Any help or ideas would be much appreciated!

**Comment by patrickc91** [comment]
Ignore this for now...I'm working with my sys admin to make sure this isn't an issue with our server. But after further testing it's looking like it's probably our set up, and not this reverse proxy.

Will update and close if that's the case.

**Comment by patrickc91** [comment]
Our bad! Sorry for polluting the issue's section.

**Comment by jonguenther** [comment]
@patrickc91 what was the issue? I am having the same problem and can't find a solution.
