### ISSUE TITLE
Define another port to redirect to

### ISSUE THREAD

**Issue by dblM90** [jwilder/nginx-proxy#519]
Hello,

could it be possible to implement a new environment variable to specify the port, to which nginx should redirect requests?

For example i have a container running a web app on port 3000. i would like to say nginx via variable, that this container is reachable via http://test.domain.com and the port is not 80/443, but 3000

**Comment by wader** [comment]
Not sure i follow. Do you mean listen externally on the docker host on additional ports? than you could probably start the nginx-proxy container with additional ports  (add a `-p 3000:80` etc) but other hosts will be accessible via that port also.

**Comment by dblM90** [comment]
no, you misunderstood my question. i don't want nginx do listen on different ports, but to redirect incoming traffic on port 80/443 to another port like 3000. Because there are several containers with web apps not listening on port 80 or 443, i want to redirect to

**Comment by wader** [comment]
Ok! Have looked at using VIRTUAL_PORT?

**Comment by dblM90** [comment]
Yes, i tried using virtual port, but seems to dont habe any effect at nginx

**Comment by dblM90** [comment]
oh, okay. it takes several minutes before the port is adjusted. i think thats it. thanks

**Comment by wader** [comment]
@dblM90 hmmm weird, it should more or less instant
