### ISSUE TITLE
docker-compose v2 with network only displays welcome page nginx 

### ISSUE THREAD

**Issue by freskimo** [jwilder/nginx-proxy#525]
Hello,

I first define a new network:
`sudo docker network create --driver bridge proxy-tier`

I then use docker-compose to setup the nginx reverse proxy as follows:

```
version: '2'
services:
  nginx:
    image: nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /etc/nginx/conf.d
     - /etc/nginx/vhost.d
     - /usr/share/nginx/html
     - cert-store:/etc/nginx/certs:ro
    networks:
     proxy-tier:
  gen:
    image: jwilder/docker-gen
    depends_on:
     - nginx
    volumes_from:
     - nginx
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: [
        -notify-sighup,
        nginx-proxy,
        -watch,
        #-only-exposed,
        -wait,
        "5s:30s",
        /etc/docker-gen/templates/nginx.tmpl,
        /etc/nginx/conf.d/default.conf
      ]
    networks:
     proxy-tier:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
     - gen
    volumes_from:
     - nginx
    volumes:
     - cert-store:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
     - NGINX_DOCKER_GEN_CONTAINER=proxy_gen_1
volumes:
  cert-store:
networks:
  proxy-tier:
    external: true
```

My sample app looks as follows:
```
version: '2'
services:
  app:
    build: .
    ports:
     - "8081:80"
    environment:
     - VIRTUAL_HOST=www.xxx.com
     - VIRTUAL_NETWORK=proxy-tier
   networks:
     - proxy-tier
networks:
  proxy-tier:
    external: true
```

In order for the nginx config to display the ip addresses of the found container i would have to:
1/ comment out -only-exposed
2/ add the docker-gen to the network (proxy-tier)
3/ add VIRTUAL_NETWORK to the app env

The config of nginx now correctly points to the container. However, the nginx default welcome page is still displayed. 

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream www.xxx.com {
				## Can be connect with "proxy-tier" network
			# nvw_app_1
			server 172.19.0.4:80;
}
server {
	server_name www.xxx.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://www.xxx.com;
	}
}

```

From the proxy container it is not possible to ping to the app container. I have only one relevant firewall rule opening port 80. I disabled dockers functionality to configure the firewall. 

I desperately looking for a solution. If someone knows anything more...

(Docker version 1.12.0, build 8eab29e & docker-compose version 1.8.0, build 94f7016)

**Comment by RafaelKr** [comment]
Try this for your app config:

version: '2'
services:
  app:
    build: .
    networks:
      - default
      - nginx-proxy
    ports:
     - "8081:80"
    environment:
     - VIRTUAL_HOST=www.xxx.com

networks:
    nginx-proxy:
        external:
            name: proxy-tier

**Comment by freskimo** [comment]
Something went wrong during the copy/paste. Indeed this network is defined for the app config.

Nginx config looks fine. It just doesn’t proxy but instead displays the default welcome page.
I reckon if the container is not reachable by the proxy it would display an error instead of displaying the default page.

**Comment by wader** [comment]
So you see welcome page when you request http://www.natvingerwerk.be or http://www.natvingerwerk.com? generated config looks ok. Can it be that it is the proxied container that returns the welcome page for some reason?

**Comment by RafaelKr** [comment]
I got this also today, as I forgot a semicolon (config syntax was wrong)
You could check the output of
`docker exec -it nginx nginx -t -c /etc/nginx/conf.d/default.conf`

Offtopic
@jwilder I executed this command and got
```
2016/08/05 08:34:09 [emerg] 31#31: "map" directive is not allowed here in /etc/nginx/conf.d/default.conf:3
nginx: [emerg] "map" directive is not allowed here in /etc/nginx/conf.d/default.conf:3
nginx: configuration file /etc/nginx/conf.d/default.conf test failed
```

The first 6 lines look like this:
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
```
But it's working, so no need to check this immediately.

**Comment by freskimo** [comment]
@wader I am positive that this is the proxy's welcome page and not the app container.
@RafaelKr What semicolon did you forget? 
The output is the same as yours. Could this be the error why it isn't working?

**Comment by wader** [comment]
@RafaelKr default.conf is config ment to be included inside `http { ... }`, run with `-c /etc/nginx/nginx.conf` instead

**Comment by wader** [comment]
@freskimo could the problem be that `-notify-sighup` is wrong, there is no "nginx" container? try to add `container_name: nginx` for the nginx service. That would explain the welcome page, default nginx config (with welcome page) is copied to the volume when container is created, docker-gen runs to produce the correct config but then fails to reload nginx.

**Comment by mickaelperrin** [comment]
I am currently experiencing a very weird and similar issue but every two request.

First request is well proxied to the destination container, I can see the logs of the proxied container and nginx-proxy to update. Second request update only nginx-proxy and displays the nginx home page.

running 

Crazy ? Any hints on what to watch, and which useful informations to provide ?

Running `docker exec -it propject_nginx_1 nginx -t -c /etc/nginx/nginx.conf` returns:

    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by freskimo** [comment]
@wader You were right i feel dumb now :). Indeed, the command expects the name of the container. I should have read the doc better.

Thank you all for the help. This can be closed.

**Comment by wader** [comment]
@freskimo no problem, i've been there too... stopid misconfigs 😄

**Comment by biax** [comment]
I'm learning docker and would like to know what      "- VIRTUAL_HOST=www.xxx.com" environment variable is for? Where or how is this variable used? I don't see it used anywhere.

**Comment by wader** [comment]
@biax Hi, it's used in the docker-gen template here https://github.com/jwilder/nginx-proxy/blob/0670a13d922a7c85d01d4ccb1c629bf3edc36dfe/nginx.tmpl#L79

It's a environment used in containers to tell nginx-proxy which hostnames to route to them.
