### ISSUE TITLE
Can't start the container...

### ISSUE THREAD

**Issue by ulrith** [jwilder/nginx-proxy#530]
I've tried to start nginx-proxy container with the command

` docker run -d -p 80:80 -v /var/run/docker/libcontainerd/docker-containerd.sock:/tmp/docker.sock:ro --name nginx-proxy --net bridge jwilder/nginx-proxy`

But I've got the following error:

```
dockergen.1 | 2016/08/11 14:52:09 Watching docker events
dockergen.1 | 2016/08/11 14:52:09 Error retrieving docker server info: Get http://unix.sock/info: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0e\xff\xf1"
dockergen.1 | 2016/08/11 14:52:09 Error listing containers: Get http://unix.sock/containers/json?all=1: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0e\xff\xf1"
dockergen.1 | 2016/08/11 14:52:09 Docker daemon connection interrupted

```

My $DOCKER_HOST is tcp://192.168.103.104:4243,
I have no /var/run/docker.sock file...

Please help!

**Comment by wader** [comment]
What is `/var/run/docker/libcontainerd/docker-containerd.sock`? could it be related to docker only wants to talk TLS or no TLS at all? at the moment it looks like a unix socket is required.

**Comment by ulrith** [comment]
The right socket was mistakenly removed when fighting with the bug
https://github.com/docker/docker/issues/22847
