### ISSUE TITLE
Use iptables with nginx-proxy

### ISSUE THREAD

**Issue by SuperITMan** [jwilder/nginx-proxy#532]
Hello, 

First all, thank to jwilder for this perfect project that I use since one month ! :)

Now, I have a litte question about iptables.
Actually, I installed Fail2Ban in a docker and f2b analyses logs of nginx-proxy to ban ip. 

After X bad tryings to connect to my admin website, the ip address is banned for 15 minutes thanks to iptables. 
Unfortunately, for an unknown reason, it does not work with ports 80 and 443 (linked to nginx-proxy).

So, if I do these commands (probably not necessary to do all), I'll be suppose to be completely blocked.

> iptables -A INPUT -s public_address_ipv4 -j REJECT
> iptables -A DOCKER -s public_address_ipv4 -j REJECT
> iptables -A DOCKER-ISOLATION -s public_address_ipv4 -j REJECT

Obviously, my SSH access is blocked but I always can access to my website... 
How can I prevent an ip to access to access to my website linked to nginx-proxy ?

If someone has an idea, it would be great ! :)

PS : Sorry for my English, it's not my mother tonge

**Comment by wader** [comment]
My guess is that fail2ban default only rejects ssh traffic (port 22) on ssh login fails. There seems to be something called "allports" for fail2ban but i can't really figure how to use it.

**Comment by SuperITMan** [comment]
You're right, there's an action called allports which block all ports for the address. 

But normally if I do `iptables -A INPUT -s public_address_ipv4 -j REJECT`, the IP should be blocked. 
It is for ssh but not for web.

**Comment by SuperITMan** [comment]
Finally I found a solution to use iptables and fail2ban with nginx-proxy :)
You can find Fail2Ban for Docker on my GitHub here : [https://github.com/SuperITMan/docker-fail2ban](https://github.com/SuperITMan/docker-fail2ban) 

Here is how to use iptables to prevent access to docker web host
```
iptables -N PRE-DOCKER
              iptables -I FORWARD -o docker0 -j PRE-DOCKER
              iptables -A PRE-DOCKER -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
              iptables -A PRE-DOCKER -i docker0 ! -o docker0 -j ACCEPT
              iptables -A PRE-DOCKER -m state --state RELATED -j ACCEPT
              iptables -A PRE-DOCKER -i docker0 -o docker0 -j ACCEPT
```

Thanks to Rudi Starcevic for his solution https://forums.docker.com/t/restricting-external-container-access-with-iptables/2225/3

**Comment by hvorragend** [comment]
Even if the post is already a bit older, I have a question:
How did you get to the logs? The file access.log is actually not available at all.

```
	&& ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
```

**Comment by hvorragend** [comment]
Please?
