### ISSUE TITLE
Virtual Host issue with subdomain

### ISSUE THREAD

**Issue by Felhamed** [jwilder/nginx-proxy#533]
I am running a few ghost blogs and the proxy works perfectly for every domain I've tried. However, when trying to assign a sub-domain I get 502 bad gateway and I cannot figure out what the issue is. I know my DNS is set correctly because when I ping the sub-domain I get the correct IP. Here is how I deploy ghost:

`docker run --name some-blog -d -p 81:2368 -e VIRTUAL_HOST=blog.domain.com -v /home/ghost/someblog/:/var/lib/ghost --restart unless-stopped ghost`

That gives me a 502 gateway error, while having the VIRTUAL_HOST=domain.com does not. Any idea why?

**Comment by Felhamed** [comment]
Btw, "VIRTUAL_HOST=blog.domain.com,www.blog.domain.com" fixed my issue.

**Comment by wader** [comment]
Close?

**Comment by Felhamed** [comment]
Yes, closing.
