### ISSUE TITLE
mixed http / https 

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#534]
There is an inconsistency how http to https redirect happens.

Consider following sample:

```
environment:
    VIRTUAL_HOST: |
     domain1.com,
     domain2.com
    LETSENCRYPT_HOST: |
     domain2.com
    LETSENCRYPT_EMAIL: support@domain.com
```

domain2.com works fine, its being redirected correctly http -> https. Problem is that domain1.com without ssl is also being redirected to https and user is greeted with error that ssl doesn't exist obviously.

```
curl -k --head teemo.weare.de.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.9.15
Date: Sun, 14 Aug 2016 11:19:23 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://teemo.weare.de.com/
```

generated nginx config

```
upstream 
teemo.weare.de.com {
                ## Can be connect with "bridge" network
            # webserver
            server 172.17.0.9:80;
}
server {
    server_name 
teemo.weare.de.com;
    listen 80 ;
    access_log /var/log/nginx/access.log ghost;
    return 301 https://$host$request_uri;
}
server {
    server_name 
teemo.weare.de.com;
    listen 443 ssl http2 ;
    access_log /var/log/nginx/access.log ghost;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;
    ssl_certificate /etc/nginx/certs/weare.de.com.crt;
    ssl_certificate_key /etc/nginx/certs/weare.de.com.key;
    ssl_dhparam /etc/nginx/certs/weare.de.com.dhparam.pem;
    add_header Strict-Transport-Security "max-age=31536000";
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http://teemo.weare.de.com;
    }
}

```

sometimes after restarts and moving around domain without ssl in the list of VIRTUAL_HOST correct config is generated without redirect, this is especially true if domain without ssl is last in the list.

**Comment by sandrodz** [comment]
@jwilder any ideas? I think this is a bug.

**Comment by sandrodz** [comment]
@wader any thoughts?

**Comment by wader** [comment]
@sandrodz Hmm im looking at `nginx.tmpl` for when `$is_https` is true... the only thing that comes to mind is the `closest` expression that tries to find the "best" match. Do the domains share suffixes etc?

**Comment by sandrodz** [comment]
Let me give you a real settings:

```
    VIRTUAL_HOST: |
      abc.weare.de.com,
      weare.de.com,
      www.weare.de.com,
      flarum.weare.de.com,
      demos.weare.de.com,
      labs.weare.de.com,
      cdn.weare.de.com,
      shop.weare.de.com,
      adjaragroup.com,
      www.adjaragroup.com,
      wiseadvices.com,
      www.wiseadvices.com,
      kpi.ge,
      www.kpi.ge,
      tngabor.com,
      www.tngabor.com,
      stylediplomacy.com,
      www.stylediplomacy.com,
      holiday.ge,
      www.holiday.ge,
      hi-tbilisi.com,
      www.hi-tbilisi.com,
      holidayinn-tbilisi.com,
      www.holidayinn-tbilisi.com,
      kpiukraine.com,
      www.kpiukraine.com,
      ekotek.ge,
      www.ekotek.ge,
      cjn.ge,
      www.cjn.ge,
      fish.weare.de.com,
      static.europa.weare.de.com,
      static.isonoir.weare.de.com,
      static.moto.weare.de.com,
      static.prospero.weare.de.com,
      static.roomsgazette.weare.de.com,
      static.wiseadvices.weare.de.com,
      teemo.weare.de.com
    LETSENCRYPT_HOST: |
      abc.weare.de.com,
      weare.de.com,
      flarum.weare.de.com,
      demos.weare.de.com,
      labs.weare.de.com,
      cdn.weare.de.com,
      shop.weare.de.com,
      adjaragroup.com,
      wiseadvices.com,
      kpi.ge,
      tngabor.com,
      stylediplomacy.com,
      www.stylediplomacy.com,
      holiday.ge,
      hi-tbilisi.com,
      kpiukraine.com,
      ekotek.ge,
      cjn.ge,
      fish.weare.de.com
```

in this config, static.wiseadvices.weare.de.com gets wrongfully https, while last item teemo.weare.de.com works fine.

**Comment by wader** [comment]
Did some tests, docker execed into a nginx-proxy container and then:
```
# exec -ti nginxproxy_nginx bash
root@6a0dc956e1a5:/# mkdir /tmp/test
root@6a0dc956e1a5:/# cd /tmp/test
root@6a0dc956e1a5:/tmp/test# touch weare.de.com.crt
# this is what "{{ $vhostCert := (closest (dir "/etc/nginx/certs") (printf "%s.crt" $host))}}" do
root@6a0dc956e1a5:/tmp/test# docker-gen <(echo '{{closest (dir "/tmp/test") "static.wiseadvices.weare.de.com.crt"}}')
weare.de.com.crt
```
And looking at what `closest` does in docker-gen: 

    closest $array $value: Returns the longest matching substring in $array that matches $value

But it's weird if it only happen some times, this should happen every time, or?

Anyway this feels like a bug yes. Guess the same as #434

**Comment by sandrodz** [comment]
It happens all the time, except for the very last domain in the list. That last domain threw off my initial estimate of the problem.

**Comment by wader** [comment]
Not the last one... that is strange. Do you see any logic to that? hmm

**Comment by sandrodz** [comment]
last in `VIRTUAL_HOST` doesn't get ssl redirect when it doesn't need to. But ones above it get ssl redirect even if they don't need to. I don't see any reason why it happens :S

**Comment by wader** [comment]
And it's not related to the `closest` behaviour?

**Comment by kachkaev** [comment]
Same issue here. Temporary adding all domains to `LETSENCRYPT_HOST` as a workaround.

**Comment by sandrodz** [comment]
@wader I'm hitting this issue all the time. I've learned few more things:

Last domain in the list, doesn't get redirected to https, even if its in `LETSENCRYPT_HOST` list. All other domains get redirected to https even if they are not in `LETSENCRYPT_HOST `.

This is super annoying, I don't always want to have all domains in `LETSENCRYPT_HOST `. This also means there is a bug, since behaviour is all over the place.

**Comment by sandrodz** [comment]
atm I'm using this last domain trick as a workaround, so if I don't want domain to be redirected to https - I'm simply putting it as last domain in the `VIRTUAL_HOST` - but obviously this is seriously limiting, because I can only have 1 domain as a last one :)

**Comment by sandrodz** [comment]
Any news on this front?

**Comment by sandrodz** [comment]
I think https://github.com/jwilder/nginx-proxy/issues/720#issuecomment-285965216 fixed this.
