### ISSUE TITLE
multiple sites, creating and updating

### ISSUE THREAD

**Issue by dirad** [jwilder/nginx-proxy#541]
What is the best practice if i want to run several sites behind this nginx-proxy? 

I'd like to document this for others as well, as i am having a bit if confusion with the workflow.

Steps
* work locally, creating a app / site 
* test and pack as docker image
* ? put in repo ? what about private code
* boot a staging / prod server , install docker and pull nginx-proxy , make configurations for nginx
* pull private [app] docker image 
* set-up docker-compose to include your image
* run docker with the virtual_host specified in docker-compose

Am i on the right track or made a salad?

+ Is it possible to have nginx-proxy use a host directory for data [wp files for instance] so containers are lean and clean?

**Comment by RafaelKr** [comment]
I also would like to know, if there is a way to do zero-downtime deployments.

```
1. v1 is running (WordPress v1 + SQL v1)
2. start container WordPress v2 (using SQL v1)
3. rewrite nginx config to point to WordPress v2 (but don't close open connections to WordPress v1)
4. stop container WordPress v1, after all connections to it are closed
```

**Comment by jwilder** [comment]
I'd suggest reading the original blog post for this project: [Automated Nginx Reverse Proxy for Docker](http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/).

To run multiple sites, you just need to start `nginx-proxy` on your host and then start each container with a `-e VIRTUAL_HOST=site1.com`.  Provided your DNS is setup to route `site1.com` to your nginx host, `nginx-proxy` will forward the request to the containers started with `VIRTUAL_HOST=site1.com`.
