### ISSUE TITLE
Support Letsencrypt certificate names and folder structure

### ISSUE THREAD

**Issue by marcofranssen** [jwilder/nginx-proxy#542]
It would be awesome if the container could run ssl using letsexcrypt retrieved certificates.

Lets encrypt puts certificates in a folder called after the first domainname in your certificate.

`/etc/letsencrypt/live/some-app.marcofranssen.nl`

In the folder there are the following certificates:

- cert.pem
- chain.pem
- fullchain.pem
- privkey.pem

Is there a way the NGINX config can work with this folder structure out of the box?

**Comment by langhard** [comment]
If you are working with docker. Have a look at: https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/.

**Comment by jwilder** [comment]
Closing this since https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ works already.
