### ISSUE TITLE
502 to docker-gitlab w/ docker-compose

### ISSUE THREAD

**Issue by minskmaz** [jwilder/nginx-proxy#548]
Attempting to configure nginx-proxy to handle docker-gitlab
I'm only getting 502's so I've posted the stdout and docker-compose here:

https://gist.github.com/minskmaz/4a741f733cc90ae63aad00220d9e646c

Obviously I'm not doing this right - suggestions welcomed.

**Comment by wader** [comment]
Hi, can you post the generated nginx default.conf?

My guess is that `VIRTUAL_PORT=10080` should be `VIRTUAL_PORT=80`, when i checked the docs it sounded like `GITLAB_PORT` is the "public" port used when generating URLs but the service will still listen to port 80. Give that a try.

**Comment by wader** [comment]
Close?
