### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by Silvercast** [jwilder/nginx-proxy#550]
Hi,
I'm testing demo example as in documentation on macOS docker-machine 0.8.0, docker 1.12.0. I notice a long delay approx 2~3 seconds to resolve a simple curl request. The request is routed to correct container and I get proper response though. Is it supposed to be like that?

**Comment by wader** [comment]
Hi, what URL are you using? using hostname or IP when testing? If hostname can you try `curl http://<resolved-ip> -H "Host: <hostname>"` and see if it's still slow.

**Comment by sandrodz** [comment]
Mac docker is very slow due to osfx, it has nothing to do with this container. You can find further discussion here: https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076

**Comment by Silvercast** [comment]
I just tested 2 cases:
```curl -H "Host: whoami.local" 192.168.99.100```
```curl whoami.local```

the first is superfast while the later has 3 second delay as reported

**Comment by wader** [comment]
Hmm ok, then i would guess this is unrelated to docker. Is resolving with i.e.`host whoami.local` also slow? if not i would suggest to run `curl` with debug/verbose output and see if you can spot what's taking time.

@sandrodz I use mac for docker also but haven't experienced osfx being that slow. Is it slow for specific usages, lots of files, fs notifications etc?

**Comment by sandrodz** [comment]
@wader try to run Symphony app in container on mac, page loads are 20sec+, similarly ROR. wordpress and other mini things work fine.

**Comment by wader** [comment]
@sandrodz ah ok! i mostly run golang stuff in docker

**Comment by Silvercast** [comment]
turn out `host` command look up from `/etc/resolv.conf` on OSX and it couldn't resolve DNS because I modified `/etc/hosts` instead. However, `ping whoami.local` works. CURL could suffer same issue. No idea how to fix it yet...

**Comment by Silvercast** [comment]
Let's blame curl and close this as not a bug. Hope info here helps someone.
