### ISSUE TITLE
Cannot proxy netdata

### ISSUE THREAD

**Issue by tynor88** [jwilder/nginx-proxy#556]
Hi,

Thanks for a great docker. I've succesfully proxied alot of my docker containers and it worked flawlessly until i tried to proxy Netdata docker (https://github.com/titpetric/netdata)

The service (webpage) is running on port 19999. It exposes that particular port in the [Docker file](https://github.com/titpetric/netdata/blob/master/Dockerfile#L10). 

I've added the VIRTUAL_PORT, VIRTUAL_HOST, LETSENCRYPT_HOST and LETSENCRYPT_MAIL variables to the docker, so the docker run looks like this:

`
docker run -d --name="Netdata" --net="bridge" -e TZ="Europe/Paris" -e HOST_OS="unRAID" -e " VIRTUAL_HOST"="subdomain.mydomain.com" -e "LETSENCRYPT_HOST"="subdomain.mydomain.com" -e "LETSENCRYPT_EMAIL"="my@mail.com" -e "VIRTUAL_PORT"="19999" -p 19999:19999/tcp -v "/proc":"/host/proc":ro -v "/sys":"/host/sys":ro --cap-add SYS_PTRACE titpetric/netdata
`

I've tried using _--expose 19999_ as well as part of the _docker run_ with no luck. I'm using a similar configuration on 5 other docker containers (just a different subdomain), and they all work fine.

Nothing is being added to **default.conf**. I see alot of errors in the log with the service being unavailable:

> "Invalid response from http://subdomain.mydomain.com/.well-known/acme-challenge/rHVflldnEh1NCfRMYrO5aq3205FNw65wKHvKlCLab3U: \\"\\u003chtml\\u003e\\r\\n\\u003chead\\u003e\\u003ctitle\\u003e503 Service Temporarily Unavailable\\u003c/title\\u003e\\u003c/head\\u003e\\r\\n\\u003cbody bgcolor=\\"white\\"\\u003e\\r\\n\\u003ccenter\\u003e\\u003ch1\\u003e503 Service Tempora

Any ideas?

**Comment by wader** [comment]
I tried to copy the command and noticed when i pasted that there is a whitespace after `-e "` for `VIRTUAL_HOST`. Maybe just formatting? but then it should not have done a line break?

**Comment by tynor88** [comment]
Great find! I was struggling for 3 hours with this issue - i feel really stupid right now. It was indeed the whitespace in the variable name. Thanks for the help!
