### ISSUE TITLE
How to proxy a container which is running with --net="host"

### ISSUE THREAD

**Issue by tynor88** [jwilder/nginx-proxy#557]
This is probably not an issue, but rather a question.

My nginx-proxy is running in **bridge** mode, but I have a container OpenVPN AS (https://github.com/linuxserver/docker-openvpnas) which has to run in **host** mode in order to work properly.

How would I do that? Right now the nginx-proxy cannot find the service on the specified port as it's running on another virtual network. I've tried connecting nginx-proxy to the host network with: 
`docker network connect host nginx-proxy
`
But then i get this error: 
> Error response from daemon: Container cannot be disconnected from host network or connected to host network

This doesn't seem like the right way either. How would one do this?

**Comment by wader** [comment]
Hmm as i understand containers with host network can't be connected to anything else, but i might be wrong.

I did some tests and a maybe a bit too crazy workaround it to run a "dummy" container that just forwards from the container to a host port.
```
docker run --rm --expose 80 --net=<nginx-proxy-network> -e VIRTUAL_HOST="<hostname>" debian bash -c 'apt-get update && apt-get install -y socat && exec socat tcp-listen:80,fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):<port-that-openvpnas-webserver-listens-on>'
```
But this require that the openvpnas webserver listens on any interface on the host. Also i guess you would like to create a Dockerfile instead of adhoc run command.

If the nginx-proxy container could know its gateway IP somehow you could probably get a away with just some nginx proxy_pass config but I can't figure any way of doing that.

**Comment by tynor88** [comment]
Thanks @wader. This workaround seems to work. I did finally get it to work with some slight changes. I didn't tell you that the web interface is only listening on https connections, so i ran the docker with this run command: 
`docker run --rm --expose 443 --net="bridge" -p 9445:443 -e VIRTUAL_HOST="subdomain.domain.com" -e VIRTUAL_PROTO="https" -e VIRTUAL_PORT="443" -e LETSENCRYPT_EMAIL="my@mail.com" -e LETSENCRYPT_HOST="subdomain.domain.com" debian bash -c 'apt-geupdate && apt-get install -y socat && exec socat tcp-listen:443,fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):943'`

I will eventually create a seperate docker for this hacky workaround, until a better solution will be found :+1:

**Comment by wader** [comment]
😄👍 a bit strange but it works. I guess putting it in a Dockerfile make it a bit nicer... but yeah something else is probably better

**Comment by wader** [comment]
Close?

**Comment by tynor88** [comment]
Yes i will close this. I created a socat docker btw which can be found here: https://github.com/tynor88/docker-socat

**Comment by rahulhada** [comment]
> Hmm as i understand containers with host network can't be connected to anything else, but i might be wrong.
> 
> I did some tests and a maybe a bit too crazy workaround it to run a "dummy" container that just forwards from the container to a host port.
> 
> ```
> docker run --rm --expose 80 --net=<nginx-proxy-network> -e VIRTUAL_HOST="<hostname>" debian bash -c 'apt-get update && apt-get install -y socat && exec socat tcp-listen:80,fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):<port-that-openvpnas-webserver-listens-on>'
> ```
> 
> But this require that the openvpnas webserver listens on any interface on the host. Also i guess you would like to create a Dockerfile instead of adhoc run command.
> 
> If the nginx-proxy container could know its gateway IP somehow you could probably get a away with just some nginx proxy_pass config but I can't figure any way of doing that.

Do we have any other alternative to solve this issue or we have go with the same workaround?
