### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by richburdon** [jwilder/nginx-proxy#578]
Is is possible to use nginx-proxy to configure OAuth2 authentication to upstream services? (e.g., internal admin servers like Celery Flower that I want to secure)?

Or is this out of scope? Should I configure an additional server (VIRTUAL_HOST) that proxies requests to something like: https://github.com/bitly/oauth2_proxy

**Comment by jwilder** [comment]
`nginx-proxy` just proxies to docker containers.  Proxying to an `oauth2_proxy` container seems like it should work though.
