### ISSUE TITLE
ssl_session_tickets off results in an SSL handshake error

### ISSUE THREAD

**Issue by tevjef** [jwilder/nginx-proxy#580]
A change in commit 87879c1 `ssl_session_tickets off` causes a handshake error in latest versions of Chrome 53 and Firefox 50. I was able to establish a ssl connection in Internet Explorer, Safari and curl. I'm no expert in this area, but I did a little wireshark sniffing and found that both Chrome and Firefox closed the connection after an SSL Alert sent by the browsers

Firefox and Chrome
`192.168.1.112	   XXX.XXX.XXX.XX  TLSv1.2  Client Key Exchange, Change Cipher Spec, Hello Request, Hello Request`
`XXX.XXX.XXX.XX	   192.168.1.112	TLSv1.2	New Session Ticket, Change Cipher Spec, Encrypted Handshake Message`
`192.168.1.112	   XXX.XXX.XXX.XX	TLSv1.2   Encrypted Alert`
`TCP FIN`

Removing `ssl_session_tickets off` or setting it on works, but curiously, my other servers are functioning just fine with `ssl_session_tickets off`

Moreover `ssl_session_tickets off` is not required to get an A+ rating

**Comment by chulkilee** [comment]
For the record:

- Chrome: `ERR_SSL_PROTOCOL_ERROR`
- Firefox: `SSL_ERROR_RX_UNEXPECTED_NEW_SESSION_TICKET`
- Ruby: `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0
state=SSLv3 read finished A: unexpected message`

**Comment by chulkilee** [comment]
I confirmed that #581 fixes this problem. Until that's merged, you can mount the fixed template at `/app/nginx.tmpl`

**Comment by freakinruben** [comment]
strange! `ssl_session_tickets off` works fine here

It's also not really recommended to turn `ssl_session_tickets` on, see https://wiki.mozilla.org/Security/Server_Side_TLS#TLS_tickets_.28RFC_5077.29

[This comment](https://community.letsencrypt.org/t/errors-from-browsers-with-ssl-session-tickets-off-nginx/18124/5) explains that 
>  if you have 2 server configurations and and you have ssl_server_tokens set to on in one, it will break the one where it's set to off in certain browsers

Maybe that's what's going on?

**Comment by chulkilee** [comment]
@freakinruben I think so. #581 fixed this by adding missing `ssl_session_tickets off;` to default site, which did not have that.

**Comment by MelwinKfr** [comment]
In my case I had to add `ssl_session_tickets off;` directly into the http{} block as it is said in the comment linked so I mounted `/etc/nginx/conf.d` and added a file which contains this awesome setting.
