### ISSUE TITLE
SSL configuration with nginx

### ISSUE THREAD

**Issue by joeyhipolito** [jwilder/nginx-proxy#601]
I've been struggling to setup my ssl certificate with nginx-proxy,. it is always giving me `site can't be reached` and `502` and `503` errors.

Here are the commands I've tried so far

    docker run --name proxy -d -p 80:80 -p 443:443 -v /home/foo/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy:latest

    docker run --name www -d -p 81:80 -e VIRTUAL_HOST=foo.bar -v /var/www:/usr/share/nginx/html:ro nginx:latest

tried this as well

    docker run --name www -d -p 81:80 -e VIRTUAL_HOST=foo.bar -e VIRTUAL_PROTO=https -v /var/www:/usr/share/nginx/html:ro nginx:latest

and this one

    docker run --name www -d -p 81:80 -e VIRTUAL_HOST=foo.bar -e VIRTUAL_PROTO=https -e VIRTUAL_PORT=443 -v /var/www:/usr/share/nginx/html:ro nginx:latest

Still no luck..

Here's the result of this command `docker exec -it proxy cat /etc/nginx/conf.d/default.conf`

    proxy_set_header Proxy "";
    server {
            server_name _; # This is just an invalid value which will never trigger on a real hostname.
            listen 80;
            access_log /var/log/nginx/access.log vhost;
            return 503;
    }
    upstream foo.bar {
                                    ## Can be connect with "bridge" network
                            # site
                            server 172.17.0.2:443;
    }
    server {
            server_name foo.bar;
            listen 80 ;
            access_log /var/log/nginx/access.log vhost;
            location / {
                    proxy_pass https://foo.bar;
            }
    }

What could possibly the erratic step?

**Comment by wader** [comment]
Hi, how does the config look when you use `docker run --name www -d -p 81:80 -e VIRTUAL_HOST=foo.bar -v /var/www:/usr/share/nginx/html:ro nginx:latest`? you should only need to use `VIRTUAL_PROTO=https` and `VIRTUAL_PORT=443` if nginx-proxy should talk https (on port 443) to the proxied container. In your case i guess you want to terminate https at nginx-proxy and then talk unencrypted http to the containers?

I see that you publish port 81 for the container, does it respond correct if you talk to it directly?

Anything interesting in the nginx-proxy logs?

**Comment by joeyhipolito** [comment]
Hello wader,

here's the config looks like without `VIRTUAL_PROTO` and `VIRTUAL_PORT`

    server {
            server_name _; # This is just an invalid value which will never trigger on a real hostname.
            listen 80;
            access_log /var/log/nginx/access.log vhost;
            return 503;
    }
    upstream foo.bar {
                                    ## Can be connect with "bridge" network
                            # www
                            server 172.17.0.2:80;
    }
    server {
            server_name foo.bar;
            listen 80 ;
            access_log /var/log/nginx/access.log vhost;
            location / {
                    proxy_pass http://foo.bar;
            }
    }

Yes, I published port 81, if I access it directly ie. `http://foo.bar:81` it'll have the same content as `http://foo.bar`

**Comment by wader** [comment]
So `http://foo.bar:81` works, no error and you get some content but `http://foo.bar` gives error? If so can you try:
```
docker exec -ti <nginx-proxy-container> bash
apt-get update && apt-get install curl
curl -H "Host: foo.bar" http://172.17.0.2:80
```

Do you see the request in the nginx-proxy log?

**Comment by joeyhipolito** [comment]
No actually with that docker command i've run, earlier, both works, what I am trying to make work is

`https://foo.bar`

**Comment by wader** [comment]
Ah ok, what cert files do you see in the container?
`docker exec <nginx-proxy-container> ls -l /etc/nginx/certs`

**Comment by joeyhipolito** [comment]
I can the see `foo.bar.cert`

**Comment by wader** [comment]
No `.key` file? both certificate and key is needed (see https://github.com/jwilder/nginx-proxy#ssl-support)

**Comment by joeyhipolito** [comment]
Oh cool!, that is why!, it now works great!!! I'll close the issue, thanks a lot!!
