### ISSUE TITLE
Cant' access files in a symlinked folder

### ISSUE THREAD

**Issue by rowino** [jwilder/nginx-proxy#602]
Whenever I create a symlinked folder in the root of a site served using nginx-proxy, I get a 404 when trying to access it or any file within it. I don't get the same problem when I use plain nginx or another server. Has anyone else faced this problem, do you have a solution for it? turning symlink on in the config doesn't make any difference. Thanks for the help

**Comment by wader** [comment]
Hi, does the symlink point "outside" the nginx-proxy container?

**Comment by rowino** [comment]
Thanks @wader you question solved my problem :). In one of the instances, the second folder is not synced into the container so effectively the folder doesn't exist, in another the link was created in the host and had absolute paths instead of relative paths so failed. Thanks :)
