### ISSUE TITLE
start nginx-proxy on other port than 80

### ISSUE THREAD

**Issue by abipit** [jwilder/nginx-proxy#610]
Hello, 

Is it possible to have nginx-proxy on other port than 80 ?
Because on my host I've already an apache with websites. I want to keep it and have an docker with this nginx-proxy with subdomain.

I tested with port 81 : 
docker run -d -p 81:80 --name nginx-proxy -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy

But when I run my application with : -e DEFAULT_HOST=subdomain.domain.com
it doesn't work.

Is that clear ?
Is it possible ?
Thank you

**Comment by wader** [comment]
Hi, `-p 81:80`should work. But i think you should use `VIRTUAL_HOST=subdomain.domain.com` if this is the env for the container. `DEFAULT_HOST ` is a env variable for the nginx-proxy container telling it to which container to route unknown hostnames.

**Comment by abipit** [comment]
Yes @wader thank you.
It's a bad copy/paste, I ran my application with `-e VIRTUAL_HOST=subdomain.domain.com`

I remark in the file : /etc/nginx/conf.d/default.conf that are no servers in the upstream section but I see my subdomain.domain.com.

The error if i want reload nginx : 
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:36

**Comment by wader** [comment]
Ok, that i usually a sign that nginx-proxy and your application container is not connected to a common network. Have a look at https://github.com/jwilder/nginx-proxy#multiple-networks

**Comment by abipit** [comment]
Hum thank you, but same network 172.17.0.26 & 172.17.0.29 for my 2 containers.

**Comment by abipit** [comment]
Ok I think it's my old version of docker the problem.
On my centos 6.8, the maximum is docker 1.7.1 :(
