### ISSUE TITLE
Reload template

### ISSUE THREAD

**Issue by JulienFauconnier** [jwilder/nginx-proxy#616]
How to reload the template ?

I made some modifications inside (remove TLS1, and some other things) but after restart the container corresponding to my website, nothing change when I test it with Mozilla Observatory.

**Comment by wader** [comment]
Changing files inside the container is probably not a good idea.

I think the two most common ways is to create your own derived docker image (ex: `FROM nginx-proxy` `COPY /myfile /file/to/overwrite`, ...) or use the standard image and override by volume mouth path or files from the host.

**Comment by JulienFauconnier** [comment]
> or use the standard image and override by volume mouth path or files from the host.

Yep, it's exactyle what I've done to edit this file, so that's not the issue ;)

**Comment by wader** [comment]
Ok! what file did you volume mount? template or default.conf? default.conf will be overwritten by docker-gen on container changes.

**Comment by JulienFauconnier** [comment]
Template, I don't need to touch default.conf

**Comment by wader** [comment]
So `-v /host/path/my_nginx.tmpl:/app/nginx.tmpl`? can you give more information about your setup? like full docker commands if your using one or separate docker-gen container?

**Comment by JulienFauconnier** [comment]
> -v /host/path/my_nginx.tmpl:/app/nginx.tmpl
Nop, the entire vhost folder is mounted :)


One container for nginx (from jwilder of course),
with letsencrypt-nginx-proxy-companion to auto generate my certificates (that's why I mount the vhost folder).

And I'm using docker-compose to launch my containers, not one for all, but one for nginx, one for the companion, and one for each of my services (websites, etc)

**Comment by wader** [comment]
That is weird. So from inside the container you can see your modified template but the generated default.conf does not have your changes?

**Comment by JulienFauconnier** [comment]
Finally it's my mistake, dont know why but I was having a nginx.tmpl fil in my `/etc/nginx/` folder, 
but only the subfolders `certs` and `vhost` was linked to the nginx container.

Now it's perfectly fine, thank you a lot for your help :)
