### ISSUE TITLE
Question: reverse proxy for openvpn?

### ISSUE THREAD

**Issue by tmtben** [jwilder/nginx-proxy#620]
Hi,

How could I use jwilder/nginx-proxy image to access multiple vpn servers by hostname using the same port?

Thanks,
Ben

**Comment by jwilder** [comment]
It's not designed to proxy vpn traffic so I'm not sure how you could use it for that.

**Comment by tmtben** [comment]
Please have a look here:
http://stackoverflow.com/questions/34741571/nginx-tcp-forwarding-based-on-hostname
