### ISSUE TITLE
Reverse proxy for OpenVPN

### ISSUE THREAD

**Issue by tmtben** [jwilder/nginx-proxy#624]
Hi,

How could I use jwilder/nginx-proxy image to access multiple vpn servers by hostname using the same port?

Please have a look here:
http://stackoverflow.com/questions/34741571/nginx-tcp-forwarding-based-on-hostname

Thanks,
Ben

**Comment by jwilder** [comment]
You already asked this the other day: #620.  Using your link you could create a [custom template](https://github.com/jwilder/nginx-proxy#custom-nginx-configuration) possibly.  As I said before though, this project was not designed to proxy vpn traffic so I'm not sure if it would work or not.
