### ISSUE TITLE
Create subdirectory instead of subdomain

### ISSUE THREAD

**Issue by peperunas** [jwilder/nginx-proxy#635]
Is it possible to put a site on a subdirectory instead of a subdomain?

e.g:

from `mysite.example.org/` to `example.org/mysite`

Thanks!

**Comment by jwilder** [comment]
No.  Not currently.

**Comment by desimaniac** [comment]
Is this still the case ?

**Comment by yivi** [comment]
This answer is two years old, but I guess there were no changes on this, right?

**Comment by KrzysztofMadejski** [comment]
Duplicate of #47 and #190
