### ISSUE TITLE
laravel has issues with proxy_set_header X-Forwarded-Proto https 

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#636]
I've a following config:

`<client> <ssl nginx = nginx-proxy + letsencrypt companion > <80 nginx> <laravel>`
laravel has a method called `asset()` which is supposed to detect schema and output correct url. But it doesn't, I asked question on stackoverflow - but its clear it is not php issue, but something with server.

My hunch is that <ssl nginx> is not passing some vital information to <80 nginx>.

Can I add something to <80 nginx> virtualhost config so that it thinks request came from https? (client came from https, but laravel doesn't see this it sees only <80 nginx>).

I tried to add `proxy_set_header X-Forwarded-Proto https` to virtualhost config, but it didn't change anything.

**Comment by jwilder** [comment]
This seems to be an issue with your second nginx config and larval which is not part of this project.

**Comment by sandrodz** [comment]
Yes, I resolved it by modifying second nginx config. And setting https on; manually based on `proxy_set_header X-Forwarded-Proto https` info from nginx-proxy.
