### ISSUE TITLE
$CurrentContainer line doesn't work in custom template - is this a docker-gen bug?

### ISSUE THREAD

**Issue by JonasT** [jwilder/nginx-proxy#637]
I'm using an own template, and I recently tried to update it for docker-compose V2 with https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl

However, when just adding those two lines in the beginning:

```
{{ $CurrentContainer := where $ "ID" .Docker.CurrentContainerID | first }}

# GENERATING CONTAINER: name: {{ $CurrentContainer.Name }},  id: {{ $CurrentContainer.ID }}
```

.. the result will start with:
```
# GENERATING CONTAINER: name: <no value>,  id: <no value>
```
Similarly, $CurrentContainer.Networks seems to be empty, so that I cannot adapt the loop at all.

I am using the latest docker-gen image (tag "latest"), so is there some obvious reason why this wouldn't be working? I assume this is most likely still my own error, but I cannot really figure out why it wouldn't work given the line is taken unmodified from https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl and right at the beginning...

**Comment by wader** [comment]
Hmm could it be https://github.com/jwilder/nginx-proxy/pull/459? docker-gen with `-only-exposed`  running in container with no exposed ports

**Comment by JonasT** [comment]
Oh yea, most definitely, I remember that parameter - and I upgraded the image for years, but never the parameters.
I also know a lot of other people who didn't do this, whom I'm gonna notify about this so they don't run into the same issue :smile: thanks for the explanation.

**Comment by wader** [comment]
No problem 👍
