### ISSUE TITLE
ajax xhr 500 internal server error

### ISSUE THREAD

**Issue by orboan** [jwilder/nginx-proxy#639]
Hello,
why javascript in a nginx-proxified kevana/ui-for-docker does not work?
Any workaround?
Updated: As you can see in a screencap below from the developer web console, this is an issue regarding an ajax xhr 500 internal server error. Please help me to find a solution
Thanks

**Comment by wader** [comment]
Hi, in what way does it not work? what error do you see where?

**Comment by orboan** [comment]
Please see caps. First is proxyfied, second, not.
<img width="895" alt="proxyfied" src="https://cloud.githubusercontent.com/assets/7423107/20621782/20f80122-b300-11e6-9c87-811765aaf2ec.PNG">
<img width="895" alt="not-proxyfied" src="https://cloud.githubusercontent.com/assets/7423107/20621783/20f8346c-b300-11e6-8ebe-e10fdc1bc7c9.PNG">

**Comment by wader** [comment]
Can you check developer console for errors? i suspect it fails to load scripts etc

**Comment by orboan** [comment]
Checking with developer console I get:
<img width="960" alt="error2" src="https://cloud.githubusercontent.com/assets/7423107/20623369/8aaf8246-b307-11e6-8dd5-eb93685a9937.PNG">
<img width="956" alt="error1" src="https://cloud.githubusercontent.com/assets/7423107/20623370/8ab016ac-b307-11e6-8100-bba91205fbf2.PNG">

**Comment by orboan** [comment]
If I edit the latest GET and change the port (from 80 -proxyfied- to 9090 -not proxyfied-) then that GET gets a 200 response.
<img width="960" alt="error3" src="https://cloud.githubusercontent.com/assets/7423107/20623495/1e2392d8-b308-11e6-8dfa-de1b9871535d.PNG">

**Comment by orboan** [comment]
You can also follow his issue up here: 
https://github.com/kevana/ui-for-docker/issues/260

**Comment by orboan** [comment]
Hello, 
Please read what I have found playing around with apache. This may be also applicable to nginx:

I have configured a reverse proxy with apache2. I've used apache because I have better knowlege of it than of nginx

My reverse  proxy WORKING configuration with apache is:
ProxyRequests Off
ProxyHTMLEnable On
ProxyPass /dockerui/ http://labs.orboan.com:9090/
ProxyPassReverse /dockerui/ http://labs.orboan.com:9090/
ProxyHTMLURLMap http://labs.orboan.com /dockerui/
<Location /dockerui/>
ProxyPassReverse /
SetOutputFilter  proxy-html
ProxyHTMLURLMap http://labs.orboan.com:9090 /dockerui/
ProxyHTMLURLMap / /dockerui/
ProxyHTMLURLMap /dockerui/ /dockerui/
RequestHeader    unset  Accept-Encoding
</Location>

But I have to explicitly add a trailing slash at the end of the URL. But it works: the AJAX xhr requests work fine and all docker-ui website functions as expected.

BUT, if I add these next two rewrite lines, with the goal of not having to explicitly adding a trailing slash at the end of the URL:

RewriteEngine On
RewriteCond %{REQUEST_URI} !(/$|\.)
RewriteRule (.*) %{REQUEST_URI}/ [R=301,L]

Then, the ajax xhr requests do not work, ie dynamic elements of the web site are not working, as in the previous screen cap. THIS IS THE SAME BAD BEHAVIOR as with this NGINX docker image. THUS, it is plausible to conclude this docker nginx reverse proxy has some not adequate configuration with redirection that causes the problem with xhr requests and https://github.com/kevana/ui-for-docker not working.

Please, I hope you can fix it with the new information I provide here. Thanks.

**Comment by jwilder** [comment]
See this [comment](https://github.com/kevana/ui-for-docker/issues/204#issuecomment-216364460) for details, but looks like the proxy connection header needs to be set differently.

This works for me.

```bash

mkdir /tmp/hosts && echo "proxy_set_header Connection $http_connection;" > /tmp/hosts/foo.local_location
docker run -it -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro -v /tmp/hosts:/etc/nginx/vhost.d jwilder/nginx-proxy
docker run -e VIRTUAL_HOST=foo.local -p 9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock uifd/ui-for-docker
```

**Comment by orboan** [comment]
Thanks. In order to make your wordaround work, I needed to change the double quotes " by single ', thus to make this work, the first line you wrote should be
`mkdir /tmp/hosts && echo 'proxy_set_header Connection $http_connection;' > /tmp/hosts/foo.local_location`
