### ISSUE TITLE
Reverse Proxy non HTTP

### ISSUE THREAD

**Issue by adi90x** [jwilder/nginx-proxy#641]
Hello, 

I just setup a VNC Virtual Desktop ( `consol/centos-xfce-vnc` )  listening on port 5901.
And I was wondering if there is a way to reverse proxy connection ?

What I want is being able to connect to `vnc.foo.com`  to acces my VNC session.
It seems that it is possible to reverse proxy TCP connection with nginx , am I correct ? Is there any solution to do it with `jwilder/nginx-proxy` ?

Any help appreciated !
Regards,

**Comment by jwilder** [comment]
Seems like you could just point your DNS `vmc.foo.com` to your host and connect to it directly.

This project mainly support HTTP(S) reverse proxies so you'd need to use a custom template if you wanted to proxy TCP.
