### ISSUE TITLE
proxy for non-dockerized service

### ISSUE THREAD

**Issue by kosli** [jwilder/nginx-proxy#646]
Hi

I am posting this here too, as if there is a solution here via a "fake" container, it will automatically work with the letsencrypt docker :-)

I am using docker-letsencrypt-nginx-proxy-companion for proxying multiple docker containers, but would like to use it also for an application that is running on another machine, and not in a local docker container.

So for the nginx-proxy part, i can add a custom.conf in the /etc/nginx/conf.d/ directory and the service will be reachable via HTTP. But I couldn't find a way to use it together with the letsencrypt functionality?

Or do you have an idea how i could make a simple "fake" docker container that would force nginx-proxy, and so docker-letsencrypt-nginx-proxy-companion, to proxy to another host?

thanks
KoS

see https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/127

**Comment by wader** [comment]
Hi, i guess you could have a container that is just a tcp proxy

**Comment by kosli** [comment]
@wader thank you very much, i must have been blind :-)
i used a simple socat proxy container: https://github.com/silasdavis/socat-proxy-docker
