### ISSUE TITLE
Can't get anything but the default "Welcome to nginx" page

### ISSUE THREAD

**Issue by ElTimablo** [jwilder/nginx-proxy#658]
HTTPS doesn't work whether I enable it or not and all of my subdomains lead back to that page. I'm starting the container with `docker run -d -p 80:80 -p 443:443 -v /docker/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro --privileged -e VIRTUAL_PROTO=https jwilder/nginx-proxy`, but even when I don't enable HTTPS it displays nothing but the default landing page. The logs don't show any errors at all, either, so I'm kinda lost on what to do here.

**Comment by phelpsiv** [comment]
Do you have any virtual host containers running when you build the nginx-proxy container? I found I had to stop all virtual host containers to get the nginx-proxy working.

**Comment by ElTimablo** [comment]
I'm a silly man, and forgot to start any containers to connect to. Before, I'd get an error page, but I guess the image was updated recently to give me the default landing page. Closed!
