### ISSUE TITLE
My domain on the first container and the same domain on a second container with port

### ISSUE THREAD

**Issue by abipit** [jwilder/nginx-proxy#662]
Hello, 
I explain, is it possible to have this configuration : 

- my domain www.example.com on the containerA : OK
- the same domain + port www.example.com:8888 on the containerB : KO

Is it possible ? I'm not sure. If yes, what is the configuration please ?
Thanks

**Comment by jwilder** [comment]
Only thing I can think of that might work is to run two separate `nginx-proxy` containers using different networks.  Then join both containerA and one nginx proxy bound to port 80 and containerB and the other nginx proxy bound to port 8888.

Never tried this though so you may need to experiment.
