### ISSUE TITLE
Return 503 with valid certificates

### ISSUE THREAD

**Issue by oomathias** [jwilder/nginx-proxy#669]
When a container with HTTPS is down a 503 error is returned with the default certificate even if a valid one exists for this host. So you end up with an SSL error instead of a 503.

I added this at the end of my `nginx.tmpl` to handle this case.

```nginx
{{ $certs := dir "/etc/nginx/certs" }}
{{ range $cert := $certs }}
  {{ if hasSuffix ".key" $cert }}
    {{ $host := trimSuffix ".key" $cert }}
    {{ if eq (whereAny $ "Env.VIRTUAL_HOST" "," (split $host ",") | len) 0 }}
      {{ if ne $host "default" }}
server {
  server_name {{ $host }};
  listen 443 ssl http2;
  access_log /var/log/nginx/access.log vhost;
  include /etc/nginx/vhost.d/default;
  return 503;

  ssl_session_tickets off;
  ssl_certificate /etc/nginx/certs/{{ (printf "%s.crt" $host) }};
  ssl_certificate_key /etc/nginx/certs/{{ (printf "%s.key" $host) }};
}
      {{ end }}
    {{ end }}
  {{ end }}
{{ end }}
```

So if you have 3 certs (a.domain.com, b.domain.com, c.domain.com) and a.domain.com is NOT found in a VIRTUAL_HOST (host down), it adds a server entry which returns 503 with a valid cert.

Is that something you are interested in? Should I make a pull request?

**Comment by nathang21** [comment]
+1 to this, made initial debugging confusing when setting up my containers.

**Comment by jwilder** [comment]
Would #614 resolve this as well?

**Comment by oomathias** [comment]
@jwilder Yes, for already existing certs.

But I'm not sure what's the problem in #614, since the first hostname in config `_` is already returning a 503 (if there is a default cert). Maybe returning a 444 if there isn't a default cert...

My patch is for down containers with existing certs. If your container crash or is rebooting, you want to serve a 503 with the valid certificate for this domain so the end user can see it.

**Comment by dbrosy** [comment]
hi @oomathias I am trying to do the same as you describe  above. I have added the code to end of nginx.tmpl but it causes error and doesn't give the desired result. Can you give an example of how you added to nginx.tmpl?

**Comment by oomathias** [comment]
@dbrosy I have the default `nginx.tmpl` https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl and I added my script at the end (last line)

What's wrong with the results?

**Comment by dbrosy** [comment]
I get:
 Error running notify command: nginx -s reload, exit status 1

I am pasting your code after last 

{{ end }}

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
