### ISSUE TITLE
Path based upstream

### ISSUE THREAD

**Issue by stephan2012** [jwilder/nginx-proxy#675]
Is there any way to select a backend (upstream) based on the path? In this case (Atlassian Confluence), both upstreams are handled by the same container.

```
[…]
location / {
    […]
    proxy_pass http://upstream.server.domain:8090;
    […]
}

location /subpath {
    […]
    proxy_pass http://upstream.server.domain:8091;
    […]
}
[…]
```

Not sure if #254 deals with the same issue. In case it does please just close this issue.

**Comment by jwilder** [comment]
Not currently.  #254 is intended to address that.
