### ISSUE TITLE
Gitlab crashed because of proxy_pass

### ISSUE THREAD

**Issue by RaphaelJenni** [jwilder/nginx-proxy#677]
I updated the nginx-proxy and suddenly the url of my gitlab was changed to 
https://6ad65ad95ad9f5ad9f5adfa131a65d16f1a

This is set in the conf.d/default.conf under each server in the location section.
Please make that optional or find a different way to solve that problem.

**Comment by jwilder** [comment]
Likely #671 caused this. cc @thomasleveil 

Can you provide the conf file it's generating?  I assumed this change was basically an internal change and you would not see it in the backends or anywhere else.

**Comment by RaphaelJenni** [comment]
This is my `default.conf` file. I hope it helps.


[default.conf.txt](https://github.com/jwilder/nginx-proxy/files/703720/default.conf.txt)

**Comment by thomasleveil** [comment]
Hi could you share the contents of:
/etc/nginx/vhost.d/jenkins.domain1.tdl
And
/etc/nginx/vhost.d/default

Please?

Le ven. 13 janv. 2017 à 08:14, RaphaelJenni <notifications@github.com> a
écrit :

This is my default.conf file. I hope it helps.

default.conf.txt
<https://github.com/jwilder/nginx-proxy/files/703720/default.conf.txt>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jwilder/nginx-proxy/issues/677#issuecomment-272376879>,
or mute the thread

**Comment by RaphaelJenni** [comment]
**/etc/nginx/vhost.d/default**
```
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
proxy_http_version 1.1;
proxy_set_header Connection "";

client_max_body_size 1g;
```


**/etc/nginx/vhost.d/jenkins.domain1.tdl**
```
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;

```

**Comment by cncolder** [comment]
I have same issue.

My `/etc/nginx/conf.d/default.conf` show me

```nginx
# xydy-api
upstream a63b14ddf4713d369912433c253994eade99472b {
				## Can be connect with "edu-stage_default" network
			# edu-stage_xydy-api_1
			server 172.18.0.6:8000;
				## Can be connect with "edu-stage_default" network
			# edu-stage_xydy-api_2
			server 172.18.0.2:8000;
}
server {
	server_name xydy-api;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://a63b14ddf4713d369912433c253994eade99472b;
	}
}
```

I only put one custom config in `/etc/nginx/vhost.d/example.com`

```nginx
location ^~ /api/ {
	rewrite '^/api/(.*)$' /$1 break;
	proxy_pass http://xydy-api;
	add_header Cache-Control 'no-store';
}
```

**Comment by thomasleveil** [comment]
can you show the result of the command: `docker exec <your nginx-proxy container> nginx -s reload`

**Comment by RaphaelJenni** [comment]
I run now an older version, because of downtime. But maybe @cncolder can help you with that.

**Comment by cncolder** [comment]
```bash
> docker exec edu-stage_proxy_1 nginx -s reload
2017/01/13 10:04:31 [notice] 35#35: signal process started
```

**Comment by cncolder** [comment]
I'm not understand what gram used in `nginx.tmpl`. But I think this issue come from <https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L95-L97>

That very long upstream name `a63b14ddf4713d369912433c253994eade99472b` in my config is `sha1 $host`

Is this a new feature or mistake?

**Comment by thomasleveil** [comment]
I created test case files for both cases: 
https://github.com/thomasleveil/nginx-proxy/tree/issue-677-RaphaelJenni
https://github.com/thomasleveil/nginx-proxy/tree/issue-677-cncolder

but running those, I cannot reproduce any error with nginx.

@cncolder the very long upstream names are made on purpose

**Comment by cncolder** [comment]
@thomasleveil Yes. No nginx error for me. Except `vhost.d/*`

I have two container. One for example.com with `VIRTUAL_HOST=example.com`. Another for example.com/api with `VIRTUAL_HOST=xydy-api`.
I want to rewrite example.com/api/* then proxy pass to xydy-api.
So I put a vhost config.

```nginx
# /etc/nginx/vhost.d/example.com

location ^~ /api/ {
	rewrite '^/api/(.*)$' /$1 break;

	# This not work after upgrade to new nginx-proxy version
	# proxy_pass http://xydy-api;

	# SHA1 style host name
	# echo -n xydy-api | shasum
	proxy_pass http://a63b14ddf4713d369912433c253994eade99472b;
}
```

I think we need add document about this.

**Comment by thomasleveil** [comment]
So to sum up, it is not that the vanilla nginx-proxy isn't working, but rather customized configs which need to be adapted.

**Comment by RaphaelJenni** [comment]
I don't have a custom config. Gitlab uses a own nginx server. But this one is running behind the proxy. But I don't have enough experience in this topic to help you.

**Comment by thomasleveil** [comment]
@RaphaelJenni can you give a try to image [tomdesinto/nginx-proxy:issue-677](https://github.com/thomasleveil/nginx-proxy/tree/issue-677). In this image, if you don't use regular expressions for matching your hosts, then it will behave as before #671

**Comment by RaphaelJenni** [comment]
@thomasleveil This image is working.

**Comment by Kiina** [comment]
https://github.com/sameersbn/docker-gitlab/issues/1062

I have the same issue. Thought it was a gitlab problem because it was the same day I changed my gitlab config. Had set X-Forwarded-Ssl in my vhost.d and removing the file worked for me.

**Comment by thomasleveil** [comment]
#679 is now merged. @RaphaelJenni this should be fixed

**Comment by RaphaelJenni** [comment]
Thanks. I will test it and then if it works, close the issue.

**Comment by RaphaelJenni** [comment]
It works now. Thanks @thomasleveil for your help and for the fix 👍
