### ISSUE TITLE
Manually specify configuration

### ISSUE THREAD

**Issue by TroelsL** [jwilder/nginx-proxy#678]
What is the correct (if such a thing exists) way of doing the following:

I have nginx-proxy setup and working with letsencrypt-nginx-proxy-companion.

Now I have two sets of services:

1. Docker containers that should be using HTTPS only and should therefore be using letsencrypt. I'll add the environment variables as usual.
2. Other services (mostly docker containers) that I imagine I need to define manually. An example:

server {
        listen 80;
        server_name unifi.local;
        location / {
                proxy_pass http://192.168.1.101:8080;
                proxy_buffering off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                auth_basic "Restricted";
                auth_basic_user_file /etc/nginx/.htpasswd;
        }
}

In my current (vanilla nginx) setup, everything is is in one messy default.conf. But I assume that this is autogenerated and overwritten with the proxy. Where do I keep this manual configuration now? I tried mounting and putting it in conf.d, but that doesn't seem to work.

**Comment by thomasleveil** [comment]
create a file named _unifi.local.conf_ with:

    server {
    	listen 80;
    	server_name unifi.local;
    	location / {
    		proxy_pass http://192.168.1.101:8080;
    		proxy_buffering off;
    		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		auth_basic "Restricted";
    		auth_basic_user_file /etc/nginx/.htpasswd;
    	}
    }

now add this file to the nginx-proxy container with a volume:

    docker run .... -v /somewhere/unifi.local.conf:/etc/nginx/conf.d/unifi.local.conf:ro jwilder/nginx-proxy

**Comment by TroelsL** [comment]
I've mounted the entire /conf.d directory, and for reasons I can't quite explain. It works after creating a new file. There were no errors in the log, and I'm 99% sure I had restarted the container after adding the file. I guess it must've been the 1% that got me.

I'm glad to hear that I had understood it correctly. It seems like a very logical place to do it.

Thanks for the help!

**Comment by JohnAllen** [comment]
Is there a reason for the filename: `unifi.local.conf`?

**Comment by TroelsL** [comment]
@JohnAllen It should be the same as your hostname. I used unifi.local in my question, which is why @thomasleveil also used it. It might also have been unifi.example.com or even just unifi, depending on your DNS settings.
