### ISSUE TITLE
Add Basic Authentication support

### ISSUE THREAD

**Issue by albestia** [jwilder/nginx-proxy#68]
Hi, I've forked you and I'm working on add Basic Authentication support.
My idea is to use /etc/nginx/htpasswd/ dir as a place to put files with VIRTUAL_HOST name. If it's present, enable auth_basic on the virtual host.

It's easy, and I'm nearly done, but I'm having problems with build process.

$ docker build .
Sending build context to Docker daemon 107.5 kB
Sending build context to Docker daemon 
Step 0 : FROM nginx:1.7.8
 ---> e46b3488b010
Step 1 : MAINTAINER Jason Wilder jwilder@litl.com
 ---> Using cache
 ---> 6f27863813de
Step 2 : RUN apt-get update && apt-get install -y -q --no-install-recommends    ca-certificates    wget && apt-get clean && rm -r /var/lib/apt/lists/*
 ---> Running in 8a9d7ed77827
Err http://security.debian.org wheezy/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://http.debian.net wheezy Release.gpg
  Could not resolve 'http.debian.net'
Err http://nginx.org wheezy Release.gpg
  Could not resolve 'nginx.org'
Err http://http.debian.net wheezy-updates Release.gpg
  Could not resolve 'http.debian.net'
Reading package lists...
W: Failed to fetch http://http.debian.net/debian/dists/wheezy/Release.gpg  Could not resolve 'http.debian.net'

W: Failed to fetch http://http.debian.net/debian/dists/wheezy-updates/Release.gpg  Could not resolve 'http.debian.net'

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://nginx.org/packages/mainline/debian/dists/wheezy/Release.gpg  Could not resolve 'nginx.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ca-certificates
E: Unable to locate package wget
2014/12/16 20:52:36 The command [/bin/sh -c apt-get update && apt-get install -y -q --no-install-recommends    ca-certificates    wget && apt-get clean && rm -r /var/lib/apt/lists/*] returned a non-zero code: 100

For sure I'm doing something wrong, but unable to find it.

Sorry for my unknowledge.

**Comment by Nitesedge** [comment]
Any progress with this? I am looking to do the same thing. I would love to see this implemented and pushed back into the repo. If you haven't solved it can you share your changes, progress, and issues so I can contribute?

**Comment by albestia** [comment]
I've got it on my fork if you want to play with.

https://github.com/albestia/nginx-proxy

Keep me informed of any bug/issue you detect.
Thanks in advance.

2015-01-14 14:43 GMT+01:00 Nitesedge <notifications@github.com>:

> Any progress with this? I am looking to do the same thing. I would love to
> see this implemented and pushed back into the repo. If you haven't solved
> it can you share your changes, progress, and issues so I can contribute?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jwilder/nginx-proxy/issues/68#issuecomment-69917197>.
>



-- 
Albert Murillo Aguirre

**Comment by jwilder** [comment]
Fixed via 6d646d92f8d2e7fea8aee54c07c730d948b67c6e
