### ISSUE TITLE
Nginx proxy from Internet to local network

### ISSUE THREAD

**Issue by mprokopov** [jwilder/nginx-proxy#680]
I'm really stuck with following issue, help.

All I want to do is to proxy from outside nginx to local server. For that I use CoreOS with jwilder/nginx-proxy for public accessable container also as for internal one.

I created and mapped proper /etc/conf.d/mysite.conf inside public nginx container with proxy_pass to nginx container on server in the internal network.

```
server {
  server_name neovo.kiev.ua;
  listen 80;
  location / {
    proxy_pass http://192.168.160.71:80;
  }
}
```
and second one nginx parses containers setup via VIRTUAL_HOST neovo.kiev.ua on server 192.168.160.71. This one works correct without any issues if I test like 
```
curl -H 'host: neovo.kiev.ua' http://192.168.160.71 
```

But if I test not on local machine, but on public accessible coreos it always returns 503, Server Unavailable error, despite 192.168.160.71 is accessible from this server.

I really stuck, because this configuration perfectly works with my local Docker on Mac and totally does not work on any other public host.

Do you have any example for reverse proxying nginx to nginx?

**Comment by thomasleveil** [comment]
your config seems good. I would use tcpdump (or wireshark) to capture the network packets while you test. Then inspect the packets that compose your http request to verify that the `Host` header wasn't removed/altered before hitting nginx-proxy

**Comment by mprokopov** [comment]
I'm curious, it it possible to have this issue because of some selinux default network restrictions on CoreOS?
Tcpdump shows that nginx even does not try to make connection to local server, immediately responses with 503 error.

**Comment by thomasleveil** [comment]
Nginx-proxy responds with 503 error if it was not able to determine to which virtual host the http request is for. 

Nginx-proxy finds the virtual host info in the http header 'Host'  of queries, and create its list of known virtual hosts from the VIRTUAL_HOST environment variable of running containers. 

Knowing that, either the http query is missing the 'Host'  header, or the 'Host' header's value is incorrect, or the container which should get the queries is not running, or missing the VIRTUAL_HOST environnement variable, or that environment variable has an incorrect value

**Comment by mprokopov** [comment]
My issue was in specifying comma separated server_name

In that case nginx config did not handle propery server and proxy_pass configuration.
