### ISSUE TITLE
does nginx-proxy sets content type

### ISSUE THREAD

**Issue by edoardoc** [jwilder/nginx-proxy#691]
Hello, 

I am having some hard time trying to understand how nginx-proxy is supposed to handle content-types.
I need to serve an svg file from an application server that does not set type for such files, so I thought nginx could do it for me, but it doesn't work.
I mean, it does work: nginx correctly sets the content type anytime I make it serve *.svg, but the same doesn't apply with nginx-proxy - **it seems nginx-proxy fully ignores /etc/nginx/mime.types** 

I made a small project to show the situation, https://github.com/edoardoc/somesvgtest with a docker-compose two services are started behind the proxy: first one serving svg from another nginx and the second serving it from a go server (that does not set content type).

please have a look.
PS: I also thought that maybe this is an expected behaviour - since nginx-proxy is a proxy it should not be interested in setting content types (?)

**Comment by thomasleveil** [comment]
It is not the responsibility of a _reverse proxy_ to handle such things. However, you can customize the behavior of nginx-proxy by providing your own bit of nginx configuration as described [here](https://github.com/jwilder/nginx-proxy#custom-nginx-configuration).

**Comment by edoardoc** [comment]
fair enough. 
I tried several configuration solutions - the ones described in the nginx-proxy configuration examples and others - but I haven't managed to make it serve svg files.
moreover, everything seems good for that, if you check ```/etc/nginx/nginx.conf``` 

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    server_names_hash_bucket_size 128;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
daemon off;
```

there is ```    include       /etc/nginx/mime.types;```  which in turns declares ```image/svg+xml                         svg svgz;``` among the content types that the proxy should handle.

what is it that I am missing?

**Comment by jinghuaz** [comment]
any update

**Comment by edoardoc** [comment]
closing this issue cause it is the expected behaviour - and it doesn't seem easy to change the nginx-proxy configuration (the nginx.conf files I posted before it is never read, as the mime.types file).. maybe this image needs some cleaning from the base nginx?
