### ISSUE TITLE
503 - Service Unavailable - How to troubleshoot?

### ISSUE THREAD

**Issue by tvedtorama** [jwilder/nginx-proxy#707]
Hi,

I need to test the nginx docker containers on my OSX computer before moving to production.  This involves  the docker-machine setup with a virtual machine.  

I start the nginx and nginx-dev servers and get the default nginx message for my host name, which I set up on my etc/hosts configuration (on the mac). (http://mydockerhost1)

Then I start my image, which I can reach on the host name reach if I add ports (-p) arguments (http://mydockerhost1:3000 works).  When i console into the nginx-volumes I can see that it has modified the config to something like this, when I started my image:

```
# mydockerhost1
upstream bdacd495f8d155c80c0f8ddad3353987c0203bf0 {
}
server {
	server_name mydockerhost1;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://bdacd495f8d155c80c0f8ddad3353987c0203bf0;
	}
}
```

**However the nginx site now displays the 503 Service Temporarily Unavailable error**.  I can't find any errors around the place, but does not know where to look?  The logs of nginx and docker-gen looks ok.

**What should I do to figure out what's wrong?  Is there issues with running this on the docker-machine on a max?**

I start the dockers the following way:

	docker run -d -p 80:80 -p 443:443 \
	    --name nginx \
	    -v /etc/nginx/conf.d  \
	    -v /etc/nginx/vhost.d \
	    -v /usr/share/nginx/html \
	    -v /home/docker/nginx-test/certs:/etc/nginx/certs:ro \
	    nginx

	docker run -d \
	    --name nginx-gen \
	    --volumes-from nginx \
	    -v /home/docker/nginx-test/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
	    -v /var/run/docker.sock:/tmp/docker.sock:ro \
	    jwilder/docker-gen \
	    -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

	docker run -d \
	   --name website \
	   -e "VIRTUAL_HOST=mydockerhost1" \
	   --expose 3000 \
	   tvedtorama/website 

This setup is from the letsencrypt-compainon, which I intend to use - but I guess I have to get the basics running first?

**Comment by bjoernbusch** [comment]
Shouldn't there be a VIRTUAL_PORT=3000  in your dockerhost1?

**Comment by tvedtorama** [comment]
Thank you, I'm not sure. 

My node.js application listens on port 3000, and I expose that port in the commands above.  I want nginx to map it to standard web ports, however.  So that the user will find it on the url without any port specifications.

Do I have to map the port like this "-p 80:3000" on my application?  So nginx can find it there? 

As I said, I can access the app using domain and port specification, when I do "-p 3000:3000", but that must be the app docker directly, I guess?

**Comment by thomasleveil** [comment]
a few things to try in order to troubleshoot:

    docker logs nginx
    docker exec nginx cat /etc/nginx/conf.d/default.conf
    docker exec nginx nginx -s reload

**Comment by bjoernbusch** [comment]
ok, so the readme says it should automatically find the only exposed port and map that into nginx. Can you try changing your command like this anyway?

`docker run -d --name website -e "VIRTUAL_HOST=mydockerhost1" -e VIRTUAL_PORT=3000 --expose 3000 tvedtorama/website `

**Comment by tvedtorama** [comment]
Thank you both!

Putting the VIRTUAL_PORT argument in there did not seem to do anything.

However, I finally got the basics to run, by mangling the example from the letsencrypt-container and in this site.  I can't tell what the minor differences does, but it seems to work now.

Very weirdly this works:

    docker run -d -p 80:80 -p 443:443 --name nginx -v /etc/nginx/conf.d -v /etc/nginx/vhost.d -v /usr/share/nginx/html -v /home/docker/nginx-test/certs:/etc/nginx/certs:ro nginx
    docker run -d --name nginx-gen --volumes-from nginx -v /var/run/docker.sock:/tmp/docker.sock:ro -v /home/docker/nginx-test:/etc/docker-gen/templates -t jwilder/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf 
    
I can then start this:

    docker run -d --name website -e "VIRTUAL_HOST=mydockerhost1" --expose 3000 tvedtorama/website 

or use the nginx-thing, which seems to fail as my domain is local:

	docker run -d \
	    --name nginx-letsencrypt \
	    -e "NGINX_DOCKER_GEN_CONTAINER=nginx-gen" \
	    --volumes-from nginx \
	    -v /home/docker/nginx-test/certs:/etc/nginx/certs:rw \
	    -v /var/run/docker.sock:/var/run/docker.sock:ro \
	    jrcs/letsencrypt-nginx-proxy-companion

then:

	docker run -d \
	   --name website \
	   -e "VIRTUAL_HOST=mydockerhost1.invalid.com" \
	   -e "LETSENCRYPT_HOST=mydockerhost1.invalid.com" \
	   -e "LETSENCRYPT_EMAIL=xyz@gmail.com" \
	   --expose 3000 \
	   tvedtorama/website

**Comment by bjoernbusch** [comment]
So you removed the `-only-exposed` and `-wait 5s:30s` and added `-t`? And you're only mapping the template itself and not the entire directory? Interesting. 🤔

**Comment by tvedtorama** [comment]
I think these args are the only difference, while I don't know what they do.

I did lots of trial and error yesterdays - so it could be that I have confused something in the process.

Not sure what you mean by the "template" comment?

**Comment by bjoernbusch** [comment]
No, sorry, the other way around, you're mounting now the entire folder, where the nginx.tmpl file is in. You changed
`-v /home/docker/nginx-test/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro`
to
`-v /home/docker/nginx-test:/etc/docker-gen/templates`

**Comment by tvedtorama** [comment]
Yes, that's right.  I think I tested both ways yesterdays - but this could be the issue.  I think there was some other github issue that concluded that the folder should be mounted, not the file.
