### ISSUE TITLE
Getting 503 For All Requests

### ISSUE THREAD

**Issue by witnessmenow** [jwilder/nginx-proxy#716]
Hey all,

Running on Ubuntu 16.04 
Docker version 1.13.1, build 092cba3

I'm trying to set this up and I get 503 everytime I hit the virtualhost address.

If I hit the IP address of the server with the port number specified I get the docker image so its up and running and the port is exposed ok.

I'm running the proxy with the following command:

`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name nginx-proxy jwilder/nginx-proxy`

And running my other docker image like this:

`docker run -d -e "VIRTUAL_HOST=www.moralsareoptional.com,moralsareoptional.com" -e "NODE_ENV=production" -e "PORT=3060" -p 3060:3060 --name mao-server craicaddictgames/apps:mao-server`

Anyone know what im doing wrong? 

docker logs nginx-proxy returns (I stopped and started the other docker image): 

`forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2017/02/12 23:04:54 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2017/02/12 23:04:54 Running 'nginx -s reload'
dockergen.1 | 2017/02/12 23:04:54 Watching docker events
dockergen.1 | 2017/02/12 23:04:54 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/12 23:16:52 Received event die for container cd10a37efc1e
dockergen.1 | 2017/02/12 23:16:53 Received event stop for container cd10a37efc1e
dockergen.1 | 2017/02/12 23:16:53 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2017/02/12 23:16:53 Running 'nginx -s reload'
dockergen.1 | 2017/02/12 23:16:53 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1    | 94.177.249.43 A_IP_ADDRESS - - [12/Feb/2017:23:17:03 +0000] "GET /82172316237 HTTP/1.1" 503 213 "-" "Mozilla"
dockergen.1 | 2017/02/12 23:17:06 Received event start for container cd10a37efc1e
dockergen.1 | 2017/02/12 23:17:06 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2017/02/12 23:17:06 Running 'nginx -s reload'
nginx.1    | 94.177.249.43 MY_IP_ADDRESS - - [12/Feb/2017:23:17:31 +0000] "GET / HTTP/1.1" 503 615 "http://www.moralsareoptional.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"`

**Comment by ForsakenHarmony** [comment]
can you share your `conf.d/default.conf`

for me the upstream thingie is empty, which it shouldn't be

**Comment by witnessmenow** [comment]
Sorry, I'm a docker newbie. Do I need to map out the folder or something to get access to the file?

**Comment by ForsakenHarmony** [comment]
you can either map it (but you don't need to if you don't have nginx and docker-gen as separate containers)

or you can run `docker cp nginx-proxy:/etc/nginx/conf.d/default.conf .` which should copy the file to the current directory

**Comment by witnessmenow** [comment]
Thanks a lot!

> # If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# www.moralsareoptional.com
upstream 1236a5782d440c39dd1e39b3cc490dbbb7fb9c6e {
				## Can be connect with "bridge" network
			# mao-server
			server 172.17.0.3:3060;
}
server {
	server_name www.moralsareoptional.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://1236a5782d440c39dd1e39b3cc490dbbb7fb9c6e;
	}
}

**Comment by ForsakenHarmony** [comment]
ok, that seems right, but will only work for `www.moralsareoptional.com`, any logs inside your application container?

**Comment by witnessmenow** [comment]
I think this might be a DNS configuration issue. Someone else owns the domain and they seem to have made a mistake where it points to.

It does hit the server (as seen in the logs in the first post) but the domain name resolves to a different server (so must be forwarded or something), I assume this is causing an issue. Will try debug and confirm

**Comment by thomasleveil** [comment]
can you run

    docker exec nginx-proxy nginx -s reload

and see if it raises any interesting error message

**Comment by m3talstorm** [comment]
You will need a specify a host when doing a request like:

> curl -H "Host: www.moralsareoptional.com" localhost

or set a default host in your docker-compose / Environment args:

> -e "DEFAULT_HOST=www.moralsareoptional.com"

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
