### ISSUE TITLE
Unable to start due to IPv6 binding

### ISSUE THREAD

**Issue by JamieMagee** [jwilder/nginx-proxy#717]
After #713 was merged yesterday, I am unable to start `nginx-proxy` on unRAID, as its kernel is not compiled with IPv6 support. I get the following error message:

`[emerg] 18#18: socket() [::]:80 failed (97: Address family not supported by protocol)`

There is currently an [open feature request](https://lime-technology.com/forum/index.php?topic=39533.0) to compile the kernel unRAID uses with IPv6 support. I am sure that unRAID is not the only OS that doesn't have full IPv6 support yet.

Is it possible to either:
1. Rollback change #713 
2. Create an IPv4 only docker tag `nginx-proxy`

**Comment by jwilder** [comment]
I'm reverting #713 in #718 for now.

**Comment by JamieMagee** [comment]
Thanks!

**Comment by Influencer** [comment]
How long does it take for this to make its way to docker hub once pulled?
