### ISSUE TITLE
SSL setup - Connection timed out

### ISSUE THREAD

**Issue by mrtibs2000** [jwilder/nginx-proxy#726]
I'm trying to get nginx (docker-compose setup) to serve SSL for the following domains:
api.mydomain.com
www.mydomain.com
api.sandbox.mydomain.com
www.sandbox.mydomain.com

The first 2 worked like a charm. The sandbox ones don't seem to work. If I do a curl http://www.sandbox.mydomain.com, I do get a 301 - which is correct. If I do a curl https://www.sandbox.mydomain.com, it just hangs - "Connection timed out". There is nothing in the logs.

I then purchased a wildcard certificate: *.mydomain.com. Same thing: "Connection timed out".

Btw, all the certs are in the same folder (./certs), and I thought they interfere with each other, so I tried different combinations (all of them in certs folder, only the wild card one in the certs folder, only the sandbox ones in the certs folder, etc.).

**Comment by thomasleveil** [comment]
note that a wildcard certificate for `*.mydomain.com` would not appy to `www.sandbox.mydomain.com`. If you need a certificate for that domain, you either need a regular certificate for `www.sandbox.mydomain.com` or a wildcard certificate for `*.sandbox.mydomain.com`.

**Comment by mrtibs2000** [comment]
Thanks for pointing that out. I deleted the *.mydomain.com, but I do indeed have a certificate for www.sandbox.mydomain.com - and that doesn't work. I thought that I might have accidentally mistyped a URL when creating the certificate request, but then I found several tools that confirm the correct spelling and the validity of the crt and the key.

I looked inside the default.conf on the container, and everything looks good. I compared that to my production default.conf and they are almost identical (without the word "sandbox" in them):
...
`
upstream api.sandbox.mydomain.com {
        ## Can be connect with "satellite_default" network
      # satellite_api_1
      server 172.18.0.7:8081;
}
server {
  server_name api.sandbox.mydomain.com;
  listen 80 ;
  access_log /var/log/nginx/access.log vhost;
  return 301 https://$host$request_uri;
}
server {
  server_name api.sandbox.mydomain.com;
  listen 443 ssl http2 ;
  access_log /var/log/nginx/access.log vhost;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 5m;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;
  ssl_certificate /etc/nginx/certs/api.sandbox.mydomain.com.crt;
  ssl_certificate_key /etc/nginx/certs/api.sandbox.mydomain.com.key;
  add_header Strict-Transport-Security "max-age=31536000";
  location / {
    proxy_pass http://api.sandbox.mydomain.com;
  }
}
`
...

**Comment by mrtibs2000** [comment]
Oh... I had forgotten to enable port 443 on my router.
