### ISSUE TITLE
502 error for services with delayed start

### ISSUE THREAD

**Issue by krystalcode** [jwilder/nginx-proxy#744]
I use docker compose 2 with nginx and docker-gen in separate containers, with an nginx-proxy network.

For simple services e.g. the jwilder/whoami example or a simple nginx container that serves static files, it always work. However, I'm testing it with other services, and I'm getting a 502 Bad Gateway error. Looking at the nginx logs, there is a connection refused error. The nginx configuration at "default.conf" seems to be correctly generated with the IPs and ports properly generated for each service. I can ping the containers by IP from within the nginx container.

A couple of services that I have issues with:
1. Gogs - it sometimes works, it sometimes throws a 502 error.
2. Kibana - it always throws a 502 error.

What I am thinking at the moment is that there is a delay for both services before they actually start serving. The Gogs service waits for mysql that runs on a separate container, and that may take a small amount of time to initiate. The Kibana service normally requires even up to a few minutes for various optimizations before getting started.

The problem is that even after waiting enough time for all initializations to complete, the same errors are being thrown. If, however, I start only the mysql service first, wait a minute, and then start the Gogs app, it seems to always work.

Is it possible that this is the problem, or should I be looking at somewhere else?

**Comment by thomasleveil** [comment]
could you share a minimal docker-compose.yml file that would allow to reproduce the issue?

**Comment by krystalcode** [comment]
Will try to reproduce independently and provide a file today.

**Comment by krystalcode** [comment]
I have tried to reproduce and it seems that in the case of Kibana/ElasticSearch there have been a few configuration changes required in the latest versions and that was causing the issue. I have been able to consistently make it work with the correct configuration. I will investigate the case with Gogs a bit more, but my guess would be that the proxy works as expected.

I'm therefore closing this issue, I'll update if there is anything relevant.

**Comment by stratosgear** [comment]
Hi @krystalcode.  I'm also having problems with the delayed start of kibana (I'm using [spujadas elk docker image][1]).

My nginx `default.conf` appears as:

```
upstream my.domain.com {
                                ## Can be connect with "nginxproxy_default" network
                # my-elk
                server 172.18.0.6 down;
}
```
What kind of Kibana/Elasticsearch configuration changes are you talking about?  Is there some workaround to bypass the delay?

In my docker image Kibana is started after Elasticsearch is started and ES takes at least 3-4 seconds before it's up and Kibana starts connecting...

Thanks!

[1]: https://github.com/spujadas/elk-docker

**Comment by krystalcode** [comment]
Hi @stratosgear 

I was using separate Elasticsearch and Kibana container images (from https://github.com/krystalcode/docker-dev), and the issue was that the kibana installation path had changed, and an additional option was required when installing X-Pack on elasticsearch. You can see the changes I had to to do here:

https://github.com/krystalcode/docker-dev/commit/cda4248d6e9ac5ab41fae510d7d3af96886ee3d6
https://github.com/krystalcode/docker-dev/commit/147acbfc122fb0c49e62bc3e2bab39f7488bb250

The point though is that these were problems on the application side, if you make sure that your ELK image runs correctly and kibana communicates correctly with elasticsearch (check kibana's logs, after it finishes building it will report whether it can reach elasticsearch), Nginx proxy should work. Kibana may take a few minutes to build when it starts and during that time it won't work, but after that Nginx proxy should pick it up automatically.

**Comment by stratosgear** [comment]
Geia sou @krystalcode,

Thanks for taking the time to locate your diffs.  Similarly, in my case the issue was on the application side.

And in the name of completeness, the issue had to do with my use of separate docker-compose networks.  nginx, nginxproxy-gen and nginxproxy-letsencrypt were running in an `ngixproxy-network`.  My ES/Logstash/Kibana (plus other services) where running in `myapp-network`.  Although I was "smart" enough to include the `ngixproxy-network` in the list of networks for the ELK container I had **not** added the `myapp-network` in the nginx container and nginx could not see my Kibana instance running.

Figured it out late last night.  Once again, thanks!

**Comment by krystalcode** [comment]
Kalispera @stratosgear  :)

Ok great, glad it worked. You don't need to add both networks to all containers though. I only add the nginxproxy-network to the app and that is enough. You do not need to add the myapp-network to the proxy.
