### ISSUE TITLE
coreos cluster support?

### ISSUE THREAD

**Issue by mikedevita** [jwilder/nginx-proxy#75]
Hello, I am trying to run a coreos cluster using fleet to deploy several wordpress lamp stacks across a number of servers. Each wordpress stack has a different domain name.

does your script support this? As far as I can tell it only works if nginx-proxy is on the same host as the wordpress containers.

**Comment by jwilder** [comment]
nginx-proxy needs to be on the same host as your containers.  If you want a nginx-proxy to add backends for remote hosts, that is not currently supported.  I've never tried running nginx-proxy from CoreOS so I can't say for sure if it will work or not.  It depends on how the docker daemon is setup and whether it's using unix domain sockets, TCP or TLS.

You might be better off looking at confd or vulcan which can use etcd as a registry.  https://github.com/jwilder/docker-register can register your containers in etcd where vulcan/confd can get at them.
