### ISSUE TITLE
Tests fail with new Docker version scheme

### ISSUE THREAD

**Issue by kamermans** [jwilder/nginx-proxy#755]
@thomasleveil: Docker has reworked their versioning system and I have installed the latest version in Ubuntu 16.04, which is versioned `Docker version 17.03.0-ce, build 60ccb22` (from the official repo).

This causes a failure in the `pytest` test suite (stripped wide header lines):
```
root@f8107fadcf50:/home/steve/Workspace/nginx-proxy/test# pytest
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /usr/local/bin/python2
rootdir: /home/steve/Workspace/nginx-proxy/test, inifile: pytest.ini
collected 101 items / 1 errors 

test_dockergen/test_dockergen_v3.py:12: in <module>
    pytestmark = pytest.mark.skipif(versiontuple(docker_version) < versiontuple('1.13'),
test_dockergen/test_dockergen_v3.py:8: in versiontuple
    return tuple(map(int, (v.split("."))))
E   ValueError: invalid literal for int() with base 10: '0-ce'
```

The problem is that the version now contains `-ce`.  My understanding is that version `17.03` (they use date-based versioning now) is equivalent to either `1.13` or the non-existent `1.14`.  In any case, this is the code that is causing the failure: https://github.com/jwilder/nginx-proxy/blob/master/test/test_dockergen/test_dockergen_v3.py#L12-L13

I am reworking my SSL Enhancement tests at the moment, so I will work around this for the time being, but if you (@thomasleveil) could look into it, I would be grateful.  Otherwise, I can probably fix it when I have some more time (this weekend, perhaps).

Until this issue is fixed, the unit test will not work on Docker `> 1.13`.

**Comment by thomasleveil** [comment]
I have a PR ready to be submitted to fix this. I'll submit it later today.

Le lun. 6 mars 2017 à 17:45, Steve Kamerman <notifications@github.com> a
écrit :
