### ISSUE TITLE
domains does not work on mac

### ISSUE THREAD

**Issue by b3nk3** [jwilder/nginx-proxy#758]
Hi,

I am merrily using the proxy on my prod server (ubuntu 16.04) but the domains I set on my local machine does not get resolved in the browser, eg test.localhost, but resolve fine by IP.

If I do a `curl -H "Host: test.localhost" localhost` however, outputs the whole website on my terminal.

This means to me, that nginx proxy does its job, but somehow Safari/Chrome doesn't resolve the domain.

Could you advise me what to look at as I'm struggling to resolve this.

**Comment by thomasleveil** [comment]
clearly out of the jwilder/nginx-proxy scope. What I would do is to add such domains to the hosts file. I don't own a Mac, but a quick search on Google reveals it is `/private/etc/hosts`. I suggest you search for tutorial on how to alter this file. 
You might also want to clear your Mac DNS cache and Internet browser DNS cache.

**Comment by b3nk3** [comment]
Slightly out of scope I would say, as I'd run into this if I'd have a mac server. But otherwise apologies. 

I will try cleaning the DNS cache as simply adding it to the hosts file did not work.

**Comment by jwilder** [comment]
You could also setup `dnsmasq` to have all `.localhost` domains resolve locally.  Something like: https://passingcuriosity.com/2013/dnsmasq-dev-osx/

**Comment by b3nk3** [comment]
as it works out of the box on Linux, I expect the same on macOS. Was wondering where is the difference. Thanks for the help anyway.
