### ISSUE TITLE
Listen Port 22

### ISSUE THREAD

**Issue by Awatatah** [jwilder/nginx-proxy#759]
is there a way or is there a `-e` option to set the listener? I need to listen on port 22 for a `server_name` So what I am looking for is something like:
`$ docker run -e VIRTUAL_HOST=foo.bar.com -e LISTEN_PORT=22 ...`

for a result of 
```
    server {
        server_name foo.bar.com;
	listen 22 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass ssh://foo.bar.com ;
	}
}

**Comment by metyl** [comment]
@Awatatah did You managed to configure listen port?

**Comment by Awatatah** [comment]
@metyl No, I gave up on it. After doing research I found that it is not possible.  What you will have to do is expose addition ports like `p- 222:22`
Example: `docker run --name foo -p 8080:80 -p 222:22 -d  image`
Then you can just ssh using that port `ssh user@192.168.1.1 -p 222`
