### ISSUE TITLE
503 errors

### ISSUE THREAD

**Issue by mjdavies** [jwilder/nginx-proxy#769]
Hello there

We've just started getting 503 errors from one of our proxies that's being served by nginx-proxy.

It looks like nginx-proxy isn't seeing the container/service on docker cloud and it' snot creating the entry for it in the default.conf file.

Looks like something along these lines

https://github.com/jwilder/nginx-proxy/issues/426

I've tried adding net:bridge to the service's description in the docker cloud stack file, and redeploying both nginx-proxy and the service, but it's not seeing it :-(

I can post up any docs you need, but some help would be great.  It's affecting a production system at the moment.

**Comment by mjdavies** [comment]
Solved it.

I created a new stack and it was ok.  Looks like the volumes got all messed up somehow with the other service stack on docker cloud.

Sorry to bother you.

**Comment by razbakov** [comment]
See #787
