### ISSUE TITLE
Can't use with multiple containers (jenkins + wordpress) - 503

### ISSUE THREAD

**Issue by luisnabais** [jwilder/nginx-proxy#771]
Hello.
I'm using the following **OS/Docker configuration**:
CentOS 7 (fully updated)
Docker 17.03
FirewallD disabled
SELinux disabled

With the following **Docker Images**:
jwilder/nginx-proxy:alpine
jrcs/letsencrypt-nginx-proxy-companion:latest
jenkins:2.32.3-alpine
wordpress:4.7.3-apache

**Issue**
I have A Records point to my domains, with subdomains. Example: jenkins.mydomain.com and wordpress.mydomain.com.

If I use _jenkins.mydomain.com_, it redirects correctly to my VPS machine, nginx-proxy recognizes it, letsencrypt processes certificates, redirects from http to https (if the redirect is needed) and Jenkins opens correcty.

If I use _wordpress.mydomain.com_, it recognizes, it shows in logs:
nginx.1    | wordpress.mydomain.com IP_ADDRESS - - [20/Mar/2017:16:56:17 +0000] "GET /favicon.ico HTTP/1.1" 503 616 "http://wordpress.mydomain.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"

And I get 503 error message.

I'm using the following **Docker run commands in scripts**:
**nginx-proxy**

docker container run -d -ti \
--name nginx-proxy \
--restart=always \
-p 80:80 \
-p 443:443 \
-v letsencrypt:/etc/nginx/certs:ro \
-v /etc/nginx/vhost.d \
-v /usr/share/nginx/html \
-v /var/run/docker.sock:/tmp/docker.sock:ro \
jwilder/nginx-proxy:alpine

docker network connect lnblog nginx-proxy

**Letsencrypt**
docker run -d -ti \
--name letsencrypt \
-v letsencrypt:/etc/nginx/certs:rw \
--volumes-from nginx-proxy \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
jrcs/letsencrypt-nginx-proxy-companion

**Jenkins**
docker container run -d -ti \
--name jenkins \
--restart=always \
-e VIRTUAL_HOST=jenkins.mydomain.com \
-e VIRTUAL_PORT=8080 \
-e LETSENCRYPT_HOST=jenkins.mydomain.com \
-e LETSENCRYPT_EMAIL=mail@mydomain.com \
-p 8080 \
-p 50000 \
-v jenkins:/var/jenkins_home \
jenkins:2.32.3-alpine

**Wordpress**
WP_BLOG_PWD=="<db_password>"

docker container run -d -ti \
--name wp_blog \
--restart=always \
--net wpblog \
-e WORDPRESS_DB_HOST=mariadb:3306 \
-e WORDPRESS_DB_NAME=wp_blog \
-e WORDPRESS_DB_USER=wp_blog_user \
-e WORDPRESS_DB_PASSWORD=${WP_BLOG_PWD} \
-e VIRTUAL_HOST=wordpress.mydomain.com \
-e VIRTUAL_HOST=80 \
-e VIRTUAL_NETWORK=wpblog \
-e LETSENCRYPT_HOST=wordpress.mydomain.com 
-e LETSENCRYPT_EMAIL=mail@mydomain.com 
-p 81:80 \ (this is just for debugging, I don't need port 81, I'll remove it later)
-v wpblog:/var/www/html \
wordpress:4.7.3-apache

docker network connect mariadb wp_blog

Any hints on what am I doing wrong? Am I understanding this incorrectly?
I'm using basic HTTP inside containers, but nginx-proxy processing HTTPS for them with letsencrypt.

Thank you very much for your help.
Best regards,
Luis Nabais

**Comment by r6203** [comment]
From a quick glance: You mistakenly set VIRTUAL_HOST=80, instead of VIRTUAL_PORT=80 inside your Wordpress config.
Don't know if that's causing your issue.

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
