### ISSUE TITLE
Adding AWS ALB causing "503 Service Temporarily Unavailable"

### ISSUE THREAD

**Issue by awartani** [jwilder/nginx-proxy#777]
Let's say we have an AWS ECS cluster with:
1. `nginx-proxy` container.
2. Simple HTTP container with `VIRTUAL_HOST=x.com`

When trying to access x.com it works with no issues (nginx-proxy is working).

Adding an `AWS ALB` with a target group that's pointing to `nginx-proxy`, is causing x.com to return `503 Service Temporarily Unavailable` (of course modifying DNS information to make x.com point to ALB).

Anyone ran into this before?

**Comment by jwilder** [comment]
Maybe: https://github.com/jwilder/nginx-proxy/wiki/Add-a-health-check-URL-for-AWS-ELB-ECS

If not, please ask questions in the [Q&A Group](https://groups.google.com/forum/#!forum/nginx-proxy).

Thanks!
