### ISSUE TITLE
delayed contaienr get marked down

### ISSUE THREAD

**Issue by aberfeldy** [jwilder/nginx-proxy#778]
Hey,

I used nginx-proxy inside a docker-compose and I run into a problem when one of the others container are delayed. The app-container has to run some reindexing and configurations scripts, before it starts it's http service, this leads to the issue that nginx-proxy marks them as down and thus I get 502 errors. 
Once the app is done, I'm able to run `sed -i "s/ down/:80/" /etc/nginx/conf.d/default.conf && nginx -s reload` and it works like a charm.
Is there any way to re-read/re-generate the conf with a command without rebuilding the container or start it separately?

**Comment by jwilder** [comment]
Send `nginx-proxy` container a `sighup`.  Something like `docker kill -s HUP <nginx-proxy container>`
