### ISSUE TITLE
error 503

### ISSUE THREAD

**Issue by raisiqueira** [jwilder/nginx-proxy#782]
I ran the following command, and it is returning error 503. Do I need to do any other configuration to run locally?

`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`
`docker run -e VIRTUAL_HOST=dev.lcoal`

**Comment by jwilder** [comment]
You may have a typo in your second command: `dev.lcoal`.  Looks like it's also missing an image to run.

**Comment by raisiqueira** [comment]
docker run -e VIRTUAL_HOST=dev.local nginx:alpine

**Comment by raisiqueira** [comment]
How to get around this situation?

**Comment by revolunet** [comment]
closable ?

**Comment by jwilder** [comment]
Moved to: https://groups.google.com/forum/#!topic/nginx-proxy/aY1FJJXNq0k
