### ISSUE TITLE
Problem with vhost listen on 443

### ISSUE THREAD

**Issue by paulz1** [jwilder/nginx-proxy#786]
It's possible that I don't understand something, but this is our situation.

We have a host with 3 vhost sites, all of them running in the container. So for example we have
jwilder/nginx-proxy
and
vhost1, vhost2, vhost3

nginx expose for 80 and 443.
And all of vhosts listen internally on 80 port.
We add certificates for vhost1 and vhost2, so now we could access https://vhost1 and https://vhost2.
Until that everything is perfect.

Now we try to add another docker container with vhost4.
The problem is that vhost4 listen only for 443.
And suddenly I could not get it work with nginx.

I give a look to nginx conf and it seems that I understand why it does not work.
Here is the part of nginx.conf :

```
upstream vhost4.domain.net {
				## Can be connect with "bridge" network
			# vhost4
			server 172.17.0.6:80;
}
```

The upstream for our vhost4 is 172.17.0.6 and it try to get it with 80 port. But the vhost4 is listen only for 443 so it does not work.

So the questions are...
1) Is it seems correct as explanation ?
2) Is there some solution for fix it ?

Thank you very much for help.
And by the way thank you very much for this project. It's very useful and I have done a lot things thanks to this project.

**Comment by wader** [comment]
If vhost4 talks https on 443 i think you want to start it with  `VIRTUAL_PORT=443` and `VIRTUAL_PROTO=https`

**Comment by paulz1** [comment]
Ok, thank you very much. I saw these options, but I misunderstood how it works.

VIRTUAL_PORT=443 and VIRTUAL_PROTO=https is the good solution for our situation. And it works perfectly.
