### ISSUE TITLE
docker-compose version 3?

### ISSUE THREAD

**Issue by ekkis** [jwilder/nginx-proxy#801]
I'm integrating: https://github.com/jwilder/nginx-proxy/blob/master/docker-compose-separate-containers.yml into my own docker-compose file, however I'm using features from version 3, which has eliminated the `volumes_from` functionality

could we upgrade this .yml to version 3?  I can't quite figure out how to do it with the new syntax

**Comment by tsq** [comment]
+1

**Comment by ekkis** [comment]
actually, I kinda figured it out.  it isn't finalised but see here: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/pull/203

**Comment by FrancescoSaverioZuppichini** [comment]
updates guys?

**Comment by buchdag** [comment]
@FrancescoSaverioZuppichini updates on what ?

This is a four years old closed issue. 🤔
