### ISSUE TITLE
Can not access other proxied virtual hosts from within containers

### ISSUE THREAD

**Issue by actraiser** [jwilder/nginx-proxy#803]
Hello,

I use nginx-stable with jwilder/docker-gen to serve a bunch of microservices via SSL. All Containers have their own docker-compose.yml and run in bridge network mode. There are no other links/remote_links between containers configured in the docker-compose-files. Are those required if I need e.g. a nodejs service in one container to reach out to api in another container via a full qualified hostname, e.g. https://service1.mydomain.com?

I can access all services from the browser by the VIRTUAL_HOSTs specified, ssl works fine too. What does not work is to access domains by their FQDN from within the individual containers, e.g. if service2 wants to connect to service1 for some API request. Situation is this:

What works:
- Accessing https://service1.mydomain.com from a browser
- Accessing https://service2.mydomain.com from a browser
- Accessing https://service1.mydomain.com from the server that hosts the containers
- Accessing any other website from within containers, e.g. `wget google.com`
- Pinging a docker container IP from another container, e.g. `ping 172.17.0.5` from container 172.17.0.4 works fine

What does NOT work
- Accessing https://service2.mydomain.com from the service1 container.
- Accessing https://service1.mydomain.com from the service2 container.
- wget the service by hostname when logged into a container times out
- wget the service by ip when logged into a container refuses the connection, e.g.  

  `wget https://172.17.0.5`
  
  `Connecting to 172.17.0.5 (172.17.0.5:443)`
  
  `wget: can't connect to remote host (172.17.0.5): Connection refused`

Is there an important DNS-related configuration step missing? I am happy to provide configuration files etc but maybe this is something obvious. 

Would appreciate any pointers.

Best
-act

**Comment by thomasleveil** [comment]
Isn't ssl added by nginx? Try http instead of https

**Comment by actraiser** [comment]
I found the source of the problem. I had to add a rule to the UFW (uncomplicated firewall) on the Ubuntu installation to allow for  inter-container communication coming in on the docker0. 

```
# find out IP of the host docker interface first by checking ` inet addr:`
ifconfig docker

# then add rules
ufw allow in on docker0 from <ip>
ufw allow out on docker0 to <ip>
ufw reload
```

Et Voila - it works.
-act

**Comment by jasonHav** [comment]
I've run into almost this same issue. UFW config didn't help unfortunately.

**Comment by zaaom** [comment]
@jasonHav did you manage to solve this issue? thank you!

**Comment by jasonHav** [comment]
unfortunately not - I ended up changing code architecture so it was no longer needed
