### ISSUE TITLE
How can I use it in Windows Docker, which base on Hyper-V

### ISSUE THREAD

**Issue by Iaodiary** [jwilder/nginx-proxy#817]
First , thanks for your applications
I want to use it on windows10, but there is no /var/run/docker.sock 
So does it have a altenative function to implement the same result, monitoring docker nginx change and automatic to reconfigured and restart the nginx-proxy service.

Thanks again

**Comment by fezfez** [comment]
any info ?

Thanks in advance

**Comment by jwilder** [comment]
`docker-gen` can also use the standard docker env vars:

```
DOCKER_HOST - default value for -endpoint
DOCKER_CERT_PATH - directory path containing key.pem, cert.pem and ca.pem DOCKER_TLS_VERIFY - enable client TLS verification
``

If those values are set, it will use them as instead of defaulting to unix socket.

**Comment by affektde** [comment]
this works for me ;-)

``-v //var/run/docker.sock:/tmp/docker.sock:ro``
