### ISSUE TITLE
Empty upstream with docker-compose.yml

### ISSUE THREAD

**Issue by DRogue1337** [jwilder/nginx-proxy#819]
Currently trying to use the docker-compose approach for [owncloud](https://github.com/owncloud-docker/server#launch-with-docker-compose).

I added
```
environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      ...
expose:
      - 80
```

to the [docker-compose.yml](https://raw.githubusercontent.com/owncloud-docker/server/master/docker-compose.yml) and removed the 'ports' key since we don't need them.

But the `upstream` in the `default.conf` file is empty:
```
# test.cloud.code.ag
upstream test.cloud.code.ag {
}
server {
        server_name test.cloud.code.ag;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://test.cloud.code.ag;
        }
}
```

When adding the IP manually
```
upstream test.cloud.code.ag {
server 172.18.0.4;
}
```

I just get `504 Gateway Time-out`.

**Comment by danibram** [comment]
Same here with the last version, if i launch the nginx-proxy image through docker-compose i cant make it work because the upstream are empty. When i launch through the command line works perfectly. There are any diference (i dont understand)? Im only launching 2 whoami images with the basic configuration of nginx-proxy

**Comment by hitalos** [comment]
Yours containers (nginx and owncloud) needs to be in the same network.
If you are using separeted `docker-compose.yml` files, in **version '2'** the stacks are created with a particular networks.

Set `network_mode: bridge` to use the same default network that would be used in `docker run…` command.

**Comment by DRogue1337** [comment]
I'll try that, but I'm using nginx-proxy with `docker run` and not `docker-compose.yml`, so there's only one yml file.

**Comment by DRogue1337** [comment]
Thanks again, @hitalos. It's working now.

I have another `docker-compose.yml` for my GitLab instance and there I don't need to set the `network_mode`, but that's because I'm not specifying `version: '2'` there, so I didn't think about that.

**Comment by hitalos** [comment]
When not specifying, version '1' is used and the `network_mode` default is `bridge`.
