### ISSUE TITLE
Headers set in app container are stripped

### ISSUE THREAD

**Issue by honi** [jwilder/nginx-proxy#82]
Hi, I have a django application composed of several containers: nginx, django+gunicorn, redis, postgres. The nginx container exposes port 80 and sets some headers, for example Cache-Control.

The reason I'm using this tool is because I want to deploy the same thing twice, one for QA and one for Production. It is working as expected, nginx-proxy correctly routes the requests based on the domain.

Though the problem I'm facing is that with nginx-proxy in front, the Cache-Control header never gets out. FYI, I do get the header if deployed only once without nginx-proxy and sending requests directly to my own nginx container.

Maybe I'm doing something wrong, but I would expect nginx-proxy to forward any headers set by the upstream. Is this not the case?

**Comment by jwilder** [comment]
There might be a missing directive in the nginx template. Maybe proxy_pass_header is needed.

**Comment by honi** [comment]
Yes, adding `proxy_pass_header Cache-Control;` in nginx.tmpl does the trick.

What would be the best approach for using custom templates? It would be nice if we could provide the template with a volume when running nginx-proxy, same way as the certs / htpasswd files.

Having custom templates per VIRTUAL_HOST also sounds reasonable. Are you or anybody else working on this feature?

**Comment by md5** [comment]
That doesn't seem right. `Cache-Control` isn't in the list of headers that are stripped by default and I don't see a `proxy_hide_header` in the upstream Nginx conf that would make this happen.

I just coded up a quick Sinatra app that returns a `Cache-Control` header and was able to see the header through `nginx-proxy`. See here: https://gist.github.com/md5/f83bc66b48981d6db7a0

**Comment by honi** [comment]
You are right @md5, my previous test was incorrect. There is no need for proxy_pass_header.

Though the custom nginx.tmpl feature is still valid I believe.

**Comment by jwilder** [comment]
Custom includes was added w/ #106.
