### ISSUE TITLE
Custom server blocks?

### ISSUE THREAD

**Issue by dj-hedgehog** [jwilder/nginx-proxy#826]
I need to add some custom Server Blocks (for reverse proxying to IP restricted Websites) to my nginx-proxy Konfiguration. Can I do this with this proxy?

**Comment by DRogue1337** [comment]
Yes, you can: https://github.com/jwilder/nginx-proxy#custom-nginx-configuration

**Comment by dj-hedgehog** [comment]
ok, thank you. I tried it and it works quite good.
