### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by wenlock** [jwilder/nginx-proxy#83]
@jwilder Hi!  just ran across this, and it looks like a very elegant and simple solution to proxy ports.   I'm liking it.   Do you have a license picked yet.  Would be great to see apache 2 or mit license on this work.

**Comment by jwilder** [comment]
I usually make stuff MIT. docker-gen which this uses is MIT.

**Comment by wenlock** [comment]
Hoping you don't mind letting me help you make that quick change.

**Comment by jwilder** [comment]
Nope. Thanks for the help!
