### ISSUE TITLE
react-router try_files

### ISSUE THREAD

**Issue by rcauquil** [jwilder/nginx-proxy#836]
Hi !
I have some trouble trying to get react-router working with nginx-proxy..
The proposed [solution](https://gkedge.gitbooks.io/react-router-in-the-real/content/nginx.html) is : 
```try_files $uri $uri/ /index.html;``` 

So I added it in /srv/docker/nginx/vhost.d/my.hostname_location but I'm only getting a 500 error.
It's working as expected if I change it for example by : 
```try_files $uri $uri/ =404;``` 

What am I doing wrong with this one ?

Have a nice day

**Comment by rcauquil** [comment]
For everyone that was stuck like me on this, I was adding it to the wrong container (nginx-proxy) instead of my app (which use a nginx:alpine image to serve my react app with react-router).
So I moved ```try_files $uri $uri/ /index.html;``` to the correct container, and everything works now as expected.

**Comment by wenduzer** [comment]
How did you edit it?
can you share the dockerfile?

**Comment by rcauquil** [comment]
@wenduzer I wrote a little [post about it](https://romaincauquil.fr/code/2017/06/02/react-router-nginx-docker/)

**Comment by wenduzer** [comment]
Wow! thank you very much!
I tried using it, It works but loads too much. can't figure out why,
look - https://img.wenduzer.io/
