### ISSUE TITLE
nginx: [emerg] no servers are inside upstream

### ISSUE THREAD

**Issue by guiyomh** [jwilder/nginx-proxy#841]
Hi all, 
I try to use nginx-proxy, but doesn't works.

```
docker exec -ti nginx-proxy bash
root@2913f58b4a98:/app# nginx -t
2017/06/02 14:07:50 [emerg] 73#73: no servers are inside upstream in /etc/nginx/conf.d/default.conf:50
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:50
nginx: configuration file /etc/nginx/nginx.conf test failed
```
here the /etc/nginx/conf.d/default.conf
```
 29 # HTTP 1.1 support
 30 proxy_http_version 1.1;
 31 proxy_buffering off;
 32 proxy_set_header Host $http_host;
 33 proxy_set_header Upgrade $http_upgrade;
 34 proxy_set_header Connection $proxy_connection;
 35 proxy_set_header X-Real-IP $remote_addr;
 36 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 37 proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
 38 proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
 39 proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
 40 # Mitigate httpoxy attack (see README for details)
 41 proxy_set_header Proxy "";
 42 server {
 43         server_name _; # This is just an invalid value which will never trigger on a real hostname.
 44         listen 80;
 45         access_log /var/log/nginx/access.log vhost;
 46         return 503;
 47 }
 48 # mail.plusdispo.docker
 49 upstream mail.plusdispo.docker {
 50 }
 51 server {
 52         server_name mail.plusdispo.docker;
 53         listen 80 ;
 54         access_log /var/log/nginx/access.log vhost;
 55         location / {
 56                 proxy_pass http://mail.plusdispo.docker;
 57         }
 58 }
 59 # plusdispo.docker
 60 upstream plusdispo.docker {
 61 }
 62 server {
 63         server_name plusdispo.docker;
 64         listen 80 ;
 65         access_log /var/log/nginx/access.log vhost;
 66         location / {
 67                 proxy_pass http://plusdispo.docker;
 68         }
 69 }
```
Do you have an idea ?

**Comment by ajtucker** [comment]
I faced the same issue with empty upstream definitions. I'm using docker-compose to bring up some containers and had tried running the nginx-proxy as per the instructions with `docker run`.

I think this is down to the nginx-proxy having a different network to the container you want to proxy. Adding the nginx-proxy to the docker-compose configuration worked ok for me. Later I realised that I could add additional networks to the nginx-proxy container (with `docker network connect`) and this works too.

As per issue #848, perhaps the best bet would be to use the host network.

**Comment by Neilpang** [comment]
@ajtucker 
Yes,  try my folk if you like:  https://github.com/Neilpang/nginx-proxy

**Comment by quadeare** [comment]
@Neilpang @ajtucker 
I just tested neilpang/nginx-proxy docker image and it fix upstream definitions problem !
Now, i can start different docker-compose.yml with separate networks.

Maybe you could suggest a merge request with your fix :)

**Comment by Neilpang** [comment]
@quadeare  
Here is a PR,  https://github.com/jwilder/nginx-proxy/pull/849

**Comment by guiyomh** [comment]
Thank @Neilpang 
I have found a workaround. Add in my DockerCompose file this : `network_mode: bridge` on each service.
