### ISSUE TITLE
[emerg] 1#1: host not found in upstream "down" in /etc/nginx/conf.d/default.conf

### ISSUE THREAD

**Issue by m-a-v** [jwilder/nginx-proxy#845]
I have many containers. One of the containers didn't get an IP address (due to a misconfiguration).

With the current nginx.tmpl file this creates an incorrect nginx.conf file, since .Network.IP is empty. As a result ALL hosts are down.

	{{ else if .Network }}
		# {{ .Container.Name }}
		server {{ .Network.IP }} down;
	{{ end }}

Any idea how to solve this?

**Comment by therealgambo** [comment]
Had this happen recently as well. Could we not just use `127.0.0.1` if the `.Network.IP` is empty? Nginx requires  an IP address or domain for any upstream server declaration.

**Comment by m-a-v** [comment]
This seems to be a very critical issue. After a reboot one docker image did not get an IP address. If this is happens ALL the other services become unavailable.

I tested the solution from therealgambo and it works as expected.. Is there any disadvantage using the localhost (127.0.0.1) ip address?

**Comment by mprokopov** [comment]
I can confirm, this is VERY annoying.

**Comment by m-a-v** [comment]
Since 22th June I use the method described above without any problems.

**Comment by ericdfields** [comment]
+1. Just ran into this.

**Comment by Niondir** [comment]
Fix is working for me as well. Should just be added.

**Comment by therealgambo** [comment]
Fix has been merged. This can now be closed.

**Comment by m-a-v** [comment]
Duplicate of #926
