### ISSUE TITLE
Enable SSL with separate NGINX proxy and dockergen container configuration

### ISSUE THREAD

**Issue by GSFC-587** [jwilder/nginx-proxy#852]
Due to an imposed need to implement ModSecurity for my proxied web site, I have opted to use the "Separate Containers" options, with a custom-built NGINX container (with ModSecurity enabled) and the latest dockergen container from Docker Hub (with the latest nginx.tmpl from the nginx-proxy GitHub installed).

My goal is to have an NGINX proxy container that routes all requests on port 443 to individual containers (not exposed to the Internet) on their exposed ports 80.

The problem is that I can't get my NGINX proxy container to listen on port 443 instead of port 80, and I have exhausted all the options I can think of. 

Here are my relevant docker-compose service configurations:

    nginx-proxy:
        build: ./nginx-proxy
        image: nginx-proxy
        container_name: nginx-proxy
        ports:
            - "443:443"
        volumes:
            - /etc/nginx/conf.d
            - ./config/nginx/certs:/etc/nginx/certs
            - /var/log/nginx:/var/log/nginx
        environment:
            - CERT_NAME=emac
     
    docker-gen:
        image: jwilder/docker-gen
        container_name: docker-gen
        command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./config/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
        environment:
            - ENABLE_IPV6=true

    emac:
        build: ./docker
        image: emac
        container_name: EMAC
        expose:
            - "80"
        volumes:
            - /var/log/nginx/emac:/var/log/nginx 
            - ./shared/config/nginx:/etc/nginx 
            - ./config/nginx/conf.d:/etc/nginx/conf.d 
            - ./website:/var/www:ro 
        environment:
            - VIRTUAL_HOST=lvh.me

Here is my nginx.conf of the NGINX proxy server:

    worker_processes auto;
    daemon off;

    events 
    {
        worker_connections 1024;
    }

    http 
    {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        server_names_hash_bucket_size 128;
        types_hash_max_size 2048;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # See https://www.nginx.com/resources/admin-guide/nginx-https-upstreams/
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:AES128-SHA";
        ssl_prefer_server_ciphers on;

        ssl_certificate /etc/nginx/certs/emac.crt;
        ssl_certificate_key /etc/nginx/certs/emac.key;
	
        modsecurity on;
	
        include /etc/nginx/conf.d/*.conf;
    }

(Note especially that I include the contents of /etc/nginx/conf.d.)

And here is the relevant portion of the resulting default.conf generated in /etc/nginx/conf.d at run-time:

    server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        listen [::]:80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
    }

    # lvh.me
    upstream lvh.me {
        ## Can be connect with "emac_default" network
        # EMAC
        server 172.18.0.6:80;
    }
    server {
        server_name lvh.me;
        listen 80 ;
        listen [::]:80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
            proxy_pass http://lvh.me;
        }
    }

As you can see, the default server (which corresponds to the proxy server, yes?) is configured only to listen on port 80, despite its docker service opening only port 443, and despite having a valid certificate in place (as confirmed by tools). 

What can I do to configure things such the my proxy server instead listens on port 443?

Thanks!

Carl

P.S. Sorry this is so long, but these code snippets might prove useful to others as well, in their own right.

**Comment by Neilpang** [comment]
try:

```
   - VIRTUAL_PORT=443
   - VIRTUAL_PROTO=https
```

**Comment by GSFC-587** [comment]
Thanks for the suggestion, Neipang. I'd tried that before, and just tried it again (putting those environment variables on both the nginx-proxy and docker-gen services), but it had no effect at all. (I wonder if those variable are ignore except for backend servers that have a VIRTUAL_HOST name?)

**Comment by Neilpang** [comment]
It should be used on the backend webserver,  not  on nginx proxy.
And I have tried on my servers, it works as expected.

**Comment by GSFC-587** [comment]
Hm, I tried that on the backend server (emac), but it didn't make any difference either.

In any event, I don't want my backend servers to listen on port 443, I only want my proxy server to do so. 

In fact, I want the backend servers not to listen to any port on the host, only to their local port 80. That way all access to the site and its proxied servers will be only through the proxy, and only through port 443, which is the only one that I am allowed to make publicly accessible.

I was able to do exactly this when I used the jwilder/nginx-proxy container. But since I have a requirement to use ModSecurity, that's no longer an option. I just can't seem to figure out how to get SSL to work in the "Separate Containers" configuration: i.e., to make the separate NGINX proxy container listen to port 443 and proxy to the other, VIRTUAL_HOST containers.

**Comment by Neilpang** [comment]
Yes, I think I get what you mean now. just forget VIRTUAL_PORT and VIRTUAL_PROTO, it's not for you case.

As the server is only listening on 80 port:

```sh
server {
    server_name lvh.me;
    listen 80 ;
    listen [::]:80 ;
    access_log /var/log/nginx/access.log vhost;
    location / {
        proxy_pass http://lvh.me;
    }
}
```

it's because you don't have a cert/key file configured in the nginx-proxy container.

Please add the following 2 files to your nginx-proxy container:

```sh
/etc/nginx/certs/lvh.me.crt
/etc/nginx/certs/lvh.me.key
```

When you restart your nginx-proxy container, it first detects if the 2 files exist.  If true,  it uses the 2 files to listen at 443 port,  otherwise it only listens at 80 port.

**Comment by GSFC-587** [comment]
OK, that made a difference, but I still can't reach the site (or proxy) on port 443. Here's the relevant part of the default.conf it is now generating:

    server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        listen [::]:80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
    }
    
    # lvh.me
    upstream lvh.me {
        ## Can be connect with "emac_default" network
        # EMAC
        server 172.18.0.6:80;
    }
    server {
        server_name lvh.me;
        listen 80 ;
        listen [::]:80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
    }
    server {
        server_name lvh.me;
        listen 443 ssl http2 ;
        listen [::]:443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/lvh.me.crt;
        ssl_certificate_key /etc/nginx/certs/lvh.me.key;
        add_header Strict-Transport-Security "max-age=31536000";
        location / {
            proxy_pass http://lvh.me;
    }

This does add a 443 server for the backend (emac), but the default server is still port 80 only. 

(In fact, looking at the nginx.tmpl used by the latest version of jwilder/nginx-proxy [(here)](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl), it appears that the only way a default server listening on port 443 is generated is if there is a default.crt and default.key in place:

    {{ if (and (exists "/etc/nginx/certs/default.crt") (exists "/etc/nginx/certs/default.key")) }}

Which leads me to think I've misunderstood the role of the default server(s) in all this, and that it's not actually relevant to the problem.)

So, is it the case that the upstream server definition starting with:

    server {
        server_name lvh.me;
        listen 443 ssl http2 ;
        ...
    }

is what is (or should be) listening to the host machine's port 443? If so, then I need to rethink the problem.

Thanks!

Carl

**Comment by Neilpang** [comment]
Can you access your website at:  `http://lvh.me`  or `https://lvh.me`

**Comment by Neilpang** [comment]
why it's resolved to ip :`127.0.0.1`

**Comment by Neilpang** [comment]
please try:

```sh
curl -vv   http://lvh.me
curl -vv   https://lvh.me
```

**Comment by GSFC-587** [comment]
lvh.me is the "local virtual host" (equivalent to localhost). I'm using it for testing. And no, I can't access it either by HTTP or HTTPS. 

Another bit of info. When I run:

    curl -f https://lvh.me

I get back:

    curl: (35) Server aborted the SSL handshake 

To diagnose this further, I ran:

    openssl s_client -connect lvh.me:443 -prexit

and I get back:

    CONNECTED(00000003)
    48826:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s23_lib.c:185:
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 0 bytes and written 130 bytes
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    ---

So it looks like my problem might be certificate-related, not having anything to do with my proxy configuration.

P.S. Just saw your request.

    curl -vv https://lvh.me

yields:

    * Rebuilt URL to: https://lvh.me/
    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to lvh.me (127.0.0.1) port 443 (#0)
    * Server aborted the SSL handshake
    * Curl_http_done: called premature == 0
    * Closing connection 0
    curl: (35) Server aborted the SSL handshake

**Comment by Neilpang** [comment]
try:
```
netstat -ntpl | grep nginx
```

**Comment by GSFC-587** [comment]
Hm, that doesn't work on my Mac. I get:

    netstat: l: unknown or uninstrumented protocol

**Comment by Neilpang** [comment]
you are running all your docker containers on your Mac ?

**Comment by GSFC-587** [comment]
Yes, for local testing. I'll eventually run on a Linux host.

**Comment by Neilpang** [comment]
Oh no.   docker on Mac has dedicated network.
please just try on a linux host,   it can save your life.

**Comment by GSFC-587** [comment]
I've moved everything to my host server (and made the required hostname and certificate name adjustments). Still can't access it, and 

    openssl s_client -connect emac.<redacted>:443 -prexit

still returns:

    socket: Connection refused
    connect:errno=111
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 0 bytes and written 0 bytes
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE

Does my custom NGINX maybe need some addition modules/compiler options? 

Here are the build details:

    nginx version: nginx/1.12.0
    built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
    built with OpenSSL 1.1.0f  25 May 2017
    TLS SNI support enabled
    configure arguments: --with-http_ssl_module --with-openssl=/opt/openssl-1.1.0f --with-http_v2_module --with-ipv6 --add-module=/opt/ModSecurity-nginx

**Comment by Neilpang** [comment]
try
```sh
netstat -ntpl | grep nginx
```

**Comment by GSFC-587** [comment]
My NGINX proxy container (Ubuntu based) doesn't have netstat installed.

When I run that command on the host server, I get:

    (No info could be read for "-p": geteuid()=6100 but you should be root.)

(Hey, I REALLY appreciate your help! Sorry to take up so much of your time.)

**Comment by Neilpang** [comment]
You don't need to run this command in the container,  just run it on the linux host.

```
sudo  netstat -ntpl | grep nginx
```

**Comment by GSFC-587** [comment]
That returns nothing. That's not surprising, though, because the host server isn't running NGINX (or any web-server, in fact): only my proxied containers are running NGINX (and other web servers).

**Comment by Neilpang** [comment]
Yes, I knew the nginx server is not running on the host.
But  the process running in a container should also be seen on the host machine.

**Comment by Neilpang** [comment]
can you please try:
```
sudo ps aux | grep nginx
```

**Comment by GSFC-587** [comment]
OK, THAT returned a LOT of results: several master processes (as root), e.g.:

    root      1894  0.0  0.0  95372  4664 ?        S    23:18   0:00 nginx: master process nginx

 and dozens of worker processes (as "nfsnobo+"), e.g.:

    nfsnobo+  1896  0.0  0.0  95544  1904 ?        S    23:18   0:00 nginx: worker process

**Comment by GSFC-587** [comment]
"the process running in a container should also be seen on the host machine" — I did not know that! (Still new to Docker.)

**Comment by GSFC-587** [comment]
I have to turn in now, I'm afraid. I'll pick this up again tomorrow. Thank you SO MUCH for your efforts!

**Comment by Neilpang** [comment]
ok,  see you.

**Comment by GSFC-587** [comment]
I think I've narrowed this down to a failure of my NGINZ proxy to restart when docker-gen updates the default.conf. I wonder if there's something else I should be using than the command:

        command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

to restart the version if NGINX I've compiled (1.12.0, the latest stable version)? Or if I need to enable some module or setting to allow it to be restarted by docker-gen?

**Comment by GSFC-587** [comment]
So, in an attempt to isolate this problem, I decided to use the official NGINX image and see if I could get proxying to work in the "Separate Containers" configuration:

    nginx:
        image: nginx
        container_name: nginx
        command: nginx -g "daemon off;"
        ports:
            - "80:80"
        volumes:
            - /etc/nginx/conf.d
            - ./nginx-proxy/config/nginx:/etc/nginx
            - /var/log/nginx:/var/log/nginx
            - /var/run/docker.sock:/tmp/docker.sock:ro

    docker-gen:
        image: jwilder/docker-gen
        container_name: docker-gen
        command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        depends_on: 
            - nginx
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

This at least allows me to see the default NGINX welcome page at lvh.me; BUT in fact, proxying does NOT work in this configuration, either: no matter which proxied subdomain I try to access in the browser, I see only the default NGINX welcome page.

So I then decided to see whether I could get the official example "Separate Containers" configuration:

    [docker-compose-separate-containers.yml](https://github.com/jwilder/nginx-proxy/blob/master/docker-compose-separate-containers.yml)

And guess what — exactly the same behavior:

    curl -H "Host: whoami.local" localhost

returns not the expected whoami service response, but instead the default NGINX welcome page.

So, it appears to me that docker-gen proxying does not work in the "Separate Containers" configuration with the latest NGINX and docker-gen images.

Can anyone verify or refute this?

**Comment by GSFC-587** [comment]
OK, I finally got things working. I had a few things misconfigured in my docker-compose file that were inadvertently causing file conflicts. Another key is to NOT use the --only-exposed flag in the docker-gen command (which results in empty upstream server clauses). 

To possibly help others get started, here is the core of how I assembled a separate NGINX proxy with SSL and ModSecurity enabled.

Dockerfile:

	FROM ubuntu

	# Install/update dependencies
	RUN apt-get update && \
		apt-get -y install g++ flex bison curl doxygen libyajl-dev libgeoip-dev libtool dh-autoreconf libcurl4-gnutls-dev libxml2 \
			git pkgconf libpcre3 libpcre3-dev libxml2-dev wget zlib1g-dev && \
		rm -rf /var/lib/apt/lists/*
	
	# Compile and install ModSecurity v3 (required for ModSecurity-nginx connector)
	# See: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#ubuntu-1504

	RUN cd /opt/ && git clone https://github.com/SpiderLabs/ModSecurity.git && cd ModSecurity && \
		git checkout -b v3/master origin/v3/master && \
		sh build.sh && \
		git submodule init && \
		git submodule update && \
		./configure && \
		make && \
		make install && \
		export MODSECURITY_INC="/opt/ModSecurity/headers/" && \
		export MODSECURITY_LIB="/opt/ModSecurity/src/.libs/"

	# Install ModSecurity-nginx connector
	RUN cd /opt/ && git clone https://github.com/SpiderLabs/ModSecurity-nginx.git

	# Install OpenSSL
	RUN  cd /opt/ && git clone https://github.com/openssl/openssl.git

	# Compile and install NGINX with SSL and ModSecurity-nginx connector
	RUN  cd /opt/ && git clone https://github.com/nginx/nginx.git && cd /opt/nginx/ && \
		./auto/configure \
			--prefix=/etc/nginx  \
			--sbin-path=/usr/sbin/nginx \
			--conf-path=/etc/nginx/nginx.conf  \
			--pid-path=/var/run/nginx.pid \
			--lock-path=/var/run/nginx.lock \
			--error-log-path=/var/log/nginx/error.log \
			--http-log-path=/var/log/nginx/access.log \
			--with-http_gzip_static_module  \
			--with-http_stub_status_module \
			--with-http_ssl_module  \
			--with-pcre \
			--with-file-aio \
			--with-http_realip_module \
			--without-http_scgi_module \
			--without-http_uwsgi_module \
			--without-http_fastcgi_module \
			--with-http_v2_module \
			--with-ipv6 \
			--with-openssl=/opt/openssl \ 
			--add-module=/opt/ModSecurity-nginx && \
		make && \
		make install
	
	# Install recommended ModSecurity rules
	RUN cd /opt/ && \
		wget https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v2/master/modsecurity.conf-recommended \
			-O modsecurity.conf && \
			chmod +x modsecurity.conf
	
	# TODO: Follow recommended install and automate updates
	# See: https://raw.githubusercontent.com/SpiderLabs/owasp-modsecurity-crs/v3.0/master/INSTALL
	#
	# RUN git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /etc/modsecurity && \
	# 	cat /etc/modsecurity/rules/*.conf >> /etc/nginx/modsecurity/modsecurity.conf && \
	# 	cp /etc/modsecurity/rules/*.data /etc/nginx/modsecurity/ && \
	# 	sed -i -e 's|SecRuleEngine .*$|SecRuleEngine On|' /etc/nginx/modsecurity/modsecurity.conf
	# 		
	# COPY ./update-modsec.sh /usr/bin/update-modsec.sh
	# RUN chmod +x /usr/bin/update-modsec.sh

	EXPOSE 80 443

	WORKDIR /
	CMD nginx

docker-compose.yml

    version: '2'
    services:

        nginx-proxy:
            build: ./nginx-proxy
            image: nginx-proxy
            container_name: nginx-proxy
            command: nginx -g "daemon off;"
            ports:
                - "80:80"
                - "443:443"
            volumes:
                - ./nginx-proxy/config/nginx:/etc/nginx
                - /etc/nginx/conf.d
                - /var/log/nginx:/var/log/nginx
            environment:
                - CERT_NAME=<your cert here>
         
        docker-gen:
            image: jwilder/docker-gen
            container_name: docker-gen
            command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
            depends_on: 
                - nginx-proxy
            volumes_from:
                - nginx-proxy
            volumes:
                - /var/run/docker.sock:/tmp/docker.sock:ro
                - ./docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

    <your virtual host(s) here>

**Comment by GSFC-587** [comment]
Thanks again, Neilpang, for all the help!
