### ISSUE TITLE
Add buffer to access_log to reduce CPU and I/O cycles

### ISSUE THREAD

**Issue by quocnguyen** [jwilder/nginx-proxy#855]
From https://www.nginx.com/blog/tuning-nginx/

Logging every request consumes both CPU and I/O cycles, and one way to reduce the impact is to enable access-log buffering. With buffering, instead of performing a separate write operation for each log entry, NGINX buffers a series of entries and writes them to the file together in a single operation.

To enable access-log buffering, include the buffer=size parameter to the access_log directive; NGINX writes the buffer contents to the log when the buffer reaches the size value. To have NGINX write the buffer after a specified amount of time, include the flush=time parameter. When both parameters are set, NGINX writes entries to the log file when the next log entry will not fit into the buffer or the entries in the buffer are older than the specified time, respectively. Log entries are also written when a worker process is reopening its log files or shutting down. To disable access logging completely, include the off parameter to the access_log directive.

FYI: http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log

What do you think ?

**Comment by luckydonald** [comment]
The nginx docker links `/dev/stdout` in place of the logfiles.
Not sure if that changes anything.

See [Dockerfile of nginxinc/docker-nginx@`c769ad`](https://github.com/nginxinc/docker-nginx/blob/c769ad8ab21dfb374fa33d8fb9d0822d0fa8d2e5/mainline/stretch/Dockerfile#L36)

**Comment by kamermans** [comment]
The log is indeed symlinked to `/dev/stdout`, but it is still being accessed as a block device, so I think the feature would still work properly, but I'm not sure of there's actually a performance benefit.  The log lines are being written to either the output block device, or the buffer on each request.  If the block device is `STDOUT`, there is very little performance hit.  The real performance hit is when Docker writes that stream down to file (assuming you're using the default `json-file` driver).

If you have a performance issue, I would suggest using a different driver, like `syslog` or `gelf` and shipping your logs over to a logging host.  Buffering writes will help on media with high latency (ex: rotational hard drives, NFS, etc), but to be honest, you're probably delaying the inevitable if you have this problem.

If people (like @jwilder) do want this on, I suggest using low settings like `buffer=4k` and `flush=2s`, that way you never have to wait more than 2 seconds to get a chunk of log data.

Personally, I stream the data from STDOUT through the Docker GELF driver into Kafka, then it gets ingested in real-time by Logstash into ElasticSearch, where it shows up in real-time in Kibana.  For me, the delay from an access log write to it appearing on a real-time graph in Kibana is much less than one second, and with Nginx access log buffering of more than a few seconds, I would probably see really strange "bursty" log data for lower traffic sites.

**Comment by Xhycos** [comment]
Hello @kamermans, Can I have a talk and help from you ?
I would like to connect Kafka to a Logstash and a help will be welcome.
Can you explain how did you do this?

Regards,
Guillaume AUBRY
