### ISSUE TITLE
Per VIRTUAL_HOST custom includes

### ISSUE THREAD

**Issue by Nitesedge** [jwilder/nginx-proxy#87]
How hard would it be to add support for a custom include file per host? Much like the htpasswd where if the file exists for a virthost it gets included in the config?

 I'm thinking along the lines of custom rewrite rules per container as well as other custom includes.

I'm playing with the configs now, but am not savvy with nginx or the template language. Any pointers would be appreciated!

**Comment by Nitesedge** [comment]
I'm thinking something like this: http://pastebin.com/51SD6Ph5

Thoughts?

**Comment by md5** [comment]
@Nitesedge I think your implementation of this looks fine. I would probably call the directory `/etc/nginx/proxy.d` instead of `/etc/nginx/includes`, but this is exactly what I was going to implement when I thought I should look through the existing issues and PRs one more time.

**Comment by thaJeztah** [comment]
+1 would be nice to have a PR for this!

**Comment by md5** [comment]
I ended up opening my own PR for this at #106 since I had some time and wanted to include some docs.

**Comment by md5** [comment]
This can be closed since #106 was merged. See the README for instructions: https://github.com/jwilder/nginx-proxy/blob/master/README.md#custom-nginx-configuration
