### ISSUE TITLE
Fallback for domains not matching any VIRTUAL_HOST

### ISSUE THREAD

**Issue by daweedm** [jwilder/nginx-proxy#873]
I have a lots of domains pointing to my server.
I would like to have some kind of "default" page for all of them without writing each domain in the VIRTUAL_HOST env variable, could it be done with your image ?

**Comment by wader** [comment]
Maybe https://github.com/jwilder/nginx-proxy#default-host would work for you?

**Comment by daweedm** [comment]
Yes, thank you !
