### ISSUE TITLE
Custom nginx configuration examples

### ISSUE THREAD

**Issue by pavelsr** [jwilder/nginx-proxy#876]
I think there is a lack of examples in [documentation here](https://github.com/jwilder/nginx-proxy#custom-nginx-configuration) or docs might be outdated.

For example, I need to setup a redirect from one domain to another (i.fabmarkt.ru to fabmarket.tilda.ws in my case)

I added following config 

```nginx
server {
  server_name i.fabmarkt.ru;
  return 301 http://fabmarket.tilda.ws$request_uri;
}
```

to `/etc/nginx/vhost.d` volume (in my case mounted on `/var/lib/docker/volumes/1a1d79e510371f2c6aa216fca75b7d05f44155878f6e0a7233fc7992c08bc966/_data`)

but when I go to i.fabmarkt.ru nginx is still showing `503 Service Temporarily Unavailable`

What's wrong ?

**Comment by Pimmetje** [comment]
/etc/nginx/vhost.d will be included in a existing vhost. It will allow u to add extra options for a vhost u already have within docker. U can't use this option to add extra vhosts.

**Comment by pavelsr** [comment]
Got it. Added  `server { ... }` to `/etc/nginx/conf.d/default.conf` and everything works fine.

**Comment by timethy96** [comment]
Just for the record and anyone looking to configure custom vhosts in nginx-proxy:
If you want to configure custom vhosts, you should not put them into the default.conf, as it is overwritten on container-restart. Instead create a new file with any name and with the suffix *.conf* in `/etc/nginx/conf.d/`. In this file you can then specify your custom `server { ... }`.
