### ISSUE TITLE
Server Sent Events + SSL issue

### ISSUE THREAD

**Issue by mprokopov** [jwilder/nginx-proxy#878]
It seems, that nginx-proxy has an issue with the keep-alive SSE (server sent events) connections. It closes connection despite custom nginx configuration for virtual host

    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;

After about 1 minute it closes client connection and dies.

That does not happen if app container does SSL termination by itself and is not proxied by nginx.

**Comment by jpic** [comment]
Is it still the case for you since #882 ?

**Comment by yomexzo** [comment]
Did you resolve this @mprokopov? I am trying to proxy a long running connection on a nextjs set up using nginx and the above configuration is not working. I can hit the endpoint directly and see the content as they are received but nginx seems to be waiting for the upstream to indicate it is done sending data before responding to the client.

**Comment by mprokopov** [comment]
@yosmanyga that was the issue not on the Nginx side, but the backend side

**Comment by yosmanyga** [comment]
@mprokopov you meant @yomexzo

**Comment by yomexzo** [comment]
What did you do in backend to fix it @mprokopov?
