### ISSUE TITLE
support for wildcard virtual-hosts

### ISSUE THREAD

**Issue by schmunk42** [jwilder/nginx-proxy#89]
We're using [xip.io](http://xip.io) to name and access our vHosts, which works very nice so far.

The only downside is, that we have to add several possible options to our `VIRTUAL_HOST` env variable, if we'd like to access it on different environments or from other clients on the network.

So our config looks like this:

```
VIRTUAL_HOST: kitchen-sink.127.0.0.1.xip.io,kitchen-sink.192.168.59.103.xip.io,kitchen-sink.192.168.77.10.xip.io
```

but it would be much nice, if we could use:

```
VIRTUAL_HOST: kitchen-sink.(.*).xip.io
```

Is this even possible with nginx?

PS: Thanks for this wonderful code, it saves so much time and makes things really easy to setup.

**Comment by jwilder** [comment]
I haven't tried this but the `VIRTUAL_HOST` value ends up being the value for `server_name` in the nginx config.  It looks like wildcards are supported: http://nginx.org/en/docs/http/server_names.html

You could try something like `VIRTUAL_HOST=*.xip.io` possibly.

**Comment by schmunk42** [comment]
Nice, thanks!
I'll try that. Would you be interested in a PR with an additional paragraph for the docs, if it works - or is it too specific?

Von meinem iPhone gesendet

Am 21.01.2015 um 19:52 schrieb Jason Wilder <notifications@github.com <mailto:notifications@github.com>>:

**Comment by jwilder** [comment]
Sure.  Always open to more documentation PRs.
