### ISSUE TITLE
Trying to edit /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by wenduzer** [jwilder/nginx-proxy#904]
I am running nginx-proxy with static react web-app but can't get the router working. I get 404.
So I figured I need to redirect every route to the index.html in the nginx configuration.
this is what I added to try to make it work with html5 router (to redirect to index.html)
but still can't work it..
`
server {
       location / {
                    try_files $uri $uri/ /index.html;
}     
`

Am I missing something? the way of configuring nginx-proxy, etc?

**Comment by GodLikeZeal** [comment]
I have the same case with you,please help me how to solve this problem,thank you very much!

**Comment by w3nda** [comment]
@GodLikeZeal that was so long ago, took me a minute but there ya go.
https://romaincauquil.fr/code/2017/06/02/react-router-nginx-docker/

you can find out more in #836

**Comment by GodLikeZeal** [comment]
> @GodLikeZeal that was so long ago, took me a minute but there ya go.
> https://romaincauquil.fr/code/2017/06/02/react-router-nginx-docker/
> 
> you can find out more in #836

wow!thank you very much
