### ISSUE TITLE
Feature request: 301 redirect to www or non-www

### ISSUE THREAD

**Issue by jmillerdesign** [jwilder/nginx-proxy#92]
If you pass in multiple domains, it would be great to be able to 301 redirect the www subdomain to the naked domain. ```VIRTUAL_HOST: example.com,www.example.com```

**Comment by johnjelinek** [comment]
I think you might want to specify a different syntax in that case. Perhaps `example.com->www.example.com` to set a 301 redirect.

**Comment by md5** [comment]
You guys may want to comment on the implementation in #98.

**Comment by jmillerdesign** [comment]
Thanks to #106 this is now possible. Here's how to do it:

* Create a volume for /etc/nginx/vhost.d
* In /path/to/vhost.d/www.example.com, add the contents: ```rewrite ^(.*) https://example.com$1 permanent;```

**Comment by johnjelinek** [comment]
works!

**Comment by skwasha** [comment]
I'm having an issue with this... My VIRTUAL_HOST is set to domain.com, www.domain.com. I have a blank file domain.com and one for www.domain.com with the line: 
> return 301 https://domain.com$request_uri;
in it. My run line is as follows:
> docker run -d -p 80:80 -p 443:443 --restart=always --volumes-from #{deploy[:application]} --name nginx-proxy -v /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
I thought this should redir any www requests to non-www. but all I get are 502s. Any suggestions?

**Comment by jmillerdesign** [comment]
Sounds like you're doing everything correctly. Perhaps there's an unrelated issue with the container you're running. What's the nginx.conf like? Do you see any errors there?

**Comment by skwasha** [comment]
Are you referring to the generated one? I'm just using the default template with the addition of the vhost specific one-liner.

**Comment by skwasha** [comment]
Seems to be some sort of issue with the volumes not mounting properly from the app container. I can see both /etc/nginx/certs and /etc/nginx/vhost.d being mounted in the app container and the nginx proxy container. But only the files from the certs dir are visible on the proxy container. 

The 502's were something else entirely...

**Comment by ryneeverett** [comment]
I don't see how @jmillerdesign's strategy could work without setting `HTTPS_METHOD=noredirect` (which I wouldn't want to do because that would disable HSTS). Otherwise you get redirected to `https://www.example.com` before it gets to the vhost configuration file. Relevant parts of the template:

```
{{ if eq $https_method "redirect" }}
server {
	server_name {{ $host }};
	listen 80 {{ $default_server }};
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
{{ end }}

...

	{{ if (ne $https_method "noredirect") }}
	add_header Strict-Transport-Security "max-age=31536000";
	{{ end }}
```
