### ISSUE TITLE
Portainer with nginx-proxy

### ISSUE THREAD

**Issue by kevindesousa** [jwilder/nginx-proxy#936]
Hello, when i want to connect Portainer, i have this on nginx log output : 
3 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream....

and I have a 502 on the browser...

**Comment by kevindesousa** [comment]
Remove VIRTUAL_PROTO 0:)

**Comment by jspitzen** [comment]
@kevindesousa I'm having this same issue, but did not set VIRTUAL_PROTO

**Comment by jayd59** [comment]
You also need to remove VIRTUAL_PORT if it's set ?
