### ISSUE TITLE
issue with gitlab

### ISSUE THREAD

**Issue by zipeldiablo** [jwilder/nginx-proxy#94]
Hi i got an issue when using your reverse proxy with gitlab, is there a way to change the upload limit in nginx without having to docker exec everytime i relaunch?
Basically i cannot push big repository, this works fine if i bypass the reverse proxy

**Comment by md5** [comment]
I'd recommend dropping your own config file with `client_max_body_size` into a config file in `/etc/nginx/conf.d` in a derived image.

**Comment by mighty-code** [comment]
I have the same issue. Im new to this and don't know what I have to do. Where do I have to place which config file?

Thanks.

**Comment by md5** [comment]
I'd create a new image using a `Dockerfile` like this:

```Dockerfile
FROM jwilder/nginx-proxy
RUN echo "client_max_body_size 25m;" > /etc/nginx/conf.d/client_max_body_size.conf
```

You could then build an image based on that `Dockerfile` and run that instead of running `jwilder/nginx-proxy` directly.

An alternative would be to create a file outside the container called `client_max_body_size.conf` with the contents `client_max_body_size 25m;` (or whatever) and bind mount it into your `nginx-proxy` container:

    docker run -d --name nginx-proxy -v /var/run/docker.sock:/tmp/docker.sock \
        -v $(pwd)/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro \
        -p 80:80 jwilder/nginx-proxy

**Comment by zipeldiablo** [comment]
Oh i wasnt aware that we could add a file when running the container, was
worried to creater a dockerfile because depending on the image sometimes
the container won't run
I'll try this asap !
Ps : do you provide the sources for the files that you add in the
dockerfile? would be easier to just remount everything no?
Thanks for the help and that awesome image :)

2015-01-29 18:34 GMT+01:00 Mike Dillon <notifications@github.com>:

**Comment by jwilder** [comment]
@md5 :+1: on that approach. 

@zipeldiablo Everything is open-source... The Dockerile is here: https://github.com/jwilder/nginx-proxy/blob/master/Dockerfile

**Comment by zipeldiablo** [comment]
Tried adding the file at launch with -v working just fine, thanks a lot you
can close the issue :)

2015-01-29 18:47 GMT+01:00 Jason Wilder <notifications@github.com>:

**Comment by Toshiwoz** [comment]
Wouldn't be great to have a variable to override it?
