### ISSUE TITLE
Host networking - How to make it work?

### ISSUE THREAD

**Issue by k2xl** [jwilder/nginx-proxy#940]
How can I have nginx-proxy proxy to a container running with host networking? In my docker-compose I'm using `network_mode: host` and it doesn't work, but without it is works fine.

I need my container to run in host networking mode due to an annoying bug in docker where the client request IP address isn't forwarded properly to containers (unless net=host is true)

**Comment by k2xl** [comment]
Closing - found solution to ip problem
`request.environ.get('HTTP_X_REAL_IP', request.remote_addr)`

**Comment by bjornicus** [comment]
@k2xl I'm trying to solve this same issue; where did you put that line to solve it?

**Comment by YanzheL** [comment]
> Closing - found solution to ip problem
> `request.environ.get('HTTP_X_REAL_IP', request.remote_addr)`

I'm also curious about how do you solve the issue with this line?
