### ISSUE TITLE
2 apps => Error 503

### ISSUE THREAD

**Issue by sebastienserre** [jwilder/nginx-proxy#945]
Hello All
I'm using Docker on Ubuntu 16.04.

have a first docker-compose.yml:
`version: '2'
services:
  memcached:
    image: memcached:latest
    container_name: thivinfo_memcached
  
  mysql:
    image: mariadb:10.0.27
    container_name: thivinfo_mysql
    restart: unless-stopped
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./docker/mysql/database:/var/lib/mysql"

  apache:
    image: sebastienserre/apache-php-7.0
    mem_limit: 60m
    container_name: thivinfo_apache
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql
      - memcached:memcached
    ports:
      - "9080:80"

    volumes:
      - "./:/var/www/html"
    
    environment:
      VIRTUAL_HOST: thivinfo.local,*.thivinfo.local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: thivinfo_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - "/sessions"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    container_name: thivinfo_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

`
Which is running fine

I have duplicate it and renamed containers eand change port to have a second app running:

`version: '2'
services:
  memcached:
    image: memcached:latest
    container_name: thiverval_memcached
  
  mysql:
    image: mariadb:10.0.27
    container_name: thiverval_mysql
    restart: unless-stopped
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./docker/mysql/database:/var/lib/mysql"

  apache:
    image: sebastienserre/apache-php-7.0
    mem_limit: 60m
    container_name: thiverval_apache
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql
      - memcached:memcached
    ports:
      - "9081:80"

    volumes:
      - "./:/var/www/html"
    
    environment:
      VIRTUAL_HOST: thiverval.local,*.thiverval.local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: thiverval_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - "/sessions"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "81:80"
    container_name: thiverval_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

`
This second make a 503 error... which inf owould you need to help me solve this?

Many tyhx

**Comment by revolunet** [comment]
closable ?

**Comment by sebastienserre** [comment]
not solved but I close as I didn't received any help.
