### ISSUE TITLE
Allow http & https?

### ISSUE THREAD

**Issue by devinrsmith** [jwilder/nginx-proxy#95]
First of all I'm a big fan of this project! Thanks!

This is my first time working w/ docker-gen. I'm assuming there is some simple way to modify the template such that I can allow http and https instead of redirecting.

If I set an env VIRTUAL_REDIR=false, I'm assuming there is some way to not include the redirection code? I'm not familiar w/ the go templating language at all. I gave it a shot below, but I don't think `$container` is in scope. Getting an error (as expected?) `2015/02/03 18:04:08 unable to parse template: template: nginx.tmpl:54: undefined variable "$container"`. 

Any quick help would be much appreciated!

```
{{ if ne "false" $container.Env.VIRTUAL_REDIR }}
server {
	server_name {{ $host }};
	rewrite ^(.*) https://{{ $host }}$1 permanent;
}
{{ else }}
server {
        server_name {{ $host }};
        location / {
                proxy_pass http://{{ $host }};
                {{ if (exists (printf "/etc/nginx/htpasswd/%s" $host)) }}
                auth_basic      "Restricted {{ $host }}";
                auth_basic_user_file    {{ (printf "/etc/nginx/htpasswd/%s" $host) }};
                {{ end }}
        }
}
{{ end }}
```

**Comment by jwilder** [comment]
`$container` is not in scope at that point in the template.  You need to do something like https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L72 which grabs the value of the first container w/  `CERT_NAME` and assigns it to a variable.  You should be able to use that variable in your if clause.

**Comment by devinrsmith** [comment]
Thanks. This seems to work:
```
{{ $virtualRedir := (first (groupByKeys $containers "Env.VIRTUAL_REDIR")) }}
{{ if ne $virtualRedir "false" }}
server {
        server_name {{ $host }};
        rewrite ^(.*) https://{{ $host }}$1 permanent;
}
{{ else }}
server {
        server_name {{ $host }};
        location / {
                proxy_pass http://{{ $host }};
                {{ if (exists (printf "/etc/nginx/htpasswd/%s" $host)) }}
                auth_basic      "Restricted {{ $host }}";
                auth_basic_user_file    {{ (printf "/etc/nginx/htpasswd/%s" $host) }};
                {{ end }}
        }
}
{{ end }}
```
