### ISSUE TITLE
nginx regex parsing buggy

### ISSUE THREAD

**Issue by nshtg** [jwilder/nginx-proxy#961]
In nginx you can do things like this:

```
server_name ~^auth\d{0,2}\.example\.pw$;
```
( this would match auth.example.pw, auth1.example.pw, ... until auth99.example.pw )

However nginx-proxy (if passed as `VIRTUAL_HOST`) will cut after the `,` creating weird artifacts that do not at all behave as intended.

As a workaround we can use an asterik-based solution, however this is not optimal and could have unintended consequences:

```
VIRTUAL_HOST: ~^auth.*\.example\.pw$$
```

If you do not intend to fix this bug I would however suggest adding a note to the readme that commas are not allowed and regexs using them will not work =)

**Comment by kamermans** [comment]
Very good point @nshtg, thanks for reporting!  I'm not sure if @jwilder is aware of this issue, but it makes perfect sense to me, and I agree, either we should fix the bug, or we should document it as a limitation.

Off the top of my head, I am struggling to see how we could create a delimiter that couldn't occur naturally in PCRE, but I am a PCRE junkie, so I'll think about it :)  I guess one sort-of nasty solution would be to have another var called `VIRTUAL_HOST_DELIMITER`, which defaults to `,`.  Then you could change that to something like `#`, and use that to separate your virtual hosts.

For your regex, you can eliminate the comma by making the two digits optional instead:
```
~^auth\d?\d?\.example\.pw$
```
