### ISSUE TITLE
Varnish Cache and SSL termination

### ISSUE THREAD

**Issue by Bram-Zijp** [jwilder/nginx-proxy#965]
I would like to use nginx-proxy with a Varnish cache layer in front of it. In my normal nginx configuration I listen to port 443 and simply proxy to port 80 where Varnish will listen.

Could you implement this feature?

**Comment by kamermans** [comment]
> In my normal nginx configuration I listen to port 443 and simply proxy to port 80 where Varnish will listen.

In this scenario, you can replace `nginx` with `nginx-proxy`.  When you start your Varnish container to listen on port `80`, as long as `nginx-proxy` has the SSL certificate for the give hostname, it will listen on `443` and send the requests back to Varnish on `80` by default.

> I would like to use nginx-proxy with a Varnish cache layer in front of it. 
This is the opposite of the other sentence.  If you want Varnish in front if `nginx-proxy`, just add it as backend in VCL.

**Comment by kimlonglecis** [comment]
> > In my normal nginx configuration I listen to port 443 and simply proxy to port 80 where Varnish will listen.
> 
> In this scenario, you can replace `nginx` with `nginx-proxy`. When you start your Varnish container to listen on port `80`, as long as `nginx-proxy` has the SSL certificate for the give hostname, it will listen on `443` and send the requests back to Varnish on `80` by default.
> 
> > I would like to use nginx-proxy with a Varnish cache layer in front of it.
> > This is the opposite of the other sentence.  If you want Varnish in front if `nginx-proxy`, just add it as backend in VCL.

Varnish is the last piece component I am trying to put together in my Wordpress Stack.

I ran varnish by running:
`
nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"      
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

    networks:
      - nginx-proxy
varnish:
    image: varnish
    container_name: varnish
    # depends_on:
    #   - nginx-proxy
    restart: always
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    expose:
    - 80
    - 443
    networks:
      - nginx-proxy
      - internal
`
./default.vcl
`
vcl 4.0;

backend sentrytire {
    .host = "172.19.0.3";
    .port = "80";
}

sub vcl_recv {

}

sub vcl_backend_response {
    set beresp.ttl = 10s;
    set beresp.grace = 1h;
}

sub vcl_deliver {
    if (obj.hits > 0) {
        set resp.http.X-Cache = "cached";
    } else {
        set resp.http.X-Cache = "uncached";
    }
}
`
I confirm if checking curl -IL http://example.com, I am getting varnish cache working fine.
`
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 14 Sep 2019 00:35:52 GMT
Content-Type: text/html; charset=UTF-8
Vary: Accept-Encoding
X-Powered-By: PHP/7.3.6
Link: <http://example.com/wp-json/>; rel="https://api.w.org/"
Link: <http://example.com/>; rel=shortlink
X-Varnish: 65540 32777
Age: 1
Via: 1.1 varnish (Varnish/6.2)
X-Cache: cached
Accept-Ranges: bytes
Content-Length: 168575
Connection: keep-alive
`
Now here come the hard part setting up jwilder/nginx-proxy to reverse proxy port 443 to varnish on port 80.

By default, its nginx.tmpl will generate the /etc/nginx/conf.d/default.conf. I follow some tutorial to edit the SERVER part of example.com to
`
location / {
    # NETWORK nginx-proxy IP of Varnish Container is 172.18.0.4
    proxy_pass http://172.18.0.4:80;
}
`
But doing service nginx restart will reset /etc/nginx/conf.d/default to its nginx.tmpl file.

So I am thinking to edit the nginx.tmpl but i have no idea where the file reside. I also would like to run multiple container with multiple domain to cache thru 1 varnish container. I still have question mark on that. If anyone has successfully setting up this stack, I really appreciate your inputs and answers on this.

**Comment by jfrancais** [comment]
following.  I'm also trying to get this scenario working where I have one varnish container with to cache all my wordpress and send back to nginx for https to end user.
