### ISSUE TITLE
client_max_body_size

### ISSUE THREAD

**Issue by pdwonline** [jwilder/nginx-proxy#974]
I use the reverse proxy gen with webdav (nextcloud) but it will generate an error with large files. That seems because the parameter client_max_body_size 0;  is missing in the nginx proxy template and thus nog generated. How/where to add this?

**Comment by thaJeztah** [comment]
See https://github.com/jwilder/nginx-proxy/issues/29 for some discussion around this

**Comment by saesh** [comment]
See [this comment](https://github.com/jwilder/nginx-proxy/issues/981#issuecomment-345434827) in #981.

**Comment by jlegido** [comment]
Hi @pdwonline.

Maybe makes sense helping this issue being closed as soon as possible, since there are currently almost 400 open issues.

Not sure what's the suggested way in github, maybe editing the title and adding "[RESOLVED]" or "[DUPLICATED]" at the beginning?

Many thanks.
