### ISSUE TITLE
Upstream SSL

### ISSUE THREAD

**Issue by andrefernandes** [jwilder/nginx-proxy#99]
Template could be modified in order to support upstream SSL as well (proxy_pass to https).

If I get a working one I'll post it here.

**Comment by md5** [comment]
I might take a pass at implementing this by supporting a `VIRTUAL_PROTO` environment variable on the proxied container.

I could even see this being extended to support interesting things like `VIRTUAL_PROTO=fastcgi`to support easily proxying something like the `wordpress:fpm` image I sent [this pull request](https://github.com/docker-library/wordpress/pull/61) for, or `VIRTUAL_PROTO=ajp` to support proxying to `tomcat` on the AJP connector.

**Comment by md5** [comment]
Here's a bit from [the Nginx docs](http://nginx.org/en/docs/http/ngx_http_upstream_module.html) that shows some of the supported proxy types:

> The ngx_http_upstream_module module is used to define groups of servers that can be referenced by the proxy_pass, fastcgi_pass, uwsgi_pass, scgi_pass, and memcached_pass directives.

**Comment by md5** [comment]
Combining this with the multiple path support requested in #47 would also be interesting to support proxying a bunch of CGI-style microservices (ht/ @kendall).
